### ISSUE TITLE
Trinity does not accept incoming peer connections when in light mode

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#1003]
It also does not set up NAT port mapping. If we did both, we should be able to keep a higher peer count and faster syncs. But do we want that?

**Comment by pipermerriam** [comment]
What are the trade-offs here?  My intuition is:

- lower peer count -> more performant light node assuming it finds a sufficient number of peers serving LES
- higher peer count -> client is a more *responsible* participant in the network, serving headers when it can.

**Comment by gsalgado** [comment]
> lower peer count -> more performant light node assuming it finds a sufficient number of peers serving LES

Do you mean that support the LES protocol or that have `serveHeaders` set to True? In light mode we currently connect to any peers that support the LES protocol, regardless of whether or not they have `serveHeaders` set to True.

We could accept incoming connections but have a low default value for `max_peers`

**Comment by pipermerriam** [comment]
I wasn't aware of the `serveHeaders` flag so not that.

**Comment by carver** [comment]
:+1: to allowing light peers to connect to us, with a low-ish limit on leeching light peers (and probably a rate-limiter on light serving requests)
