### ISSUE TITLE
install py-evm fatal error: secp256k1_ecdh.h: no such file

### ISSUE THREAD

**Issue by johnys222** [ethereum/py-evm#1021]
* py-evm Version: 0.2.0a26
* OS: linux ubuntu 16.04 64bit
* Python Version (python --version):3.6.5
* Environment (output of `pip freeze`):pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.6)

### What is wrong?
when i use souce code to install
use  command "python3 setup.py install to install"  and Get the following error during the installation process
like this:
build/temp.linux-x86_64-3.6/_libsecp256k1.c:493:28: fatal error: secp256k1_ecdh.h: no such file
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
and  I found a solution to use command pip install -r requirements.txt but in source files I did not find this file  how to fix it.？ thanks

**Comment by cburgdorf** [comment]
Are you looking to work on the source of just want to run a Trinity node?

If you like to install from source, I recommend to follow the [contributing guide](http://py-evm.readthedocs.io/en/latest/contributing.html). If you just want to run a Trinity node, the [quickstart](http://py-evm.readthedocs.io/en/latest/quickstart.html) would best answer this.

Please let me know if this helps or if there's anything else we could do to get you unstuck.

**Comment by pipermerriam** [comment]
Can you try this: https://github.com/JoinMarket-Org/joinmarket/wiki/Installing-the-libsecp256k1-binding#installing-the-libsecp256k1-binding-on-linuxosx

**Comment by johnys222** [comment]
No, I don't need just want to run a Trinity node, I just want to test a python script, this script needs to rely on the py-evm library, so I want to install this library

**Comment by pipermerriam** [comment]
@johnys222 the link I sent you is instructions on how to install the necessary system dependencies to fix the error you encountered.

**Comment by johnys222** [comment]
@pipermerriam  thanks  let me try it

**Comment by johnys222** [comment]
@cburgdorf  I still don't quite understand how to install py-evm? I have downloaded the source code to my local, and have already created a pure Python environment, but I don't understand how to install the py-evm library, because I am a newbie, thank you

**Comment by cburgdorf** [comment]
@johnys222 gotcha. So you basically want to write your own program that uses `py-evm` as a library. You should be able to just specify `py-evm` as a `install_requires` in your `setup.py` file and then install dependencies through pip.

But here's the deal, using `py-evm` as a library is one of the major uses cases that we want to support so let me roll up my sleeves and write a quick guide for our documentation that will walk you through creating a simple application/script that uses Py-EVM to e.g. measure the gas cost of some task.

**Comment by johnys222** [comment]
@cburgdorf  Yes, you are very right, I am the idea, I have tried the way the pip tool is installed and the way the source is installed. It will contain some errors, which are mentioned above, so I want to ask for your help,  Thank you for writing this quick guide, it would be great

**Comment by cburgdorf** [comment]
Happy to hear it was helpful. And at the same time, I happy you brought it up because that helped us get better documentation and will certainly help other beginners as well!
