### ISSUE TITLE
Do not ignore data requests while performing DAO fork check

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#1025]
### What is wrong?

Currently, while we're waiting for a remote to send us the DAO fork block headers in order to determine if we're on the same side of the fork, we ignore any data requests they make. That seems to cause them treat us as a useless peer and disconnect.

It'd explain why when running on ropsten trinity can keep a high peer count but on mainnet most nodes disconnect shortly after the initial handshake.

### How can it be fixed

Need to handle data requests while performing the DAO fork check. Or maybe keep ignoring them during the DAO fork check, but re-queue them once the check is completed

**Comment by gsalgado** [comment]
@pipermerriam https://github.com/gsalgado/py-evm/tree/misc has a WIP fix for this. I've been running it on mainnet and it's syncing reliably keeping a peer count of 25, but it still hasn't synced up to the DAO fork block and I know geth will treat peers differently depending on whether their announced chain HEAD is past that, so it'd be great if you could give it a spin in case you have a DB synced past the DAO fork block

**Comment by pipermerriam** [comment]
I unfortunately do not have such a data dir.  I'm working on syncing a trinity node now but it's slow going.

**Comment by pipermerriam** [comment]
@gsalgado Going to try and ingest this issue tomorrow.

Side note, we should cache information about which side of the fork peers are on.

**Comment by gsalgado** [comment]
Another way of fixing this would be to let peers be added to `PeerPool` without the DAO fork check, and then perform the check in `ChainSyncer` by keeping a list of peers for which the check is pending and having its `_handle_msg_loop()` do the following for every msg read from the queue:
   1. If peer has passed DAO fork check, process msg normally  
   2. Else if cmd is not BlockHeaders, add it to the list of msgs received by that peer and return
   3. Else if cmd is BlockHeaders
    3.1 If DAO fork check is successful, handle all previously received messages from the peer
    3.2 Else disconnect from peer and discard all previous messages
