### ISSUE TITLE
Add a CI job to check if the docs build cleanly

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1028]
### What is wrong?

Currently, we do not have a CI job to test if our docs still build cleanly which causes us to easily break the docs (see #1026)

### How can it be fixed

Setup a CI job that runs the doc generation command and check if it throws any errors.

**Comment by carver** [comment]
There is an example doctest tox job in web3.py: https://github.com/ethereum/web3.py/blob/master/tox.ini

**Comment by cburgdorf** [comment]
This landed in https://github.com/ethereum/py-evm/commit/2b7a456a060803b1d4f114f76f9f7e976e865e04
