### ISSUE TITLE
Matching between requested headers and received headers.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1035]
### What is wrong?

The syncing code in `p2p.chain` under `BaseHeaderChainSyncer._sync` makes an assumption about the received headers which is not necessarily correct.

### What I think is going on (please confirm)

In trying to understand where these are coming from, I'm working to understand the syncing logic and want to be sure I have it correct.

- [`p2p.chain.BaseHeaderChainSyncer._sync#L205`](https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/chain.py#L205) requests headers from the chosen `peer`
- [`p2p.chain.BaseHeaderChainSyncer._fetch_missing_headers#L253`](https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/chain.py#L253) issues a request to the peer for some headers.
- [`p2p.chain.BaseHeaderChainSyncer._fetch_missing_headers#L256`](https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/chain.py#L256) waits for new headers to show up in the `_new_headers` queue.
- When the new headers show up, [`p2p.chain.BaseHeaderChainSyncer._handle_block_headers#L276`](https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/chain.py#L276) puts the new headers in the `_new_headers` queue.

So, IIUC, if **any** peer sends us a `BlockHeaders` message, the new headers will end up in the `_new_headers` queue and the `headers` returned in [`_fetch_missing_headers`](https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/chain.py#L256) are not guaranteed to originate from the peer they were requested from.

Alternate explanation of what I'm trying to understand.

1. We request headers from peer `A`
2. Peer `B` sends us a `BlockHeaders` message before peer `A` responds
3. The headers from peer `B` end up in the queue.
4. We treat the headers received from peer `B` as if they were sent from peer `A`.

If this is the case then I believe we have a systemic problem that we need to solve.

### How we can solve it (maybe)

My understanding is that there is no `id` for these types of requests so we cannot do `id` based linking between requests and responses.

Without an `id` based way to link requests and responses, I think we have to do it in a probabilistic manner.

1. instead of a single queue for headers, lets use a queue per peer.
2. use the [`PeerPoolSubscriber.deregister_peer`](https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/peer.py#L706) API to clear out stale queues.
3. maintain list of *header requests* that are awaiting responses.
4. on receipt of `BlockHeaders` message, we only put it in the queue if it has a corresponding *header request* which is satisfied by the headers contained in the message.

Defining *header request*:

- A *header request* would be defined as the requesting parameters in the `GetBlockHeaders` message.  
- A match would be defined as a non-empty set of headers which is a subset of the full set of headers that could be generated by the request.

Any received headers that cannot be correlated to a specific peer and header request should be logged and discarded.

**Comment by gsalgado** [comment]
We only send header requests to the peer we've chosen (the one with highest TD) to sync with. Once we have a batch of headers we'll request body parts for subsets of them to all available peers

If other peers manage to guess the headers we're expecting at any point in time and send them before the peer we're syncing with, then yeah, what you describe could happen, but these would still have to be validated before being inserted in our chain.

Also, I'm not sure I understand how that relates to the traceback here

**Comment by pipermerriam** [comment]
I think that you may be right about this being unrelated to the stack trace.  Looking back I see that when I started tracing my way through the APIs I was in `_download_block_parts` which occurs after the code in question has processed.

**Comment by pipermerriam** [comment]
Opened #1037 for the root cause of the original bug.

**Comment by pipermerriam** [comment]
Also, opened https://github.com/ethereum/py-evm/pull/1038 which is an utterly incomplete attempt to start codifying a solution to this.

**Comment by gsalgado** [comment]
Should we close this?

**Comment by pipermerriam** [comment]
I don't think so.  This is something that I still think needs to be done (though I'm willing to be convinced otherwise).  It feels like we should have reliable request/response pairing.

**Comment by gsalgado** [comment]
Hmm, ok. Would you care to elaborate on why you think this needs to be done?

**Comment by carver** [comment]
I think this will be implemented in the process of solving #868
