### ISSUE TITLE
Broken algorithm for generating block header numbers

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1036]
### What is wrong?

https://github.com/ethereum/py-evm/blob/3dbad6b8ea82b2f325b3fce6d96a7f0dc2b5642f/p2p/chain.py#L775-L782

The algorithm linked above and included here is not generating block numbers according to protocol.

```python
if reverse:
    low = max(0, block_number - limit)
    high = block_number + 1
    block_numbers = reversed(range(low, high, step))
else:
    low = block_number
    high = block_number + limit
block_numbers = range(low, high, step)
```

For example, if requesting `5` headers starting at block number `0`, with a skip of `1`:

- expected correct: `0, 2, 4, 6, 8`
- actual: `0, 2, 4` (doesn't return 5 headers)

### How can it be fixed

Need to fix how the limits are computed to take into account the skip size so that we still return the appropriate number of headers.

**Comment by gsalgado** [comment]
I guess this might be one of the reasons why some peers would disconnect from us as a useless_peer
