### ISSUE TITLE
Implement 8 more of the core eth_* read-only RPC endpoints

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1061]
This is a tracking issue for the next alpha release milestone. The endpoints are a subset of #612, and can be chosen from that list as desired. Feel free to make individual PRs for each endpoint chosen (or group them if there are a few that are trivial to group). Link the PRs back to this issue for tracking.

  - [x] `eth_accounts` (always return `[]`)
  - [ ] `eth_syncing`
  - [ ] `eth_gasPrice` (should get its own issue to plan the algorithm)
  - [x] `eth_getBlockTransactionCountByHash`
  - [x] `eth_getBlockTransactionCountByNumber`
  - [x] `eth_getUncleCountByBlockNumber` block string
  - [x] `eth_call`
  - [x] `eth_estimateGas`
  - [ ] `eth_getTransactionByHash`
  - [x] `eth_getTransactionByBlockHashAndIndex`
  - [x] `eth_getTransactionByBlockNumberAndIndex`
  - [ ] `eth_getTransactionReceipt`
  - [x] `eth_getUncleByBlockHashAndIndex`
  - [x] `eth_getUncleByBlockNumberAndIndex` block int
  - [x] `eth_getUncleByBlockNumberAndIndex` block string
  - [ ] `eth_getLogs`

**Comment by voith** [comment]
@carver I couldn't find `eth_sign`, nor did I find it #612

**Comment by pipermerriam** [comment]
@voith we probably won't be implementing `eth_sign` since Trinity will not have any account management.  We can however implement something that always raises an exception since there is no way to have an unlocked account.

**Comment by voith** [comment]
@pipermerriam Are there any plans to implement the personal module?
Also, would it be possible to mock this behaviour in `eth-tester`?

**Comment by pipermerriam** [comment]
`personal_` will be lower priority for a while here.

1. because we don't plan to do key management.
2. because it's a non-standard API that only exists in `geth`

We can add or mock any behavior in `eth-tester` but it's a bit ambiguous to me how to best implement something like the `personal_` module functionality in a *modular* fasion.  Since it's non-standard JSON-RPC API, I wouldn't want it to be a *core* piece, but rather something that could be enabled.

**Comment by carver** [comment]
Sweet, I guess someone just forgot to check off some methods after implementing them. With those, and the three more implemented, we now have 8 more than we thought we had. Just under the wire for today's release. :)
