### ISSUE TITLE
Make fix-unclean-shutdown a Plugin

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1069]
### What is wrong?

Currently, the `fix-unclean-shutdown` command is implemented directly in the main trinity code base. This could easily live under `trinity/plugins` similar to how the `trinity attach` command is handled.

### How can it be fixed

Move code and wrap a plugin around it.

**Comment by cburgdorf** [comment]
I assigned this issue to myself but that really just means I'll take responsibility for landing this for the next milestone *if no one else does*. This is a great issue for starters and I'm happy to provide guidance if needed.

**Comment by timfong1015** [comment]
Hi, am new to open source development (but have been writing Python code for ML/data science for over a year) and  would like to give this a shot, with guidance =)

**Comment by cburgdorf** [comment]
@timfong1015 that would be great! Have a look at this existing plugin

https://github.com/ethereum/py-evm/blob/100f5c7d6b3cd97f167991e57f8766f19969e3b9/trinity/plugins/builtin/attach/plugin.py

Basically, you have to create a plugin similar to that and move *unclean shutdown repair logic* there, so we get rid of this in `main`

https://github.com/ethereum/py-evm/blob/master/trinity/main.py#L145-L146

Does that get you off the ground?

**Comment by timfong1015** [comment]
@cburgdorf  Thanks, I am drilling into this now and will let you know if I need more assistance.

**Comment by timfong1015** [comment]
@cburgdorf I have a first try at the plugin, but when I try to run pytest I get a lot of errors and it doesn't run. I'm hesitant to make a PR if I haven't tested the code yet. I've attached the output from my pytest attempt. 
[pytest_fail_trinity.txt](https://github.com/ethereum/py-evm/files/2243033/pytest_fail_trinity.txt)

**Comment by pipermerriam** [comment]
My removal of this from the current milestone doesn't change it's priority, just denoting that it isn't *required* for us to make the release.

**Comment by cburgdorf** [comment]
Hey @timfong1015 do you still plan to work on this issue? Regarding your attached output, looks like you are missing a dependency. How did you install the dependencies? It's best to install them using `virtualenv` as described in the [contributing guide](http://py-evm.readthedocs.io/en/latest/contributing.html).

**Comment by cburgdorf** [comment]
@timfong1015 I cleaned that one up https://github.com/ethereum/py-evm/pull/1182

Feel free to checkout other issues that are flagged as "Good First Issue" (but feel free to also check out any other issues!)

https://github.com/ethereum/py-evm/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22
