### ISSUE TITLE
StateDownloader should retry immediately after receiving empty reply from peer

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#1077]
### What is wrong?

During a state sync, sometimes a peer won't have the trie nodes we requested, and so will send us an empty `NodeData` msg.  When that happens we just move on and those nodes are re-requested only after the timeout (20s) has passed.

### How can it be fixed

Whenever we get an empty `NodeData` from a peer, we should look up the nodes that were originally requested to that peer and re-request them to a different peer.

**Comment by pipermerriam** [comment]
Seems like we need to keep some sort of tracking around which peers do not have certain trie nodes so that we can get to a point where we know "no peers have this trie node".  I believe this is needed for us to get out of a stalled state sync as noted in #1073
