### ISSUE TITLE
Trinity stops making peer connections during the state sync

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1093]
### What is wrong?

Logs here: https://gist.githubusercontent.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/a523c6ea4d02f96ac6f78a559e91453b7f69f065/trinity-fast-sync-log-no-more-peer-connection-attempts.log

Initially, there are lots of attempts to connect with peers, however, eventually, those logs stop showing up.  Something happened (haven't dug into logs yet) that has caused few or no more attempts to connect with peers to happen.

### How can it be fixed

Don't know yet.

**Comment by gsalgado** [comment]
```
   ERROR  07-25 14:07:27     service  Unexpected error in <p2p.discovery.DiscoveryService object at 0x7fd8281cc668>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/py-evm/p2p/service.py", line 60, in run
    await self._run()
  File "/home/piper/projects/py-evm/p2p/discovery.py", line 339, in _run
    await self.maybe_connect_to_more_peers()
  File "/home/piper/projects/py-evm/p2p/discovery.py", line 351, in maybe_connect_to_more_peers
    self.proto.get_nodes_to_connect(self.peer_pool.max_peers))
  File "/home/piper/projects/py-evm/p2p/peer.py", line 936, in connect_to_nodes
    await self.start_peer(peer)
  File "/home/piper/projects/py-evm/p2p/peer.py", line 851, in start_peer
    msgs = await self.ensure_same_side_on_dao_fork(peer)
  File "/home/piper/projects/py-evm/p2p/peer.py", line 981, in ensure_same_side_on_dao_fork
    parent, header = headers
ValueError: not enough values to unpack (expected 2, got 0)
```

Could this be a bug introduced in #1063, which treats empty headers response as valid?

**Comment by gsalgado** [comment]
AFAICT, the above wouldn't have happened if we were still calling `validate_header_response(headers)` as that'd raise a `ValidationError`, which is would simply result in a failed handshake

**Comment by gsalgado** [comment]
https://github.com/ethereum/py-evm/pull/1063/files#diff-0c5a90ea9349bdb0b8d152d6c4b24583L859

**Comment by pipermerriam** [comment]
Looks like an easy fix, we just need to check that the returned headers for the DAO check have length 2 before unpacking them.

I don't think `validate_header_response` is the right solution here since an empty response is *valid* for a generic `GetBlockHeaders` request, it's just that in this specific case, we require the response to contain all of the results.  I think that we need two validation levels, one for the *objective* question of is it a valid response according to protocol, and then the subjective one of "does this response work for the reason we requested".  In this case, a simple `len(headers) == 2` check should suffice.

**Comment by gsalgado** [comment]
Closing as this issue was never present on master
