### ISSUE TITLE
pong from kademlia?

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/py-evm#1096]
* py-evm Version: 0.1.0a13
* OS: linux
* Python Version (python --version): 3.6.5

### What is wrong?

Get these randomly, unsure what they are.

```
    INFO  07-25 17:17:20    kademlia  unexpected pong from <Node(0xdb2f@195.43.95.18)> (token == 0x857639a6df30ac85e4a035673592a8d0fce49229deef03409056d48568c9dd9d)
    INFO  07-25 17:17:21    kademlia  unexpected pong from <Node(0x985b@94.23.28.180)> (token == 0x9205dfd1f04ec232b55f7a1a23bc9174ec3bcdd24a35e7d670b3edde6e9509d1)
    INFO  07-25 17:17:21    kademlia  unexpected pong from <Node(0x985b@94.23.28.180)> (token == 0x9205dfd1f04ec232b55f7a1a23bc9174ec3bcdd24a35e7d670b3edde6e9509d1)
    INFO  07-25 17:17:21    kademlia  unexpected pong from <Node(0x985b@94.23.28.180)> (token == 0x9205dfd1f04ec232b55f7a1a23bc9174ec3bcdd24a35e7d670b3edde6e9509d1)
    INFO  07-25 17:17:21    kademlia  unexpected pong from <Node(0x985b@94.23.28.180)> (token == 0x9205dfd1f04ec232b55f7a1a23bc9174ec3bcdd24a35e7d670b3edde6e9509d1)
    INFO  07-25 17:17:21    kademlia  unexpected pong from <Node(0x985b@94.23.28.180)> (token == 0x9205dfd1f04ec232b55f7a1a23bc9174ec3bcdd24a35e7d670b3edde6e9509d1)
```

**Comment by veox** [comment]
``` sh
alias g='grep --color'
g "unexpected pong from" trinity.log | g -oE "([0-9]{1,3}\.){3}[0-9]{1,3}" | \
    sort | uniq -c | sort -n | wc -l
```

gives me about 60 unique IPs (in the last hour, on Ropsten).

The message is printed on catching a `KeyError` when looking up if the pong matches a previously-sent ping:

https://github.com/ethereum/py-evm/blob/ab941677e9c74162973397a179a73000bb76ad88/p2p/kademlia.py#L443-L448

It would seem that the `pingid` is missing; so, unless the `remote` is sending an unsolicited Pong message (without us previously sending a Ping), we've likely stored the `pingid` wrong, or failed to store it altogether.

**Comment by gsalgado** [comment]
Some of those were probably coming from buggy parity nodes, but we've introduced a workaround for that in https://github.com/ethereum/py-evm/pull/1011. If you're still seeing those they must be because we're only receiving/processing those pongs after the timeout has elapsed, so there's not much we can do. If that's not the case, please reopen

**Comment by fubuloubu** [comment]
Great work guys! I will close now and reopen if I discover it again.
