### ISSUE TITLE
Experiment with batching db writes and using a local cache

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1102]
### What is wrong?

According to some basic analysis the number of transactions in a block is responsible for most of the time it takes to process that block.

It would be interesting to see what kind of difference it makes to use the [batch writing API](https://plyvel.readthedocs.io/en/latest/user.html#write-batches) to reduce the number of times that we have to write directly to LevelDB.

### How can it be fixed

We could put a thin cache on top of the database within the database process, and have a periodic task that writes data from the cache into the database either when the cache reaches a certain size or after a set amount of time (ideally whichever comes first).

**Comment by pipermerriam** [comment]
If someone picks this up i can provide you with a database dump of the chain data dir at around block 4,900,000 which is where transaction counts get consistently high (and sync times slow down).

**Comment by waprin** [comment]
I'd be interested in looking into this (though note I'm a newb with ethereum and this project so no big deal if someone gets it done before me, since it might take me a while to get caught up). 

What's the easiest way for me to get the dump? (also how big is it?)

**Comment by pipermerriam** [comment]
@waprin 50gb, drop me private message on gitter and I'll send you a link to download the dump from.

**Comment by gsalgado** [comment]
ISTM you're talking only about fast-sync here? During a fast-sync, all we do is download the block bodies (transactions, uncles, receipts) and store them in the DB, so yeah, the # of transactions is the main thing that will affect how fast we can import blocks during a fast sync. For someone looking into this, a good starting point would be `eth.db.trie.make_trie_root_and_nodes()` and `BaseChainDB.persist_trie_data_dict()`, and the latter is where I think it'd make sense to use the batching API

**Comment by pipermerriam** [comment]
https://github.com/ethereum/py-evm/blob/653d563234b5722b9da880cc1f7e6f9ced14d721/eth/db/chain.py#L281

I believe this also produces an `O(n)` amount of writes during fast sync.

**Comment by gsalgado** [comment]
I'm gathering some profiling stats for fast-sync and although I'm doing so on a 34GB ropsten DB, I believe this is relevant as it suggests optimizing our DB access may not yield any significant performance improvements as the time taken to persist the data is insignificant when compared to the time taken to generate the tries. 

```
    1827    0.050    0.000   44.991    0.025 trie.py:16(make_trie_root_and_nodes)
    ...
    43213    0.603    0.000    0.603    0.000 {method 'put' of 'plyvel._plyvel.DB' objects}
     1704    0.072    0.000    0.601    0.000 chain.py:475(persist_trie_data_dict)
```

@pipermerriam if you want to get the stats for a run against the mainnet DB you can simply run `python -m p2p.chain -fast -db </path/to/trinity/chain/db> -enode <your-local-geth>`

**Comment by pipermerriam** [comment]
Alright, I'm going to close this for now.  Thanks for doing the work to actually measure this :smiley:
