### ISSUE TITLE
Create guide on how to write plugins

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1103]
### What is wrong?

When the plugin API has settled a bit (so, not ready yet!), we should add a guide that explains how to create plugins.

### How can it be fixed

:writing_hand: :wine_glass: :writing_hand: :sun_with_face: :wine_glass: :writing_hand:

**Comment by pipermerriam** [comment]
I think it would be good to write down some of the high level things like intended use cases and basics of the API early, and we can put some big loud `.. warning::` admonitions at the top of that page.

**Comment by pipermerriam** [comment]
Also maybe link into the code to the current internals which are implemented as plugins.

**Comment by cburgdorf** [comment]
I think I'm gonna sit down and come up with something after #1212 lands. The API is still very early and in flux but it's approaching a state where one can do more and more useful things. The usefulness will climb up when we begin to broadcast more and more events via the eventbus.

**Comment by cburgdorf** [comment]
The guide landed a while ago (Albeit, there's still much room for improvement)
