### ISSUE TITLE
EIP145 - Bitwise shifting operations

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1104]
### What is wrong?

Need to implement https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md

### How can it be fixed

Implement the new opcode (and the contstantinople VM)

**Comment by cburgdorf** [comment]
I'm looking into this but I'll probably tackle #1111 before to not code in the dark. I haven't gotten that deep into the EVM yet and I think this may be a nice opportunity to grow stronger EVM skills.
