### ISSUE TITLE
More debug output about connected peers: show messages per second

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1121]
### What is wrong?

It's a derivative metric from other metrics we are already showing, but I want to see messages per second as it is indicative of whether a peer we are connected to is *performing* well.  It might even be nice to have a full breakdown in the `trace` logging of individual command types.

### How can it be fixed

Change the reporting for peer details to look like:

```bash
ETHPeer  <Node(0x5669@127.0.0.1)>: alive=yes uptime=1m3s msgs=1234 (32/s) timeouts=245 most_rcvd=Transaction
```

- use `yes` and `no` instead of `true` and `false` since they are more concise.
- need a new util to convert a `timedelta` into a nice human readable string.  
- figure out the correct period for the messages/time metric.
  - messages per second seems like it might create too small of numbers
  - messages per minute might be very large
- start tracking timeouts on peers.  Doesn't have to be perfect but we should be able to get close.

In addition, sort the peers by uptime, showing longest uptime first.

**Comment by gsalgado** [comment]
#1166 added a timeout counter to the report, as well as average response time, which I believe is more useful than msg/s, so maybe we can close this one?
