### ISSUE TITLE
Syntax error on startup 

### ISSUE THREAD

**Issue by kyledewy** [ethereum/py-evm#1122]
* py-evm Version: Trinity v0.1.0-alpha.12 "Grace Hopper"
* OS: linux: ubuntu 16.04
* Python Version (python --version): Python 3.5.2
* Environment (output of `pip freeze`): 
asn1crypto==0.24.0
async-lru==0.1.0
attrdict==2.0.0
backcall==0.1.0
bloom-filter==1.3
cachetools==2.1.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
coincurve==7.1.0
cryptography==2.3
cytoolz==0.9.0.1
decorator==4.3.0
eth-abi==1.1.1
eth-account==0.2.3
eth-bloom==1.0.0
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.1.0
eth-utils==1.0.3
hexbytes==0.1.0
idna==2.7
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.12.1
lru-dict==1.1.6
lxml==4.2.3
netdisco==1.5.0
netifaces==0.10.7
parsimonious==0.8.0
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
plyvel==1.0.4
prompt-toolkit==1.0.15
ptyprocess==0.6.0
py-ecc==1.4.3
py-evm==0.2.0a29
pycparser==2.18
pycryptodome==3.6.4
pyethash==0.1.27
Pygments==2.2.0
pysha3==1.0.2
python-dateutil==2.7.3
requests==2.19.1
rlp==1.0.1
simplegeneric==0.8.1
six==1.11.0
toolz==0.9.0
traitlets==4.3.2
trie==1.3.7
trinity==0.1.0a13
uPnPClient==0.0.8
urllib3==1.23
wcwidth==0.1.7
web3==4.3.0
websockets==4.0.1
zeroconf==0.20.0

### What is wrong?
After installing Trinity in a virtual environment. I ran the following commands: 
`apt-get install python3.6-dev`
`apt-get install python3-pip`
`virtualenv -p python3 venv`
`pip3 install -U trinity`

I receive the following error when I try to start up Trinity:

```
Traceback (most recent call last):
  File "/home/dog/software/trinity/venv/bin/trinity", line 7, in <module>
    from trinity import main
  File "/home/dog/software/trinity/venv/lib/python3.5/site-packages/trinity/__init__.py", line 4
    __version__: str
               ^
SyntaxError: invalid syntax
```

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by cburgdorf** [comment]
>File "/home/dog/software/trinity/venv/lib/**python3.5**/site-packages/trinity/__init__.py"

Looks like you are running under Python 3.5 which is not supported (Trinity is 3.6+)

Try running `virtualenv -p python3.6 venv` to explicitly get version `3.6`.
