### ISSUE TITLE
Unify `ValidationError`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1125]
### What is wrong?

https://github.com/ethereum/py-evm/pull/1089/files#r206404376

As noted in this comment, there is a valid concern that our duplicate `ValidationError` exceptions could easily be mixed up, causing us to not be catching the exception we think we are catching.

### How can it be fixed

Once https://github.com/ethereum/eth-utils/issues/114 has been done, modify the codebase to use that exception class for all `ValidationError` exceptions.

**Comment by carver** [comment]
It could potentially go in `eth_utils.exceptions.ValidationError`.

**Comment by pipermerriam** [comment]
https://github.com/ethereum/eth-utils/issues/114

**Comment by glaksmono** [comment]
Would like to take on this once https://github.com/ethereum/eth-utils/issues/114 is done. Seems like there is already a PR on the issue @pipermerriam @carver

**Comment by pipermerriam** [comment]
@glaksmono just released and published `eth-utils==1.1.1` which contains the new `ValidationError`.  Go for it :+1:
