### ISSUE TITLE
DEBUG logs are dominated by "No idle peers have any of the trie nodes we want"

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1133]
### What is wrong?

Currently, the debug logs are dominated by this logging statement during state sync.

https://github.com/ethereum/py-evm/blob/2f8f89a6abfec1757ab2090c98e4c1df03f2b3f1/p2p/state.py#L219-L221

### How can it be fixed

We either need to move that to `TRACE` level, increase the sleep duration (probably bad for performance), or ideally, find a clean way to throttle that message so that it only shows up at most once every 1-2 seconts, or something else I haven't thought of.

**Comment by dylanjw** [comment]
Something like this leaky bucket algorithm in python:

https://stackoverflow.com/questions/45440900/throttling-async-functions-in-python-asyncio
