### ISSUE TITLE
Write simple service for the `p2p` module which maps the p2p network

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1144]
### What is this?

Just dumping an idea here.

### The Idea

Tool to do some sort of persistent *mapping* of the p2p network and ideally expose that data in a queryable format.

**Comment by carver** [comment]
Is this the idea to map the tree of all running services and their child services?

**Comment by pipermerriam** [comment]
No, this was more focused on exposing data about the nodes on the Kademlia network

- what is the population of light nodes vs full nodes vs light server nodes.
- what other types of protocols are running on the network, how many nodes do they have.

**Comment by pipermerriam** [comment]
archiving
