### ISSUE TITLE
Significant performance degradation during testing compared to pyethereum

### ISSUE THREAD

**Issue by paymog** [ethereum/py-evm#1213]
* py-evm Version: 0.2.0a26
* OS: osx
* Python Version (python --version): 3.6.5
* Environment (output of `pip freeze`):
```
aiohttp==2.3.10
amqp==2.3.2
aniso8601==3.0.2
appnope==0.1.0
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==3.0.0
attrdict==2.0.0
backcall==0.1.0
billiard==3.5.0.4
bitcoin==1.1.42
celery==4.2.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coincurve==7.1.0
coverage==4.5.1
cryptography==2.3.1
cytoolz==0.9.0.1
decorator==4.3.0
dj-database-url==0.5.0
Django==2.0.6
django-celery-beat==1.1.1
django-celery-results==1.0.1
django-cors-headers==2.3.0
eth-abi==1.1.1
eth-account==0.2.3
eth-bloom==1.0.0
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b27
eth-utils==1.0.3
Flask==1.0.2
Flask-GraphQL==1.4.1
graphene==2.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
hexbytes==0.1.0
idna==2.7
idna-ssl==1.1.0
ipython==6.5.0
ipython-genutils==0.2.0
iso8601==0.1.12
itsdangerous==0.24
jedi==0.12.1
Jinja2==2.10
kombu==4.2.1
lru-dict==1.1.6
lxml==4.2.4
MarkupSafe==1.0
multidict==4.3.1
netdisco==2.0.0
netifaces==0.10.7
parsimonious==0.8.0
parso==0.3.1
pbkdf2==1.3
pexpect==4.6.0
pickleshare==0.7.4
plyvel==1.0.4
promise==2.1
prompt-toolkit==1.0.15
psycopg2==2.7.5
psycopg2-binary==2.7.5
ptyprocess==0.6.0
py-ecc==1.4.3
py-evm==0.2.0a26
py-solc==3.1.0
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
PyGithub==1.40
Pygments==2.2.0
PyJWT==1.6.4
pysha3==1.0.2
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.12
redis==2.10.6
repoze.lru==0.7
requests==2.19.1
rlp==1.0.2
Rx==1.6.1
scrypt==0.8.6
secp256k1==0.13.2
semantic-version==2.6.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
SQLAlchemy==1.2.9
toolz==0.9.0
traitlets==4.3.2
trie==1.3.8
typing==3.6.4
uPnPClient==0.0.8
urllib3==1.23
vine==1.1.4
wcwidth==0.1.7
web3==4.3.0
websockets==4.0.1
Werkzeug==0.14.1
yarl==1.2.6
zeroconf==0.20.0
```

### What is wrong?

I'm moving my tests over from `pyethereum` to `py-evm` and I'm seeing a significant performance degradation. On `pyethreum` my test suite would take ~23 seconds. With `py-evm` it takes ~75 seconds. I've profiled my tests and the profile can be found at https://www.filehosting.org/file/details/753367/mycro.pstat.

**Comment by pipermerriam** [comment]
This is about inline with the speed I'd expect.  Py-EVM was written first for readability and easy to understand code/architecture.  We're only now getting to the phase where we're starting to focus on performance.  

Can you potentially share your test suite?  FYI, gists are really good places to dump files like your pstats file.  Depending on your test setup, you should be able to get some performance by using something like `pytest-xdist` to spread the test runs across multiple cores.

I'm closing as this isn't a bug, but please feel free to continue the coversation here.  We can re-open if a specific bottleneck is identified.

**Comment by paymog** [comment]
Ah, understood. Hopefully Py-EVM is eventually faster than pyethereum. 

Unfortunately I don't think I can share the test suite just yet but once I open-source the code I'm happy to provide a link.

I would definitely see a performance improvement if I ran my tests across multiple cores but that's not a priority just yet. Looks like I'd have to move from `unittest` to `pytest` first.

**Comment by pipermerriam** [comment]
@paymog it's up to you.  I'd be happy to look over your test suite if you want to give me access.  Contact me out-of-band (gitter/email) if you want to try that.

FYI, `pytest` can run `unittest` based tests so you might just try switching test harnesses (btw, pytest is awesome and you should absolutely switch because it is soooooooo much better)
