### ISSUE TITLE
Subscribers to peer messages shouldn't have to wait for a timeout when the peer disconnects

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1215]
### What is wrong?

When a peer disconnects, right now, subscribers to messages wait for a timeout before they realize that the peer is gone. This slows down syncing and other things (and in pathological cases with no timeout, can pause forever).

### How can it be fixed

~Maybe cause all subscribers to the peer to receive a TimeoutError immediately on peer disconnect.~

Implement `deregister_peer` in `ResponseCandidateStream` and immediately `raise TimeoutError` on any pending requests.

**Comment by gsalgado** [comment]
I think we should raise `PeerConnectionLost` instead of `TimeoutError`, like `Peer.read()` does
