### ISSUE TITLE
Implement auto-discovery of plugins

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1230]
### What is wrong?

We currently hard list plugins. It would be nice to auto discover plugins. The end game should be that plugins can be just installed through pip and probably a config file manages them (enable/disable etc).

Config file doesn't need to be part of step one.

### How can it be fixed

https://github.com/ethereum/py-evm/pull/996#discussion_r201421200

I might tackle this at some point but at the same time I think it's a great issue for anyone else interested. I'm happy to provide support.

**Comment by parthpankajtiwary** [comment]
Hi @cburgdorf,

I am interested in tackling this problem, however, I will need your guidance on how I can go about doing this. I read #996 comment and both the resources mentioned in the comment, I do understand what needs to be done but I don't understand where exactly :)

**Comment by cburgdorf** [comment]
Hey @parthpankajtiwary,

great to have you looking into this. Have a look at this place.

https://github.com/ethereum/py-evm/blob/fd5c5d4b70a670c56dcc2ae6d1c7f06c3e0f8891/trinity/main.py#L388

It should basically be a replacement for that API call. I *guess* we can even keep it a manual method invocation at this code place. It should just be something like `plugin_manager.discover_plugins()` instead of passing a fixed list of plugins.

Does that give you the right pointer to explore further?

**Comment by parthpankajtiwary** [comment]
Hi @cburgdorf,

Thank you so much for reaching out! :)

Is it okay if I can finally update you on this issue by Sunday? Just a couple of things got along in the way this week. I will give you a final update on Sunday, either with a pull request or with the issues I am facing. I hope this is not too late, please do let me know if it needs to be done earlier and I will try my best to conclude on this sooner, if possible.

**Comment by cburgdorf** [comment]
@parthpankajtiwary  sounds great. Very happy to have you looking into this!

**Comment by ankitchiplunkar** [comment]
If this issue is not being looked into I can give it a try.
