### ISSUE TITLE
Trinity crash

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1234]
### What is wrong?

Trinity crashed, logs are unclear as to why it shutdown.

https://gist.githubusercontent.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/a272bab381ed7b2c8dc68573cc3ac53058ca4c8b/trinity-strange-crash.log

### How can it be fixed

Still need to try and diagnose...

**Comment by carver** [comment]
I don't have the answer, but this seems like the critical bit:

```
   DEBUG  08-31 17:48:55        peer  Malformed message from peer ETHPeer <Node(0xcd7c@167.114.230.91)>: CMD:BlockHeaders Error: MalformedMessage('Malformed %s message: %r',)
   DEBUG  08-31 17:48:55        peer  Disconnecting from remote peer; reason: bad_protocol
   DEBUG  08-31 17:48:55     service  Cancelling ETHPeer <Node(0xcd7c@167.114.230.91)>
   DEBUG  08-31 17:48:55     service  <ResponseCandidateStream(ETHPeer <Node(0xcd7c@167.114.230.91)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)> finished: Cancellation requested by ETHPeer:PeerPool:Server:MainnetFullNode token
```

That first debug log happens right before re-raising the exception. So I guess the exception is somehow bubbling all the way up to somewhere it shouldn't, and causing a shutdown. If we find where that catch-all exception is, we should definitely log at the `exception` level to get the full stack trace.

**Comment by carver** [comment]
BTW, I see the message is not formatted correctly, I'll fix that in the next PR I'm working on.

**Comment by gsalgado** [comment]
This caught my attention
```
   DEBUG  08-31 17:48:55     service  Cancelling ETHPeer <Node(0xcd7c@167.114.230.91)>
   DEBUG  08-31 17:48:55     service  <ResponseCandidateStream(ETHPeer <Node(0xcd7c@167.114.230.91)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)> finished: Cancellation requested by ETHPeer:PeerPool:Server:MainnetFullNode token
    INFO  08-31 17:48:55   discovery  stopping discovery
   DEBUG  08-31 17:48:55     service  ETHPeer <Node(0x473b@167.99.45.137)> finished: Cancellation requested by Server:MainnetFullNode token
```

It's curious that the `Server` token gets triggered immediately after that peer's `.cancel()` method is called (which calls `peer.cancel_token.trigger()`). It suggests a bug in the cancelling of chained tokens, or maybe something is keeping a reference to the server's cancel_token instead of chaining it to create their own

**Comment by gsalgado** [comment]
@carver These two line indicate the exception has been caught in Peer._run(), which then calls `.disconnect()` and `.cancel()`

>    DEBUG  08-31 17:48:55        peer  Malformed message from peer ETHPeer <Node(0xcd7c@167.114.230.91)>: CMD:BlockHeaders Error: MalformedMessage('Malformed %s message: %r',)
   DEBUG  08-31 17:48:55        peer  Disconnecting from remote peer; reason: bad_protocol

**Comment by pipermerriam** [comment]
More logs: https://gist.githubusercontent.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/1a9019afccd98647c32bbe3f31e4599e69f8a6d3/trinity-discovery-crash.log

This validates @gsalgado thoughts here https://github.com/ethereum/py-evm/issues/1234#issuecomment-418193499

Specifically this section which indicates that the `ResponseCandidateStream` is part of the cancellation chain that causes the DiscoveryService to halt.

```
 83    DEBUG  09-03 15:45:26     service  <ResponseCandidateStream(ETHPeer <Node(0x97b6@185.64.116.14)>, <class 'trinity.protocol.eth.commands
    .BlockHeaders'>)> finished: Cancellation requested by ETHPeer:PeerPool:Server:MainnetFullNode token
 84    DEBUG  09-03 15:45:26     service  <p2p.discovery.DiscoveryService object at 0x7f1a719e6da0> finished: Cancellation requested by Respon
    seCandidateStream:ETHPeer:PeerPool:Server:MainnetFullNode token
 85     INFO  09-03 15:45:26   discovery  stopping discovery
```

The chain of tokens that caused the discover cancellation has the

**Comment by pipermerriam** [comment]
Also, this might indicate that we need to do something to fix the cancel token chaining API because honestly, I've had trouble sometimes figuring out what the right order should be.  Maybe we need something like  `token.create_child_token()` rather than actually combining two tokens and thus, having to figure out the right ordering.

**Comment by pipermerriam** [comment]
Not yet confirmed but this *may* have been a local error on my machine.  I had a version of `asyncio-cancel-token` installed from source locally which I'd been mucking around with a few weeks ago.  Running experiment now to see if it is fixed.

**Comment by gsalgado** [comment]
The log lines from https://github.com/ethereum/py-evm/issues/1234#issuecomment-418220374 indicate that the token was correctly chained by `ResponseCandidateStream`, but when it was triggered it ended up cancelling one of the parent tokens in the chain, which doesn't seem to happen (https://github.com/ethereum/asyncio-cancel-token/pull/9), so it's very possible this was all caused by your locally modified version of asyncio-cancel-token

**Comment by carver** [comment]
> One thing that is not right is for ResponseCandidateStreamExchangeManager to keep a direct reference to the cancel token passed onto it (https://github.com/ethereum/py-evm/blob/master/trinity/protocol/common/managers.py#L200), as that means it will always cancel its parent when terminating but that is a decision that belongs to the parent. 

`ExchangeManager` isn't a service, it keeps the cancel token so that it can hand the token to the `ResponseCandidateStream` on init. It doesn't otherwise use `_cancel_token`.

**Comment by pipermerriam** [comment]
Closing until I can reproduce with a fresh virtual environment.

**Comment by pipermerriam** [comment]
I am pretty sure that I'm now seeing this in the `v0.1.0-alpha.15` release running on one of our VPS instances.  Should know for sure pretty soon.

**Comment by pipermerriam** [comment]
I've confirmed this bug is not isolated to my machine.  Encountered during light sync in a VPS node, I expect I'll see it in full sync too.

**Comment by pipermerriam** [comment]
More info:

Looks like `DiscoveryProtocol` retains a direct link to the `Server` cancel token

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.32/trinity/server.py#L150-L151

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.32/p2p/discovery.py#L145

Which is then triggered when the `DiscoveryService` cleans up, calling `proto.stop()` which triggers the token

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.32/p2p/discovery.py#L819-L820

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.32/p2p/discovery.py#L397-L399

**Comment by gsalgado** [comment]
I can reproduce it when running in light mode.

As for the fact that DiscoveryProtocol retains a direct link to the Server cancel token, it is indeed something that ought to be fixed, but that token is only triggered when `DiscoveryProtocol.stop()` is called, and we still don't know why `DiscoveryService` is terminating

**Comment by pipermerriam** [comment]
check out my branch `piper/weird-crash-thing` for some additional logging output that I've injected to try and diagnose this.  I still haven't been able to see the crash with that logging enabled.

**Comment by pipermerriam** [comment]
For anyone trying to reproduce it does appear that running in light mode is more likely to trigger this.

**Comment by pipermerriam** [comment]
GOT IT!!!!!

```
   DEBUG  09-04 18:00:00     service  STACKTRACE:
Traceback (most recent call last):
  File "/home/piper/projects/py-evm/p2p/service.py", line 126, in run
    await self._run()
  File "/home/piper/projects/py-evm/p2p/discovery.py", line 780, in _run
    await self.maybe_connect_to_more_peers()
  File "/home/piper/projects/py-evm/p2p/discovery.py", line 800, in maybe_connect_to_more_peers
    self.proto.get_nodes_to_connect(self.peer_pool.max_peers))
  File "/home/piper/projects/py-evm/p2p/peer.py", line 838, in connect_to_nodes
    await self.start_peer(peer)
  File "/home/piper/projects/py-evm/p2p/peer.py", line 742, in start_peer
    await self.ensure_same_side_on_dao_fork(peer)
  File "/home/piper/projects/py-evm/p2p/peer.py", line 864, in ensure_same_side_on_dao_fork
    timeout=CHAIN_SPLIT_CHECK_TIMEOUT,
  File "/home/piper/projects/py-evm/trinity/protocol/les/exchanges.py", line 62, in __call__
    timeout,
  File "/home/piper/projects/py-evm/trinity/protocol/common/exchanges.py", line 83, in get_result
    timeout,
  File "/home/piper/projects/py-evm/trinity/protocol/common/managers.py", line 233, in get_result
    async for payload in stream.payload_candidates(request, tracker, timeout=timeout):
  File "/home/piper/projects/py-evm/trinity/protocol/common/managers.py", line 104, in payload_candidates
    yield await self._get_payload(timeout_remaining)
  File "/home/piper/projects/py-evm/trinity/protocol/common/managers.py", line 151, in _get_payload
    payload = await self.wait(future, timeout=timeout)
  File "/home/piper/projects/py-evm/p2p/cancellable.py", line 19, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/py-evm/p2p/cancellable.py", line 41, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by ResponseCandidateStream:LESPeer:PeerPool:LightServer:MainnetLightNode token
```

**Comment by pipermerriam** [comment]
`OperationCancelled` escaping during the Dao fork check which the discovery service interpreted as an upstream cancellation.

I think we need some sort of *guard* that ensures that we only silence that exception if the triggering token is in the inheritance chain of the service's local cancel token.

**Comment by carver** [comment]
Seems very reasonable for `OperationCancelled` to contain a reference to the token that triggered it, and then:

```py
except OperationCancelled as exc:
  if self.cancel_token.is_child_of(exc.token):
    pass
  else:
    raise
```

**Comment by carver** [comment]
Also, I guess even swallowed `OperationCancelled` exceptions could log at the `trace` level, which I'm assuming you had turned on.

**Comment by pipermerriam** [comment]
We should be sure to do a thorough audit of everywhere that we catch `OperationCancelled` while fixing this.

**Comment by pipermerriam** [comment]
@gsalgado good thoughts and I believe I agree with that approach.  Unfortunately, it may be closer to the end of this week before I can really spend much time on this.  I'm closing #1255.  If anyone else wants to take a stab at this :+1:

**Comment by pipermerriam** [comment]
I'm thinking that we should do something like this:

```python
class Peer:
    ready = asynio.Event()  # but not as a class variabe :)
    def _run(self):
        # do dao check
        self.ensure_same_side_of_dao()
        self.ready.set()

class PeerPool:
    def stat_peer(self, peer):
        self.run_child_service(peer)
        await peer.ready.wait()
        # do the rest of adding peer to pool
        # also: handle failure case however that works.
```

This *should* properly start the peer, do the dao check, and keep the `peer` away from the subscriber API until the dao check has been fully completed.

**Comment by gsalgado** [comment]
I'll have a go at this, but I'm not sure what you suggest above is the best alternative, for a few reasons:

1. It feels wrong to run the `Peer` service and after that wait for it to be _ready_, but maybe that's just a naming issue
2. We're waiting on a `Peer` attribute, which happens to be just an `asyncio.Event` now, but if it's changed into something that can raise `OperationCancelled`, we'll have the same problem as we have now
3. It doesn't consider the fact that the messages received during the DAO fork check need to be collected, but maybe you meant to keep the `with peer.collect_sub_proto_messages() as buffer:` there?

Anyway, I'll have to think about this a bit more, just thought it was worth mentioning those points

**Comment by carver** [comment]
>  Ideally we should never have to do something like `await other_service.method()`

It makes sense how that would solve the problem.

Off-hand, it seems like a pretty tight constraint, and probably a surprising one for most people. It sounds like a beast of a task to go through the whole code base and check if we're doing that anywhere else.

If you squint, I think the constraint implies that a `BaseService` subclass should never have any async functions that are public (ie~ not prefixed with `_`). Maybe that's slightly easier to check for.

**Comment by pipermerriam** [comment]
@gsalgado my suggestion was merely dumping my thoughts.  Take this whatever direction you think is right :+1:

**Comment by gsalgado** [comment]
> If you squint, I think the constraint implies that a BaseService subclass should never have any async functions that are public (ie~ not prefixed with _). Maybe that's slightly easier to check for.

Indeed it would, but it just occurred to me that the `await other_service.method()` pattern is actually not a problem in itself if it runs in the background (e.g. via `BaseService.run_task()` & co). It's only code that runs inside a `BaseService._run()` that has to avoid that pattern.

**Comment by pipermerriam** [comment]
Alright, new cleaned up version of my fix: https://github.com/ethereum/py-evm/pull/1265
