### ISSUE TITLE
Cleanup trinity log level setting to include defaults and make them overridable

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1243]
From: https://github.com/ethereum/py-evm/issues/806#issuecomment-417987842

### What is wrong?

We have some defaults that are used to quiet down some noisy loggers:

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.31/trinity/utils/logging.py#L111-L114

Were the use to supply overrides to these via the command line they would not be respected

### How can it be fixed

This lines should be relocated such that they are merged with the user supplied logging levels before being passed into `setup_log_levels`.

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.31/trinity/main.py#L111-L112

**Comment by glaksmono** [comment]
@pipermerriam just want to align. Do we want [1] to keep those noisy logs at `INFO` level (i.e as current, less noisy) then overrides it when log level is defined from the command line?

OR

[2] We want to take out the `INFO` level config (i.e will become more noisy), then override when log level defined in command line?
