### ISSUE TITLE
Add more tests for rewards

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1315]
### What is wrong?

We recently added unit tests (additional to the existing state tests) that cover the rewards that are paid to the miners.

We should expand the following cases ([citing from](https://github.com/ethereum/py-evm/pull/1303#pullrequestreview-157854461))

>- calculating uncle/nephew reward when the uncle is on a different VM (like: uncle in frontier at 0, nephew in constantinople at 1)
>- uncles that are 2 -> 8 layers back
>- validating that uncles > 8 back are invalid

>(I'm saying the last two without having reviewed the uncles section of the YP recently, so probably have some detail wrong)

### How can it be fixed

Add test [here](https://github.com/ethereum/py-evm/blob/0cc5d59c92c4c8947d67f9462c00c17d39089cc0/tests/core/vm/test_rewards.py)

**Comment by pipermerriam** [comment]
Tests should be *reasonably* easy to write using the new chain builder tools.

**Comment by Bhargavasomu** [comment]
I'm taking this up.

**Comment by Bhargavasomu** [comment]
This can be closed with #1685
