### ISSUE TITLE
`ethstats` plug-in fails with HTTP error 504 if not given full URI

### ISSUE THREAD

**Issue by veox** [ethereum/py-evm#1337]
* `trinity` version: `trinity-v0.1.0-alpha.16-15-g3eb6dc5d` (current master: commit 3eb6dc5d7e755ec96fc65df1833b9c3628990ab2)
* OS: Arch Linux
* Python Version (python --version): 3.7.0
* Environment (output of `pip freeze`): MISSING

### What is wrong?

PR #1336 squash-merged work from PR #1216, implementing the `ethstats` plug-in.

I've tried it with an actual "secret token" I have for `wss://ropsten-stats.parity.io/`, and there's always a `504` when trying to connect via WebSocket:

``` python
   ERROR  09-29 23:36:59       EthstatsService  Unexpected error in <trinity.plugins.builtin.ethstats.ethstats_service.EthstatsService object at 0x7f4ac6dafa58>, exiting
Traceback (most recent call last):                                                                     
  File "/home/veox/src/py-evm/p2p/service.py", line 103, in run                                        
    await self._run()                                                                                  
  File "/home/veox/src/py-evm/trinity/plugins/builtin/ethstats/ethstats_service.py", line 68, in _run  
    async with websockets.connect(self.server_url) as websocket:                                       
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self                                                                                  
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/py35/client.py", line 19, in __await_impl__
    extra_headers=protocol.extra_headers,                                                              
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/client.py", line 263, in handshake
    raise InvalidStatusCode(status_code)                                                               
websockets.exceptions.InvalidStatusCode: Status code not 101: 504                                      
Traceback (most recent call last):                                                                     
  File "/home/veox/src/py-evm/p2p/service.py", line 103, in run                                        
    await self._run()                                                                                  
  File "/home/veox/src/py-evm/trinity/plugins/builtin/ethstats/ethstats_service.py", line 68, in _run  
    async with websockets.connect(self.server_url) as websocket:                                       
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self                                                                                  
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/py35/client.py", line 19, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/client.py", line 263, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 504
```

EDIT: As a sanity check, I've tried with my previous setup of `jsonrpcproxy`+`eth-net-intelligence-api`, and it still works. So the URL/secret are correct.

### How can it be fixed

See [comment](https://github.com/ethereum/py-evm/issues/1337#issuecomment-425684580).

Either:

* add `api` to the URL in the plug-in ourselves; or
* instruct the user (in docs?) to specify the full endpoint path ~~and rename "URL" to "URI"~~.

**Comment by veox** [comment]
This may be due to the fact that I'm actually connection to WSS. `websockets`' docs have [this to say on SSL/TLS](https://websockets.readthedocs.io/en/stable/intro.html#secure-example).

**Comment by voith** [comment]
@veox I'm not really sure about the error but just want to point out that the `websockets` version pinned in setup.py   is  `5.0.1` and that version is not compatible with `python3.7`. python 3.7 support in `websockets` was added in `v6.0.0`

**Comment by veox** [comment]
@voith Yes, I'm trying now with `websockets==6.0` and `web3==4.6.0`, and still getting the same.

**Comment by evgeniuz** [comment]
I still think this may be caused by the fact that this endpoint uses SSL. I was testing against local `eth-netstats` server (and that one obviously doesn't use SSL). Will try to look more closely into this.

**Comment by evgeniuz** [comment]
Tried to test this with SSL enabled, but it works for me. BTW, if you pass `wss://ropsten-stats.parity.io/` as server URL, can you please try passing `wss://ropsten-stats.parity.io/api`, as that is endpoint clients should connect to.

**Comment by veox** [comment]
Ah! You are correct, the missing `api` endpoint is what was missing. :)

It now works as expected (when with no peers). Will try sync in a moment.

For ref (and possible future doc), I'm testing it as:

``` sh
PYTHONWARNINGS='ignore' trinity --network-id=3 --sync-mode=light --ethstats --ethstats-server-url="wss://ropsten-stats.parity.io/api" --ethstats-server-secret="SECRET" --ethstats-node-id="veox-trinity-dev" --ethstats-node-contact="veox" --max-peers=0
```

**Comment by veox** [comment]
I've added suggestions to "how it can be fixed" section in [issue description](https://github.com/ethereum/py-evm/issues/1337#issue-365165083).

**Comment by evgeniuz** [comment]
I think second approach is better, as it is more explicit. Will add note about `/api` to `--help` output and rename parameters to URI.

**Comment by pipermerriam** [comment]
Also, I think that we can auto select a default for the URI if the node is running against ropsten/mainnet or really any network ID for which we know the right *default* URI.
