### ISSUE TITLE
Add beacon chain helper functions

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1339]
### What is wrong?
Part of #930 

- The [helper functions in beacon_chain](https://github.com/ethereum/beacon_chain/blob/master/beacon_chain/state/helpers.py) are all pure functions with a `config: Dict[string, Any]` parameter. 
- Some helpers functions are like ~90% similar to [the spec](https://notes.ethereum.org/s/Syj3QZSxm#Helper-functions) as a reference implementation. But to fit Py-EVM paradigm, we may have to refactor a lot.

### How can it be fixed
It may take multiple steps:
1. Move all pure functions to `eth/beacon/helpers.py` - I have a commit here: https://github.com/hwwhww/py-evm/commit/5724a7a30ce56979382c7ea07e29e08fcaf21254 
2. Introduce `eth.beacon.db.chain.BeaconChainDB`
3. Introduce `eth.beacon.state_machines.base.BaseStateMachine(Configurable)`
4. Introduce `eth.beacon.chains.chain.BeaconChain`
4. Tear down helpers: move some of them to `eth.beacon.state_machine.base.BaseStateMachine` or being static functions / properties in `eth.beacon.types.*` classes.

cc @djrtwo @pipermerriam

**Comment by pipermerriam** [comment]
- The `config` object can probably be updated to be a `typing.NamedTuple` for stronger type safety.
- Modifying the helper functions to be non mutative looks like something that will go relatively quickly.
- Writing tests for all of these is probably the largest task (take care to not waste time writing exhaustive tests on things that are likely to change).

**Comment by pipermerriam** [comment]
Also, ideally, rather than passing a `config` object around through these various helper functions, it would probably be better to just explicitly pass the specific configuration values as individual parameters.

**Comment by pipermerriam** [comment]
On *second* thought, I'm curious if we can get away with the same pattern that the existing code uses, placing these in a `constants` file and importing them as needed.  For parameters that end up changing for various forks, we can place them in `eth.beacon.forks.fork_name.constants` (as danny suggested)

**Comment by hwwhww** [comment]
Yes, that makes sense. We will have `Configurable` `StateMachine` to handle these chain configurations.

**Comment by djrtwo** [comment]
Yeah, I agree the import is the way to go on these

**Comment by hwwhww** [comment]
closed via #1341 and #1381
