### ISSUE TITLE
changes to CREATE2

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1346]
### What is wrong?

`CREATE2` is changing:

- problem description: https://github.com/ethereum/EIPs/pull/1014#issuecomment-413990682
- proposed solution: https://github.com/ethereum/EIPs/pull/1014#issuecomment-414160604
- change to gas cost proposed by V: https://github.com/ethereum/EIPs/pull/1375#issuecomment-425641771

### How can it be fixed

Wait to see where things land with the spec and update our implementation.

**Comment by Bhargavasomu** [comment]
I would like to work on this issue. Could you please guide me regarding the codebase as to where to start?

**Comment by pipermerriam** [comment]
Correct me if I'm wrong but this issue is going to require some depth of knowledge with this library which I don't believe you have.  Probably best to stick to things labeled as "Good first issue" until you are more familiar with the codebase.
