### ISSUE TITLE
Have at least some benchmarks run against the actual DB rather than the MemoryDB

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1359]
### What is wrong?

Currently, all our benchmarks run against the `MemoryDB`. Unfortunately, that means we are missing out to measure pretty much all optimizations that are about reducing the number of hits to read/write to the database.

In other words, if some optimizations save e.g. two hits to the DB we will barely see any difference in the benchmarks as data updates in-memory are just super fast compared to the actual cost when we hit the disk (which will be the case with something like `LevelDB`.

### How can it be fixed

Run at least *some* benchmarks against `LevelDB`. I say *some* because the one argument against this, is that it will increase our CI times.

**Comment by pipermerriam** [comment]
two things:

1. we can help the current state of affairs a little by promoting our benchmarking CI runs to run earlier in the process.  That's more of a scheduling optimization but it will help.
2. in CI, we can reduce the granularity that our benchmarks run, only running the most *important* ones and then maybe a *random* subset of the other ones (ideally deterministically random so that any failures are reproducable within a branch).

**Comment by veox** [comment]
A few issues with running benchmarks in remote-hosted CI:

* you never know how "busy" the VM host is serving other VM guests - there's need to measure the "raw" device performance, too, so the benchmark is normalised to something comparable between runs;
* you never know if the remote CI is completely memory-hosted, where the "disk drive" is a "RAM disk";
* (there was something else, but I forgot :disappointed:).

**Comment by pipermerriam** [comment]
It's less about the actual benchmark performance and more about making sure the benchmarks work.

**Comment by Bhargavasomu** [comment]
What should I use as the `path` for the `LevelDB initialization`? Is it `/tmp/mainnet.db`?

**Comment by pipermerriam** [comment]
I'd recommend using the [tmpdir](https://docs.pytest.org/en/latest/tmpdir.html) fixture that comes with pytest or the [`tempfile`](https://docs.python.org/3.5/library/tempfile.html) standard library module to generate a new temporary directory for each run.  If you use the standard library `tempfile` module, make sure that the directory is removed after the test.

**Comment by Bhargavasomu** [comment]
![screenshot from 2018-10-14 10-28-43](https://user-images.githubusercontent.com/15922456/46912760-1c36c780-cf9c-11e8-8758-2e6a6440c6f2.png)
How to fix this issue in Circle CI?

**Comment by pipermerriam** [comment]
I've restarted those tests (looks like you have a linting error though)

**Comment by pipermerriam** [comment]
@carver This has happened twice over the weekend, I opened a github support issue as it doesn't seam reasonable for circle CI to be rate limited for this (and I suspect they should be able to increase their cap).

**Comment by cburgdorf** [comment]
Landed with #1393
