### ISSUE TITLE
Use chain builder tools to cleanup benchmarks

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1360]
### What is wrong?

The current benchmarks use an [impromptu API](https://github.com/ethereum/py-evm/blob/master/scripts/benchmark/utils/chain_plumbing.py) to create the chains that are used for benchmarking.

### How can it be fixed

We now have some more solid [builder tools](https://py-evm.readthedocs.io/en/latest/api/eth/tools/api.tools.builders.html) to create chains. These tools allow the creation of chains using a declarative, fluent API which we do use already in several tests.

https://github.com/ethereum/py-evm/blob/3061a48d112b2ae7d94adec89000372dd4bcac2c/tests/core/chain-object/test_chain_reorganization.py#L9-L17

We should be able to use the same tools to either use them in each benchmark directly and get rid of `chain_plumbing.py` altogether or, if that still turns out too boilerplatey, at least cleanup `chain_plumbing.py` to use the builder tools underneath.

**Comment by Bhargavasomu** [comment]
@cburgdorf I have modified the `chain_plumbing` module by using `builder tools`. Please take a look at the PR #1364
[](https://github.com/ethereum/py-evm/pull/1364)

**Comment by Bhargavasomu** [comment]
One more thing to notice is that none of the functions of `eth/tools/builder/chain` in the `builder tools` have been typed. This is causing a pylint error. Should I type the functions?

**Comment by cburgdorf** [comment]
Ok, looks like we should tackle #1366 first before we can move this forward

**Comment by cburgdorf** [comment]
@Bhargavasomu The typing issue could be resolved by importing the functions individually.

Closing as this landed with https://github.com/ethereum/py-evm/pull/1364
