### ISSUE TITLE
Remove curry API from chain builder tools

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1365]
### What is wrong?

It looks like `mypy` doesn't get along well with curried functions:

https://github.com/ethereum/py-evm/pull/1364

### How can it be fixed

Update the chain builder to not use curry? (or something better)

**Comment by Bhargavasomu** [comment]
@pipermerriam I think we can use `partial functions` of the functools library as a replacement for `curry`. But would that be ok to integrate with mypy?

**Comment by pipermerriam** [comment]
`curry` is basically a lazy `functools.partial`.  Doesn't really matter what the mechanism is as long as it maintains type safety.

**Comment by pipermerriam** [comment]
Oh,... duh, there are no type hints in the builder module.
