### ISSUE TITLE
`ethstats` plugin stuck trying to get peer count

### ISSUE THREAD

**Issue by veox** [ethereum/py-evm#1379]
* `py-evm`: `trinity-v0.1.0-alpha.16-71-gca9f90a6` (current `master` at commit ca9f90a6c08699c2aa8989b233a23cd533f0aa02)
* OS: Arch Linux
* Python: CPython 3.7.0
* Environment (output of `pip freeze`): NAH

### What is wrong?

After PR #1343 (blamed by `git bisect`), the `ethstats` plug-in stopped working again (in both "light" mode and "full" sync mode). For ref, run as:

```
PYTHONWARNINGS='ignore' trinity --network-id=3 --sync-mode=light --log-level=debug \
    --ethstats --ethstats-server-url="wss://ropsten-stats.parity.io/api" \
    --ethstats-server-secret="SECRET" \
    --ethstats-node-id="veox-trinity-dev-lightclient-debug" \
    --ethstats-node-contact="veox" \
    --max-peers=0
```

A traceback (don't read in: it's misleading):

``` python
   ERROR  10-09 17:53:26        EthstatsClient  Unexpected error in <trinity.plugins.builtin.ethstats.ethstats_client.EthstatsClient object at 0x7fcdd4ee1438>, exiting
Traceback (most recent call last):
  File "/home/veox/src/py-evm/p2p/service.py", line 103, in run
    await self._run()
  File "/home/veox/src/py-evm/trinity/plugins/builtin/ethstats/ethstats_client.py", line 52, in _run
    self.recv_handler(),
  File "/home/veox/src/py-evm/p2p/cancellable.py", line 41, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/veox/src/py-evm/trinity/plugins/builtin/ethstats/ethstats_client.py", line 59, in recv_handler
    json_string: str = await self.websocket.recv()
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/protocol.py", line 352, in recv
    yield from self.ensure_open()
  File "/home/veox/src/py-evm/.virtualenv/py-evm/lib/python3.7/site-packages/websockets/protocol.py", line 514, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
```

The "blocker", at least within `ethstats`, are these lines:

https://github.com/ethereum/py-evm/blob/ca9f90a6c08699c2aa8989b233a23cd533f0aa02/trinity/plugins/builtin/ethstats/ethstats_service.py#L137-L139

A response for `PeerCountRequest` never arrives from the event bus. The plugin keeps waiting, never submitting any stats; eventually the remote server closes the `websocket`. That makes it look like the issue is network-related.

Commenting out this retrieval, and hard-coding the peer count number to be reported as `1337` is sufficient for the node to start behaving "normally": e.g. regularly submit latest chain head data to the remote, etc..

### How can it be fixed

The actual "culprit" is unknown to me. :(

Starting a `trinity --network-id=3 attach` session and requesting `web3.net.peerCount` works fine, so this might be related to plugin/service contexts. (The `attach` and `ethstats` plugins are quite different.)

Tried looking at whether `self.context.event_bus._running` for the plugin is `True`. In all cases, it already was by the time it reached that "hanging" point. So probably not a case of an event bus that's not yet running.

PR #1343 _did_ make some changes to how peer count requests are handled. I don't understand it exactly, so can't say for sure that it's relevant. Probably best to start there.

**Comment by pipermerriam** [comment]
Probably orthogonal to this but it's probably going to be necessary to implement a mechanism that will lazily re-establish the websocket connection in the event of a failure (and ideally a backstop that will abort reconnection if too many failures happen in too brief a time).
