### ISSUE TITLE
PyPy investigation notes

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#138]
I was curious how fast py-evm would run in pypy, and it sent me down a rabbit hole. This issue is just a way to note what I learned along the way.

- pypy won't work out of the box because of the dependency on pysha3 (via eth-bloom), which [fails to compile under pypy](https://bitbucket.org/pypy/pypy/issues/2687/pypy3-is-missing-pystrhexh-breaking-pysha3)
- I ran eth-bloom tests as a rough speed proxy with several different configurations:
  - pysha3: 0.5s
  - [pure python implementation](https://github.com/ctz/keccak/blob/master/keccak.py) in cpython: 25s
  - pure python implementation in pypy: 9.5s
  - pure python implementation in cython: 20.5s
  - after a couple of type annotations in cython: 16.5s
  - cython in pypy: crash at runtime with `TypeError: object.__new__(builtin_function_or_method) is not safe, use builtin_function_or_method.__new__()`
- Optimizing sha3 in cython doesn't matter if it doesn't work under pypy (because we might as well keep the c extension version). Although I do expect that it would be possible to make it work under pypy with some tweaks.
- Punting on pypy and working on a cython trie implementation (which was Piper's first instinct) might be the most fruitful next step

**Comment by carver** [comment]
I believe the old issue blocking pysha3 got fixed, but there is another one: https://github.com/tiran/pysha3/issues/17 ie~ https://bitbucket.org/pypy/pypy/issues/2723/undefined-symbol-pyunicode_new-in-pypy3#comment-None

Anyway, the path @onyb started down seems like the best one for getting pypy live.

**Comment by pipermerriam** [comment]
I'd like to pull `keccak` out of eth-utils into an `eth-keccak` library that allows swapping out the implementation.  That way we don't have to force a specific implementation on anyone, re-use the same flexibility across all of our codebases, and fix at least this one pypy support issue across the board with one implementation.

**Comment by carver** [comment]
@pipermerriam There's an example implementation of it in https://github.com/carver/eth-hash it's red waiting to see if @onyb wants to submit the same change.

**Comment by carver** [comment]
https://github.com/ethereum/eth-hash/ is published, passing tests on pypy. Now working on integrating them into other eth-* libraries.

**Comment by pipermerriam** [comment]
@carver 

Good findings.  I'm good moving all of the fixture tests to be pypy only.

One thing that will alleviate our CI situation a bit will be when the `p2p` and `trinity` code find their way into their own repositories, reducing our ci footprint a bit simply by not having to run the combined three test suites for something that only changes one of them.

**Comment by jsw-qkc** [comment]
@carver 

I'm still unable to get py-evm to play nicely with pypy3. Running:

```
pypy3 -m pip install git+git://github.com/ethereum/py-evm
```

still yields 

```
Modules/_sha3/backport.inc:78:22: fatal error: pystrhex.h: No such file or directory
```

Am I missing something here?

**Comment by carver** [comment]
@jsw-qkc You are correct, pypy3 support degraded (or was maybe never fully supported). I took a look a little while ago at reviving it, but it was more work than I had time for. See this PR for the WIP: https://github.com/ethereum/py-evm/pull/690

**Comment by jsw-qkc** [comment]
@carver 

ah, good to know. on a slightly separate note, is py-evm still considered to be in "alpha" release phase or would you say its in a better state than pyethereum now?

**Comment by carver** [comment]
Both? :)  Feel free to drop by https://gitter.im/ethereum/py-evm since we've gone off-topic.
