### ISSUE TITLE
Add beacon chain / eth2.0 related NewType

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1383]
### What is wrong?
https://github.com/ethereum/py-evm/pull/1373#discussion_r224107745
To make the types more explict!

### How can it be fixed
1. Time unit - `Second` - and also can be used for PoW chain?
2. For beacon chain, some other `NewType` candidates: `Slot`, `ShardID`. And [with the latest spec](https://github.com/ethereum/eth2.0-specs/blob/cbd254a3090771e79ccc8eb8e21c7b32dba93c45/specs/beacon-chain.md#constants): `ValidatorStatus`, `SpecialRecordType`, `ValidatorSetDeltaFlag`.
3. **EDIT:** Move to [ethereum/eth-typing/](https://github.com/ethereum/eth-typing/)

**Comment by hwwhww** [comment]
@cburgdorf is there any known solution to define: (i) the length of an integer (ii) unsigned/signed integer via type hinting?

**Comment by cburgdorf** [comment]
> is there any known solution to define: (i) the length of an integer (ii) unsigned/signed integer via type hinting?

No, `mypy` can not do these things. What it *can* do is to allow you different types for different *intents* and ensure to trace the flow of these to prevent the wrong one ending up at a wrong place.

Consider this:

```python

def create_some_thing_unsigned() -> int:
    ...

def create_some_thing_signed() -> int:
    ...

def consume_something_unsigned(unsigned: int):
    ...
```

clearly we want to prevent the following situation:

```python
x = create_something_signed()
consume_something_unsigned(x)  # runtime crash!
```

Mypy can help you with this if you create a `NewType`.

```python
UnsignedInt = NewType('UnsignedInt', int)

def create_some_thing_unsigned() -> UnsignedInt:
    ...

def create_some_thing_signed() -> int:
    ...

def consume_something_unsigned(unsigned: UnsignedInt):
    ...
```

Now, if you'd try this again, mypy would yell at you because it knows that `x` is not of type `UnsignedInt`.

```python
x = create_something_signed()
consume_something_unsigned(x)  # development time mypy error!
```

**Comment by hwwhww** [comment]
@cburgdorf thanks for the reply!

Re: > Move to ethereum/eth-typing/

What do you think about making the beacon chain new types in `eth/beacon/typing.py` temporarily, and then move to `eth-typing` once we settle down? I want to sort out what are the new types we need.

The types that I think we'd need:
```python
SlotNumber = NewType('SlotNumber', int)  # uint64
ShardNumber = NewType('ShardNumber', int)  # uint64
BLSPubkey = NewType('BLSPubkey', int)  # uint384
BLSSignature = NewType('BLSSignature', Tuple[int, int])  # Tuple[uint384, uint384]
ValidatorIndex = NewType('ValidatorIndex', int)  # uint24
Bitfield = NewType('Bitfield', int)  # uint64
```

The types that I'm not 100% sure:
```python
AmountInEther = NewType('AmountInEther', int)  # uint64
AmountInGwei = NewType('AmountInGwei', int)  # uint64
```

**Comment by cburgdorf** [comment]
>What do you think about making the beacon chain new types in `eth/beacon/typing.py` temporarily, and then move to `eth-typing` once we settle down?

Yes, that would be my preferred approach as well :+1:  

>The types that I'm not 100% sure:

Ensuring that an API that expects `Gwei` isn't called with `Ether` is exactly what NewTypes are for. The canonical example is usually this NASA bug where an API was called with *miles* that expected *kilometers* and caused the rocket to crash. This falls into the same category.

I would just simplify the names to

```
Ether = NewType('Ether', int)  # uint64
Gwei = NewType('Gwei', int)  # uint64
```

**Comment by ChihChengLiang** [comment]
Working on this
