### ISSUE TITLE
Drop python 3.5 support in eth module

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1391]
### What is wrong?

Python 3.6 was released nearly 2 years ago. `trinity` is alpha software, which won't be stable for another good while. Python 3.5 doesn't support some sweet syntax like f-strings, native typing annotations, etc.

### How can it be fixed

Let's drop py3.5 support from the eth module, and require >=3.6.

Objections?

**Comment by pipermerriam** [comment]
I believe we are held up by: Web3.py -> eth-tester -> py-evm `eth` module

**Comment by carver** [comment]
https://github.com/ethereum/py-evm/pull/1390#discussion_r224931867

Good point about web3.

Potentially web3 v4 can freeze py-evm at the current version, and updates to py-evm will only be available in web3 v5. (which I [expect to be py3.6+](https://github.com/ethereum/web3.py/issues/722))

**Comment by pipermerriam** [comment]
Our much ignored mailing list and `/r/ethereum` might be good places to solicit feedback (and prepare people).

**Comment by jacqueswww** [comment]
Good stuff! This is great from a vyper perspective - as vyper also requires 3.6.

**Comment by pacrob** [comment]
dropped in #1785
