### ISSUE TITLE
ImportWarning: can't resolve package from __spec__ or __package__

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1402]
### What is wrong?

When running `trinity`, there are several warnings like this:
```
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

This is one of many different kinds of warnings mentioned in #1370 

The goal is not simply to hide these warnings but to resolve them.

### How can it be fixed

It will take some investigation. You should be able to see stack trace info for the warning by starting trinity with:
```sh
PYTHONWARNINGS=error::ImportWarning trinity
```

Then dig into each offending module to investigate.

[This bug report](https://bugs.launchpad.net/lxml/+bug/1732505) has some ideas about resolving the warnings.

**Comment by pipermerriam** [comment]
Should have been fixed with #1419
