### ISSUE TITLE
ResourceWarning: unclosed resource <TCPTransport

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1403]
### What is wrong?

When running `trinity`, there are several warnings like this:
```
ResourceWarning: unclosed resource <TCPTransport closed=False reading=False 0x2ab9dc8>
```

_You'll probably find more helpful results online with `ResourceWarning: unclosed transport <_SelectorSocketTransport ...`._

_The text in the original quoted warning is produced by `uvloop` which reports the error differently and has less hits on a web search._

This is one of many different kinds of warnings mentioned in #1370 

The goal is not simply to hide these warnings but to resolve them.

### How can it be fixed

It will take some investigation. You should be able to see stack trace info for the warning by starting trinity with:
```sh
PYTHONWARNINGS=error::ResourceWarning trinity
```

It looks like roughly the solution is to do an `await asyncio.sleep(0)` in between closing a transport and letting the variable go out of scope (or explicitly deleting the instance). Or maybe there is a transport that is never being explicitly closed.

**Comment by pipermerriam** [comment]
Had a small burst of *maybe* intuition about this.

We instantiate `Peer` classes with a `reader/writer` pair which is already open.  We **only** close these in the event that the peer service is actually started.  In any case where the `Peer.run()` is never called it appears that the connection will remain open.

I believe this location might be where some of these errors come from.

https://github.com/ethereum/py-evm/blob/1f60fd8576d4959c7d4642f52ac56158658cc9ae/p2p/peer.py#L130-L131

If either of the `do_p2p_handshake` or `do_sub_proto_handshake` fails I think the transport remains unclosed.

@carver this **might** be more supporting evidence that the decoupling of the protocol connection from the peer concept makes sense.

**Comment by pipermerriam** [comment]
A quick experiment wrapping the two lines above in a `try/except` and closing the reader if an error occurs seems to have fully eliminated these errors.
