### ISSUE TITLE
Remove duplicate utility functions from `eth.tools.fixtures.normalization`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1407]
### What is wrong?

from: https://github.com/ethereum/py-evm/pull/1396#pullrequestreview-165796731

There are duplicates of some of the functions in:

- `eth.tools._utils.normalization`
- `eth.tools.fixtures.normalization`

Specifically the `normalize_int` but there may be others.

### How can it be fixed

Audit these two modules for duplicate functions and remove the duplicates.  In the case of `normalize_int`, the `_utils` one should be kept.  Use your best judgement on any others that are found.

**Comment by isaacelee** [comment]
I'm going to look in to this, shouldn't be too difficult.

**Comment by glaksmono** [comment]
@isaacelee are you still working on this? Otherwise I'm considering to take a stab on it
