### ISSUE TITLE
Remove stale peers from peer pool

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1455]
### What is wrong?

It seems that we currently do not clean up well peers that aren't alive anymore.

Here's an example log. That peer died at `11-08 17:13:52` but is still in the pool almost 24 hours later (and will probably continue to stay there) 

```
     INFO  11-08 17:12:59           ETHPeerPool  Adding ETHPeer <Node(0x9140@35.198.39.201)> to pool
    INFO  11-08 17:13:17      PeerHeaderSyncer  Starting sync with ETHPeer <Node(0x9140@35.198.39.201)>
    INFO  11-08 17:13:17      PeerHeaderSyncer  ETHPeer <Node(0x9140@35.198.39.201)> disconnected, aborting sync
    INFO  11-08 17:13:17       FastChainSyncer  Header Sync with ETHPeer <Node(0x9140@35.198.39.201)> ended
 WARNING  11-08 17:13:52           ETHPeerPool  ETHPeer <Node(0x9140@35.198.39.201)> is no longer alive but has not been removed from pool
    INFO  11-08 17:14:02      PeerHeaderSyncer  Starting sync with ETHPeer <Node(0x9140@35.198.39.201)>
    INFO  11-08 17:14:02      PeerHeaderSyncer  ETHPeer <Node(0x9140@35.198.39.201)> disconnected, aborting sync
    INFO  11-08 17:14:02       FastChainSyncer  Header Sync with ETHPeer <Node(0x9140@35.198.39.201)> ended
    INFO  11-08 17:14:49      PeerHeaderSyncer  Starting sync with ETHPeer <Node(0x9140@35.198.39.201)>
    INFO  11-08 17:14:49      PeerHeaderSyncer  ETHPeer <Node(0x9140@35.198.39.201)> disconnected, aborting sync
    INFO  11-08 17:14:49       FastChainSyncer  Header Sync with ETHPeer <Node(0x9140@35.198.39.201)> ended
 WARNING  11-08 17:14:52           ETHPeerPool  ETHPeer <Node(0x9140@35.198.39.201)> is no longer alive but has not been removed from pool
...(repeats forever)...
WARNING  11-09 11:07:26           ETHPeerPool  ETHPeer <Node(0x9140@35.198.39.201)> is no longer alive but has not been removed from pool
```

My understanding is that since the peer pool is usually capped at some threshold, these useless peers will keep us from accepting other more useful peers and by doing that will keep us from syncing with other peers, hence slowing us down.

### How can it be fixed

Remove peer after some threshold period of not being alive is reached.
As I haven't been much involved in the syncing code I'd like to hear your opinion on that @pipermerriam @carver

**Comment by cburgdorf** [comment]
I also noticed that after my node catching up quite well it has fallen behind recently again and the log looks a lot like this:

```
   DEBUG  11-10 20:11:03      DiscoveryService  Already connected to 10 peers; sleeping
   DEBUG  11-10 20:11:04     DiscoveryProtocol  Ignoring find_node request from unknown node <Node(0xd356@139.59.86.165)>
   DEBUG  11-10 20:11:05      DiscoveryService  Already connected to 10 peers; sleeping
   DEBUG  11-10 20:11:06            FullServer  Receiving handshake from Address(104.198.105.184:udp:55586|tcp:55586)
   DEBUG  11-10 20:11:06               ETHPeer  Disconnecting from remote peer; reason: too_many_peers
   DEBUG  11-10 20:11:06     DiscoveryProtocol  Ignoring find_node request from unknown node <Node(0xdfca@118.24.20.114)>
   DEBUG  11-10 20:11:07      DiscoveryService  Already connected to 10 peers; sleeping
   DEBUG  11-10 20:11:09      DiscoveryService  Already connected to 10 peers; sleeping
```

So, maybe this further validates my point that the syncing stalls because we don't clean up the peer pool and at some point our peer pool is just full of dead nodes.

**Comment by pipermerriam** [comment]
@cburgdorf FYI, the reason for that logging message was to detect this.  We ideally don't want to fix this by sweeping the peer pool for disconnected peers because that hides the deeper bug of ending up with peers that don't get automatically removed from the pool.

First priority would be to try and figure out why the peers ended up dead but not removed and  if that search doesn't yield anything after some reasonable amount of time we can look into adding something that periodically removes dead peers.

**Comment by pipermerriam** [comment]
And now moments after typing that, I'm open to stop-gap fix for this to do a periodic sweep, but I think it should still output an `ERROR` level message so that we're motivated to fix the issue rather than ignore it indefinitely.

**Comment by cburgdorf** [comment]
>Note that "disconnected, aborting sync" is the syncer saying that the peer became disconnected some other way, not that it is actively disconnecting the peer. So something is causing the peer service to shut down but not leave the pool.

>We ideally don't want to fix this by sweeping the peer pool for disconnected peers because that hides the deeper bug of ending up with peers that don't get automatically removed from the pool.

Ah ok, so what you are saying is that a client that disconnects (for whatever reason) should be removed from the peer pool directly at that moment in time?

I thought that if a peer disconnects from us we may keep it in the pool and try to reconnect several times and only after x attempts of re-establishing a connection to them we would eventually give up on it and remove it from the pool.

>I would love to see the debug logs to know more, between 17:12:59 and 17:13:17.

Here you go
https://gist.github.com/cburgdorf/b5c92accc07524a37fe240900239aa6b

**Comment by pipermerriam** [comment]
> I thought that if a peer disconnects from us we may keep it in the pool and try to reconnect several times and only after x attempts of re-establishing a connection to them we would eventually give up on it and remove it from the pool.

No, current architecture has the `PeerPool` class responsible for managing the pool of peers which involves removing the peer from the pool when it disconnects.

https://github.com/ethereum/py-evm/blob/ae1e3e4fc133f36db2238f61dac05a4e4e344319/p2p/peer.py#L846-L861

We need to know why the finished callback never gets called.

**Comment by carver** [comment]
>> I would love to see the debug logs to know more, between 17:12:59 and 17:13:17.

> Here you go
https://gist.github.com/cburgdorf/b5c92accc07524a37fe240900239aa6b

Wow, there is not a peep even in the debug logs. Maybe it was somehow shut down before being added to the pool (so the finished callback is never called)

Can you add ~5s before the last logs?

Best guess, the peer shut down somewhere between 832 and 844:

https://github.com/ethereum/py-evm/blob/9870841a126fb53a6cbab2ef7bf3d46262fa23a8/p2p/peer.py#L831-L856

Note that the finished callback is in line 856. Looks like that belongs between 831 and 832.

**Comment by cburgdorf** [comment]
>Can you add ~5s before the last logs?

Here's a bit more than that (17:10 to 17:15)
https://gist.github.com/cburgdorf/8c952fbd1d83fc13bd815e1f2e1009f5

**Comment by carver** [comment]
Yup, died before adding to pool:

```
   DEBUG  11-08 17:12:59               ETHPeer  ETHPeer <Node(0x9140303e704e9d1b706b23fbd1b8c605555eb97256cb6c34c42ed03330fb8579ad6520336fde13f75f3f3e007e77e28bca283fcd3fbbb53e7f483488b7ecc35a@35.198.39.201:63229)> disconnected: disconnect_requested
   DEBUG  11-08 17:12:59               ETHPeer  ETHPeer <Node(0x9140@35.198.39.201)> had nothing left to do, ceasing operation...
   DEBUG  11-08 17:12:59               ETHPeer  Waiting for child services: [<ResponseCandidateStream(ETHPeer <Node(0x9140@35.198.39.201)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)>, <trinity.protocol.common.boot.DAOCheckBootManager object at 0x7f9b809a2278>]
   DEBUG  11-08 17:12:59           ETHProtocol  Sending ETH/Status msg: {'protocol_version': 63, 'network_id': 1, 'td': 5699707424982088372716, 'best_hash': b'\x84\xd4\xa7\x1fZD\xbf\xfb&>u\x85\x8f\xf4\x9f\x1b^\xb3\xc0nb\xb9\x7f\xb7T\xd8RJ\x82\xe0\xbb\xc7', 'genesis_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3'}
   DEBUG  11-08 17:12:59  ResponseCandidateStream  <ResponseCandidateStream(ETHPeer <Node(0x9140@35.198.39.201)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)> finished: Cancellation requested by ETHPeer:ETHPeerPool:FullServer:MainnetFullNode token
   DEBUG  11-08 17:12:59  ResponseCandidateStream  Stream <ResponseCandidateStream(ETHPeer <Node(0x9140@35.198.39.201)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)> shutting down, cancelling the pending request
   DEBUG  11-08 17:12:59  ResponseCandidateStream  <ResponseCandidateStream(ETHPeer <Node(0x9140@35.198.39.201)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)> halted cleanly
   DEBUG  11-08 17:12:59   DAOCheckBootManager  <trinity.protocol.common.boot.DAOCheckBootManager object at 0x7f9b809a2278> finished: Cancellation requested by ResponseCandidateStream:ETHPeer:ETHPeerPool:FullServer:MainnetFullNode token
   DEBUG  11-08 17:12:59   DAOCheckBootManager  <trinity.protocol.common.boot.DAOCheckBootManager object at 0x7f9b809a2278> halted cleanly
   DEBUG  11-08 17:12:59            FullServer  Could not complete handshake: IncompleteReadError('0 bytes read on a total of 32 expected bytes',)
   DEBUG  11-08 17:12:59               ETHPeer  All child services finished
   DEBUG  11-08 17:12:59               ETHPeer  ETHPeer <Node(0x9140@35.198.39.201)> halted cleanly
    INFO  11-08 17:12:59           ETHPeerPool  Adding ETHPeer <Node(0x9140@35.198.39.201)> to pool
```
