### ISSUE TITLE
Add support for "clique" based consensus

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1457]
### What is wrong?

The [clique](https://github.com/ethereum/EIPs/issues/225) POA has gained some consensus across more clients.  We should add support for it.

### How can it be fixed

Implement EIP225 based consensus in py-evm and trinity.

**Comment by lithp** [comment]
This would enable support for both goerli and rinkeby

**Comment by lithp** [comment]
Here's the unmerged draft EIP: https://github.com/ethereum/EIPs/pull/1570/files

**Comment by pipermerriam** [comment]
This seems like a good grant candidate.  Anyone want to try to ballpark implementation complexity, assign a DAI amount and submit it to the grants request page.

**Comment by soc1c** [comment]
Goerli initiative is willing to fund this with 2500 DAI if anyone wants to pick this up. (Ideally with https://github.com/ethereum/trinity/issues/72 as bonus.)

If anyone is interested, reach out here, here https://github.com/ethereum/trinity/issues/72 or here https://github.com/goerli/testnet/issues/16 before allocating a bounty.

**Comment by veox** [comment]
FTR, I've started looking into this. Nothing serious yet; branch [`add-goerli-testnet`](https://github.com/veox/py-evm/commits/add-goerli-testnet).

**Comment by veox** [comment]
Another day, more notes.

-----

There are two rule sets for header fields:

* one for epoch transition blocks (including genesis), also called "checkpoints" for containing full lists of authorised signers (authorities);
*  another for all blocks in between epoch transitions.

There is overlap in rule sets; main differences (explicitly stated in EIP-225) are for `beneficiary`, `nonce`, `extra_data`.

-----

More of an issue is the _statefulness_ of the protocol.

> Every epoch transition (...) acts as a stateless checkpoint, from which capable clients should be able to sync without requiring any previous state. [On epoch transition] all non settled votes are discarded, and tallying starts from scratch.
>
> For all non-epoch transition blocks:
> 
> * Signers may cast one vote per own block to propose a change to the authorization list.
> * (...)
> * Votes are tallied live as the chain progresses (...).
> * Proposals reaching majority consensus `SIGNER_LIMIT` come into effect immediately.

As things stand, [`check_pow` is stateless](https://github.com/ethereum/py-evm/blob/30eb1ae4a2d77db0f63e9a635345cc3ac718d9b8/eth/consensus/pow.py#L61-L65), and therefore can be [meaningfully contained in `BlockHeader.validate_seal()`](https://github.com/ethereum/py-evm/blob/30eb1ae4a2d77db0f63e9a635345cc3ac718d9b8/eth/vm/base.py#L884-L886).

`check_clique_poa()` would need to get passed a list - which may change on any (non-epoch?..) block.

The need to maintain this authority list, plus the current vote tally, means there is no short-cut for nodes that do not wish to participate in block sealing. They, too, must maintain this rolling state. "Come into effect immediately" is causing the complication.

(OT bit: Had it been "get approved to start on next epoch transition", verifying a header would be possible by using the static list from the start of current epoch.)

Anyway, seems that authority verification must be done at the `Chain` level. Similar to `parent_hash`, authority data refers to previous blocks. Different from `parent_hash`, this can't be done if there's been a gap in header verification leading up to the header-at-question. (This may become an issue downstream, in `trinity`.)

**Comment by veox** [comment]
FTR, @cburgdorf has started work on this (both `py-evm` and `trinity`). See [gitter](https://gitter.im/ethereum/trinity?at=5d934a236d4b2512c14942ca) for progress / issue description.

**Comment by cburgdorf** [comment]
I just merged https://github.com/ethereum/py-evm/pull/1855 which adds most of Clique Consensus. It's not 100 % implemented at this point which means it won't be able to spin up a Py-EVM based node as an actual Görli validator but it's possible to sync the Görli network just fine.

I still need to polish the Trinity side of this but it should soon land in a next release I'm sure.
