### ISSUE TITLE
replace active/crystallized state with one beaconstate

### ISSUE THREAD

**Issue by djrtwo** [ethereum/py-evm#1475]
### What is wrong?
https://github.com/ethereum/eth2.0-specs/pull/122 combined active and crystallized state into singular BeaconState.

### How can it be fixed
* Rename `CrystallizedState` to `BeaconState`
* Add `ActiveState` fields to `BeaconState`
* Remove `ActiveState`
* Unify state throughout code

**Comment by djrtwo** [comment]
@hwwhww I'm going to tackle this one to get familiar with the codebase before digging into other issues

**Comment by hwwhww** [comment]
As we discussed, use #1503 steps to replace this ticket.
