### ISSUE TITLE
Exception when logging stats

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1489]
### What is wrong?

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 121: ordinal not in range(128)
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
Message: 'blks=0     txs=0      bps=0    tps=0     elapsed=5.0  head=#6717266 (6fcf\u2026051c)  age=3d16h19m'
Arguments: None

```

Seems to be a regression

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by pipermerriam** [comment]
Interesting, I chose the unicode elipsis since it only takes up a single space (which is also what geth does).  Wondering what is causing the attempt to do `ascii` encoding?

**Comment by pipermerriam** [comment]
I'm curious what `stream.encoding` is during that first line of your stacktrace.  You should be able to reproduce locally with something like `logging.info('\u2026')`.

**Comment by cburgdorf** [comment]
@pipermerriam it's on our team server if you feel like investigating :)
