### ISSUE TITLE
Dynamically adjust request size based on historical peer performance.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1499]
### What is wrong?

When syncing, we regularly request significantly more *things* than the peer will respond with.  For example, we typically request 256 receipts at a time but most peers seem to only respond with ~20-30.

Each time this happens the *completed* ones get marked as such, but the remaining ones get pushed back into the queue.  In a situation where a peer only regularly returns 1/10th of the requested data that means that we have to work through the full queue 10 times before we actually complete the batch.  This seems like it probably adds a lot of overhead.

### How can it be fixed

Use the statistics for a peer's historical performance to dynamically adjust how many items for a given request type we should ask for at a given time.  

- I suspect we need additional stats tracking for this.  
- We may need to do local some local tracking just within the sync code so that requests from other parts of the application don't pollute this data.

We can probably use something similar to the difficulty adjustment.  If the response is incomplete we slowly lower the batch size.  If the response is complete we increase the batch size.  We can use the *quality* metric to inform this.  Something like:

- if incomplete response: `new_batch_size = old_batch_size - (10 - quality / 10)`
- if complete response: `new_batch_size = old_batch_size + (4 - quality / 25)`

If we treat `batch_size` as a float then some version of this formula should work reasonably well, with the batch size moving faster anytime the quality is very low and moving slower when the quality is high, always trying to slowly increase the batch size.

**Comment by pipermerriam** [comment]
@carver curious to hear your thoughts and whether I've mis-understood anything.

**Comment by pipermerriam** [comment]
This doesn't appear to be the bottleneck.  I manually tuned the receipts and block bodies to use batch sizes of 30 and 65 respectively which were the upper bounds I was seeing in the logs and general sync throughput remains roughly the same.

It appears that downloading receipts may be the bottleneck.  Looking at the logs:

- The headers queue is normally maxed out both in terms of number processing **and** the queue itself being full.
- The bodies queue is normally empty.
- The receipts queue is always working both in terms of tasks processing and queued.

So, bottleneck is still a mystery.  Things I think I've ruled out are:

- The CPU bound normalization during request/response (though I think this is something that will eventually be needed).
- Persisting the block (should be able to do ~100/second based on basic benchmarks)
- Downloading the individual parts (blocks-per-second doesn't seem to scale up even with multiple high quality peers).
- Extra churn in the task queues due to incomplete responses.

**Comment by carver** [comment]
> [Requesting 256 receipts at a time] doesn't appear to be the bottleneck.

Yup, that would also have been my prediction.

> The headers queue is normally maxed out both in terms of number processing and the queue itself being full.

That is interesting, because it suggests that the header sync is *not* a bottleneck in your test (it was in my testing some while back). If all the queued headers are in processing, and the receipts queue is backed up, that means that I agree the receipts are the bottleneck.

**Comment by pipermerriam** [comment]
Some useful information here but closing for now since this doesn't seem to be the location of any bottlenecks.

**Comment by pipermerriam** [comment]
Receipt validation does appear to be one of the slow parts.  I did some experimentation and was able to roughly double the speed by:

1. using `asyncio.gather` and running all of the `chain.coro_validate_receipt(...)` calls concurrently.
2. Adding some basic optimizations to the `validate_receipt` mechanism to only check each `address` and `topic` for inclusion in the `bloom` filter once (since both addresses and topics can be duplicated across a single receipt).

**Comment by carver** [comment]
> was able to roughly double the speed

Sweet, sounds like that's worth getting into a PR.
