### ISSUE TITLE
"$trinity console" not work

### ISSUE THREAD

**Issue by akltcode** [ethereum/py-evm#1525]
* trinity Version: 0.1.0a17
* OS: linux
* Python Version (python --version):2.6
* Environment (output of `pip freeze`):
apt-clone==0.2.1
apt-xapian-index==0.47
apturl==0.5.2
asn1crypto==0.24.0
async-generator==1.10
async-lru==0.1.0
asyncio-cancel-token==0.1.0a2
attrdict==2.0.0
backcall==0.1.0
blinker==1.3
bloom-filter==1.3
Brlapi==0.6.4
cachetools==2.1.0
cffi==1.11.5
chardet==2.3.0
coincurve==8.0.2
command-not-found==0.3
cryptography==2.4.2
cytoolz==0.9.0.1
decorator==4.3.0
defer==1.0.6
dirspec==13.10
eth-abi==1.2.2
eth-account==0.2.3
eth-bloom==1.0.1
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.3.0
hexbytes==0.1.0
httplib2==0.9.1
idna==2.7
ifaddr==0.1.5
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.13.1
lahja==0.9.0
louis==2.6.4
lru-dict==1.1.6
lxml==3.6.0
Mako==1.0.3
MarkupSafe==0.23
mypy-extensions==0.4.1
netdisco==2.2.0
netifaces==0.10.7
oauthlib==1.0.3
onboard==1.2.0
oneconf==0.3.9
parsimonious==0.8.1
parso==0.3.1
pexpect==4.0.1
pickleshare==0.7.5
Pillow==3.1.2
piston-mini-client==0.7.5
plyvel==1.0.5
prompt-toolkit==1.0.15
psutil==3.4.2
ptyprocess==0.5
py-ecc==1.4.3
py-evm==0.2.0a34
pyasn1==0.1.9
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.7.2
pycups==1.9.73
pycurl==7.43.0
pyethash==0.1.27
Pygments==2.3.0
pygobject==3.20.0
PyICU==1.9.2
PyJWT==1.3.0
pysha3==1.0.2
python-apt==1.1.0b1+ubuntu0.16.4.2
python-dateutil==2.7.5
python-debian==0.1.27
python-xapp==1.0.0
pyxdg==0.25
reportlab==3.3.0
requests==2.9.1
rlp==1.0.3
screen-resolution-extra==0.0.0
sessioninstaller==0.0.0
setproctitle==1.1.8
simplegeneric==0.8.1
six==1.10.0
system-service==0.3
termcolor==1.1.0
thin-client-config-agent==0.8
toolz==0.9.0
traitlets==4.3.2
trie==1.3.8
trinity==0.1.0a17
ubuntu-drivers-common==0.0.0
ufw==0.35
uPnPClient==0.0.8
urllib3==1.13.1
uvloop==0.11.2
virtkey==0.63.0
virtualenv==16.1.0
wcwidth==0.1.7
web3==4.4.1
websockets==5.0.1
xkit==0.0.0
zeroconf==0.21.3

### What is wrong?

Please include information like:

* full output of the error you received:
trinity: error: argument subcommand: invalid choice: 'console' (choose from 'fix-unclean-shutdown', 'attach'

* what command you ran : $trinity console

* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by cburgdorf** [comment]
Apologies. The quickstart was not up to date and used an outdated, removed command. This doc update should get you unstuck.

https://github.com/ethereum/py-evm/pull/1544
