### ISSUE TITLE
rename `TRACE` log level to `DEBUG2`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1526]
### What is wrong?

In the original design for Py-EVM I imagined using the built-in python logging facilities to do EVM tracing #62 .  Since then the `TRACE` log level has evolved to just mean *lower level debug logs*.

Second, we've ended up needing to tune the logging level of certain *noisy* modules when ideally we'd be able to do this with finer grained logging levels.

### How can it be fixed

Rename the `TRACE` to `DEBUG2` and change the numeric value to be `8`.  The idea here is that we can extend this to `DEBUG3` and onward.

- The `eth.tools.logging.TraceLogger` should be renamed to `EthereumLogger`
- The `eth.tools.setup_trace_logging` should be renamed to `setup_ethereum_logging`
- We should add a call `eth.tools.logging.setup_ethereum_logging` should be updated to call [`logging.setLoggerClass`](https://docs.python.org/3/library/logging.html#logging.setLoggerClass) so that the `logging.getLogger` will always return an instance of our logger.
- The `TraceLogger.trace` method should be renamed to `TraceLogger.debug2`
- Update the Trinity CLI parser component that handles logging configuration.

Next steps would be to create `DEBUG3` and to take our historically *noisy* loggers and set them to use this new lower level logging.

**Comment by rayrapetyan** [comment]
@pipermerriam, please confirm no one is working on it so I can start working on this one.

**Comment by pipermerriam** [comment]
@rayrapetyan :+1: go for it.

**Comment by veox** [comment]
> The idea here is that we can extend this to DEBUG3 and onward.

I'd rather have `TRACE2` than `DEBUG3`. :|
