### ISSUE TITLE
Implement becaon chain MVP network protocol

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-evm#1542]
We need the following commands:

### For the handshake

- `Status`: Exchange protocol version, network id, and head hash

### For chain syncing

- `GetBeaconBlock`: Get a specific block by hash or number
- `BeaconBlock`: Reply with a requested block

### For building the chain

- `BeaconBlock`: Same command as above, but sent with out request
- `AttestationRecord`: Send attestations

### What we ignore for now to keep it simple

- Requesting/sending multiple blocks
- State syncing
- `SpecialRecord`s

**Comment by hwwhww** [comment]
> GetBeaconBlock: Get a specific block by hash or number
> BeaconBlock: Reply with a requested block

I *think* it won't be too much overhead to change `GetBeaconBlock` to `GetBeaconBlocks`? That said, it's okay to implement `GetBeaconBlock` at the begining, but if it's easy to make `GetBeaconBlocks`, I don't see why we don't start with `GetBeaconBlocks`.
