### ISSUE TITLE
Speed up `integer_squareroot` with `math`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1550]
### What is wrong?
The [`integer_squareroot`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#integer_squareroot) function could be logically equal to `math.floor(math.sqrt(value))`.

### How can it be fixed
I simply tried to use `math.floor(math.sqrt(value))`. However, it didn't pass the test case of big number:
```
actual     = 4294967296
expected   = 4294967295
value      = 18446744073709551615
```

We can investigate it later.

**Comment by pipermerriam** [comment]
This works:

```python
def fast_integer_sqrt(value: int) -> int:
    with decimal.localcontext() as ctx:
        ctx.prec = 100
        return int(decimal.Decimal(value).sqrt())
```

Looks like it's about 4x faster as profiled using:

```python
import random
import timeit

def integer_sqrt(value: int) -> int:
    ...

def fast_integer_sqrt(value: int) -> int:
    ...

def test_time_base():
    print('base', timeit.timeit("integer_sqrt(random.randint(0, 2**256 - 1))", globals={"integer_sqrt": integer_sqrt, 'random': random}))

def test_time_fast():
    print('fast', timeit.timeit("fast_integer_sqrt(random.randint(0, 2**256 - 1))", globals={"fast_integer_sqrt": fast_integer_sqrt, 'random': random}))
```

**Comment by pipermerriam** [comment]
You might experiment with the precision as 100 was chosen arbitrarily and is likely overkill though i don't know how much it will effect performance.

**Comment by pipermerriam** [comment]
> Would you like me to submit a PR?

That would be great

**Comment by hwwhww** [comment]
closing in favor of #1698, thanks to @onyb!
