### ISSUE TITLE
Implement helper functions in Per-Slot processing section

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/py-evm#1551]
### What is wrong?

Implement these per-slot-processing functions defined [beacon-chain spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#per-slot-processing):

- `def verify_special_attestation_data(state: State, obj: SpecialAttestationData) -> bool` for CASPER_SLASHING
- `def verify_merkle_branch(leaf: Hash32, branch: [Hash32], depth: int, index: int, root: Hash32) -> bool` for DEPOSIT_PROOF

### How can it be fixed

- Implement these functions under `eth/beacon/helpers.py`
- Replace lists in the spec with tuples to meet the py-evm style.

**Comment by hwwhww** [comment]
WIP changes: https://github.com/ethereum/eth2.0-specs/pull/234/

**Comment by ChihChengLiang** [comment]
Now #234 become #241 and the later is merged.

**Comment by ChihChengLiang** [comment]
`def verify_special_attestation_data` would be nuked soon https://github.com/ethereum/eth2.0-specs/pull/252

**Comment by ChihChengLiang** [comment]
`from eth.utils.merkle import verify_merkle_proof`  is equivalent to `verify_merkle_branch`. And it is using `keccak` already. #1564
