### ISSUE TITLE
Change Hashing Function from Blake2b to Sha3

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1564]
### What is wrong?

Per https://github.com/ethereum/eth2.0-specs/pull/227

### How can it be fixed

1. Use this one:
    ```
    from eth_hash.auto import keccak
    ```
2. Remove `eth/utils/blake.py` and related tests.

**Comment by ChihChengLiang** [comment]
The spec [says](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#hash) keccak is used now and might switch to another hash function in the future.

This means that we are replacing all hash in the codebase now and will do the same in the future.
Propose to implement a hash wrapper in `eth/utils`, say `hash_function.py`.

```python
# eth/utils/hash_function.py
from eth_typing import Hash32
from eth_hash.auto import keccak

def hash_(data: bytes) -> Hash32:
    return Hash32(keccak(data))
```
and in the rest of the codebase just do
```python
from eth.utils.hash_function import hash_
hash_(something)
```
so the future switch of hash function would become just a one-liner fix in `hash_function.py`.

**Comment by jannikluhn** [comment]
Should this be based in `py-evm` or in `eth_hash`? Asking because if we implement tree hashing in `py-ssz` (which would make sense from my point of view), it would be convenient to use the same function.

`hash_` is probably not a good name as it's not clear that it's for the beacon chain and it also looks quite similar to just `hash`. What about `hash_eth20`?

**Comment by ChihChengLiang** [comment]
Ahhhh ... sorry @jannikluhn, I missed your comment. I would recommend `py-ssz` should have its own wrapper for the hash function that is based in `eth_hash`, so the boundaries between `py-evm`, `py-ssz`, and `eth_hash` are clean.

I agree the point that `hash_` is unclear, but `hash_eth20` sounds like 20. What about `hash_bcc`?
