### ISSUE TITLE
Migrate `trinity` and `p2p` modules to `ethereum/trinity` repository

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1594]
I have consulted the stars and it is time to cut the umbilical cord and move the `p2p` and `trinity` modules into the https://github.com/ethereum/trinity repository.

Current (not yet vetted) timeline is to do this during the week of December 17th-21st.

- It looks like https://blog.github.com/changelog/2018-10-30-issue-transfer/ may be useful for issue migration
- we should ensure we preserve history in both repositories which probably means pushing the full history into `ethereum/trinity` and then removing all of the `eth` stuff.
- we should consider whether to move `py-evm` into a beta (probably a very long beta)
- the https://trinity.ethereum.org/ site is hosted via github pages from the `ethereum/trinity` repo so we need to maintain that.
- annoyingly https://trinity.readthedocs.io is for the TNC token thing so we need to decide where to put the trinity specific docs.

**Comment by veox** [comment]
> annoyingly https://trinity.readthedocs.io is for the TNC token thing so we need to decide where to put the trinity specific docs.

Not just the token, but also the "Trinity routing node" - funny enough, also in Python 3.6+:

https://trinity.readthedocs.io/en/latest/en-EN/Trinity_Eth_Deployment_Guide_en.html

Name-collide all the things!..

**Comment by carver** [comment]
> * we should ensure we preserve history in both repositories which probably means pushing the full history into `ethereum/trinity` and then removing all of the `eth` stuff.

:+1: 
> * we should consider whether to move `py-evm` into a beta (probably a very long beta)

:+1:

**Comment by veox** [comment]
Possibly combine with issue #1529?..

**Comment by veox** [comment]
https://trinity.ethereum.org/ is currently inaccessible.

**Comment by pipermerriam** [comment]
@veox waiting for the devops team to do their thing  ping @jpitts
