### ISSUE TITLE
Reduce benchmark suite running time

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1607]
### What is wrong?

Benchmarking is regularly the slowest test. We aren't using the benchmarking data for anything, so the slowness has no benefit.

### How can it be fixed

Reduce the load factor on all the benchmark tests by ~100x (with a minimum of 2-3 runs, just to exercise the test a couple times).

Probably by setting custom run counts here:
https://github.com/ethereum/py-evm/blob/86297509afb50ccae75b9d2edc6aef23637556f1/scripts/benchmark/run.py#L78-L92

**Comment by jmcph4** [comment]
@carver Apologies if I've overlooked something as I'm new to the codebase, but would it not be better to go straight to the source? For example with `MineEmptyBlocksBenchmark`:

https://github.com/ethereum/py-evm/blob/86297509afb50ccae75b9d2edc6aef23637556f1/scripts/benchmark/checks/mine_empty_blocks.py#L21-L25

**Comment by carver** [comment]
The reason I suggested modifying in the test script is that when you *actually* run the benchmark (instead of just test that it works), you probably do want a bunch of runs (say, 500 in this case).

**Comment by ashish10677** [comment]
Hello. I am new to open source and I want to contribute to this issue. Can someone please guide me?

**Comment by carver** [comment]
@ashish10677 thanks for reaching out. This one is in progress in #1629 and fairly close to completion. Feel free to ping on another `Good First Issue` if you find another one you're keen to work on.

**Comment by carver** [comment]
If anyone wants to pick up where #1629 left off (and update for recent benchmark changes), it looks like it's not being actively worked on anymore. @ashish10677 are you interested?

**Comment by carver** [comment]
It's fast enough for now, closing.
