### ISSUE TITLE
Misc new helpers

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1609]
### What is wrong?

- [ ] [`is_active_validator`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#is_active_validator) - build a "property" `is_active` in `ValidatorRecord` and then update [`eth.beacon.helpers.get_active_validator_indices`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#get_active_validator_indices)
- Implement new `eth/beacon/helpers` functions:
    - [ ] [`is_double_vote`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#is_double_vote)
    - [ ] [`is_surround_vote`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#is_surround_vote)

### How can it be fixed

Read the spec and write tests fo these functions.

**Comment by jmcph4** [comment]
Just to clarify, for the first item it should be as straightforward as checking the `status` field of `ValidatorRecord` and then simply having `is_active_validator` wrap the new `ValidatorRecord.is_active` property, correct?

**Comment by jmcph4** [comment]
@hwwhww Sorry, I must've missed this!

**Comment by pipermerriam** [comment]
@ralexstokes this one might be a good one.

**Comment by ralexstokes** [comment]
@pipermerriam it does look good however there is already a PR at #1612

**Comment by pipermerriam** [comment]
@ralexstokes :cry: yeah, realized that a few minutes ago as I worked through my github notifications.

**Comment by hwwhww** [comment]
closing in favor of #1612
