### ISSUE TITLE
Rename all `module.utils` to `module._utils`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1625]
### What is wrong?

We as a team know that `utils` is a private API, but this distinction isn't always clear to others using the library.

### How can it be fixed

Anywhere that we have a `utils` module, it should be renamed to `_utils`.

**Comment by rayrapetyan** [comment]
@pipermerriam, found following "utils" in py-evm tree:
``
./eth/vm/forks/spurious_dragon/utils.py
./p2p/utils.py
./trinity/utils
./scripts/benchmark/utils
./stubs/eth_keys/utils
./eth/beacon/utils
./eth/utils
./tests/beacon/utils
./tests/trinity/utils
./tests/trinity/core/utils
```
Should they all be renamed? Thanks.

**Comment by rayrapetyan** [comment]
@cburgdorf, squash fails on my side (I believe this is due to mix of conflicts and renamed files), please try to rebase on merge. Thanks.
