### ISSUE TITLE
Implement `validate_proposer_signature`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1639]
### What is wrong?
Per-slot processing - [validate proposer signature](
https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#proposer-signature)

### How can it be fixed
1. Implement the `validate_proposer_signature` logic in `eth/beacon/state_machines/validation.py`.
    * Use flat hash instead of tree hashing for now
2. Add tests for it!

**Comment by Bhargavasomu** [comment]
I would like to work on this, will update with a PR soon.
