### ISSUE TITLE
Fresh clone of repo followed by `pytest` fails

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/py-evm#1646]
* py-evm Version: `master` at `48be6ca6bea5c6349ff3e00e477ce0db8305b43f`
* OS: osx
* Python Version (python --version): 3.6.5
* Environment (output of `pip freeze`): 

alabaster==0.7.12
apipkg==1.5
appnope==0.1.0
argh==0.26.2
asn1crypto==0.24.0
async-generator==1.10
async-lru==0.1.0
asyncio-cancel-token==0.1.0a2
atomicwrites==1.2.1
attrdict==2.0.0
attrs==18.2.0
Babel==2.6.0
backcall==0.1.0
bleach==3.0.2
bloom-filter==1.3
bumpversion==0.5.3
cachetools==2.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
coincurve==10.0.0
colorama==0.4.1
coverage==4.5.2
cryptography==2.4.2
cytoolz==0.9.0.1
decorator==4.3.0
docopt==0.6.2
docutils==0.14
eth-abi==1.3.0
eth-account==0.2.3
eth-bloom==1.0.1
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.4.1
execnet==1.5.0
flake8==3.5.0
hexbytes==0.1.0
hypothesis==3.69.5
idna==2.7
ifaddr==0.1.6
imagesize==1.1.0
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.13.2
Jinja2==2.10
jsonschema==2.6.0
lahja==0.10.0
lru-dict==1.1.6
lxml==4.2.5
MarkupSafe==1.1.0
mccabe==0.6.1
more-itertools==4.3.0
mypy==0.641
mypy-extensions==0.4.1
netdisco==2.2.0
netifaces==0.10.7
packaging==18.0
parsimonious==0.8.1
parso==0.3.1
pathtools==0.1.2
pexpect==4.6.0
pickleshare==0.7.5
pkginfo==1.4.2
pluggy==0.7.1
plyvel==1.0.5
prompt-toolkit==1.0.15
ptyprocess==0.6.0
py==1.7.0
py-ecc==1.4.7
-e git+https://github.com/ethereum/py-evm.git@48be6ca6bea5c6349ff3e00e477ce0db8305b43f#egg=py_evm
pycodestyle==2.3.1
pycparser==2.19
pycryptodome==3.7.2
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.3.1
pyparsing==2.3.0
pysha3==1.0.2
pytest==3.6.4
pytest-asyncio==0.9.0
pytest-asyncio-network-simulator==0.1.0a2
pytest-cov==2.5.1
pytest-watch==4.2.0
pytest-xdist==1.18.1
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
readme-renderer==24.0
requests==2.21.0
requests-toolbelt==0.8.0
rlp==1.0.3
simplegeneric==0.8.1
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.7.9
sphinx-rtd-theme==0.4.2
sphinxcontrib-asyncio==0.2.0
sphinxcontrib-websupport==1.1.0
termcolor==1.1.0
toolz==0.9.0
tox==2.7.0
tqdm==4.28.1
traitlets==4.3.2
trie==1.3.8
-e git+https://github.com/ethereum/py-evm.git@48be6ca6bea5c6349ff3e00e477ce0db8305b43f#egg=trinity_peer_count_reporter_plugin&subdirectory=trinity-external-plugins/examples/peer_count_reporter
twine==1.12.1
typed-ast==1.1.1
uPnPClient==0.0.8
urllib3==1.24.1
uvloop==0.11.2
virtualenv==16.1.0
watchdog==0.9.0
wcwidth==0.1.7
web3==4.4.1
webencodings==0.5.1
websockets==5.0.1
zeroconf==0.21.3

### What is wrong?

I cloned the repo and wanted to run the tests for the first time following: https://py-evm.readthedocs.io/en/latest/contributing.html#setting-the-stage.

Once inside a virtualenv, I ran `pip install -e .[dev]` and did not get any errors.

I then ran `pytest` and got three errors as it went to collect tests:

```
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.6.5, pytest-3.6.4, py-1.7.0, pluggy-0.7.1
rootdir: /src/py-evm, inifile: pytest.ini
plugins: xdist-1.18.1, cov-2.5.1, asyncio-0.9.0, asyncio-network-simulator-0.1.0a2, hypothesis-3.69.5
collected 56294 items / 3 errors / 1 skipped

=================================================================================================================== ERRORS ===================================================================================================================
_________________________________________________________________________________________ ERROR collecting tests/core/validation/test_validation.py __________________________________________________________________________________________
import file mismatch:
imported module 'test_validation' has this __file__ attribute:
  /src/py-evm/tests/beacon/test_validation.py
which is not the same as the test file we want to collect:
  /src/py-evm/tests/core/validation/test_validation.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
______________________________________________________________________________________________ ERROR collecting tests/database/test_chaindb.py _______________________________________________________________________________________________
import file mismatch:
imported module 'test_chaindb' has this __file__ attribute:
  /src/py-evm/tests/beacon/db/test_chaindb.py
which is not the same as the test file we want to collect:
  /src/py-evm/tests/database/test_chaindb.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
____________________________________________________________________________________ ERROR collecting tests/trinity/integration/test_plugin_discovery.py _____________________________________________________________________________________
ImportError while importing test module '/src/py-evm/tests/trinity/integration/test_plugin_discovery.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/trinity/integration/test_plugin_discovery.py:7: in <module>
    from peer_count_reporter_plugin import PeerCountReporterPlugin
E   ModuleNotFoundError: No module named 'peer_count_reporter_plugin'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================================== 1 skipped, 3 error in 19.96 seconds =====================================================================================================
```

### How can it be fixed

I fixed the plugin error with `pip install -e trinity-external-plugins/examples/peer_count_reporter`.

Should we add this to the docs? Or is it supposed to install with the original `pip install` and it is not working for some reason?

The other two may require a name change to avoid collisions -- I'll defer to those who have touched those files to chime in.

**Comment by cburgdorf** [comment]
Thank you for bringing that to our attention again. You aren't the first to run into this and so I just proposed a PR to only run this test when the `--integration` flag is explicitly passed. https://github.com/ethereum/py-evm/pull/1649

**Comment by pipermerriam** [comment]
@ralexstokes friendly suggestion :smile_cat: :

take a quick *gander* at https://guides.github.com/features/mastering-markdown

You can use tripple backticks for code blocks which makes that type of terminal output a lot easier to read.

**Comment by pipermerriam** [comment]
I think we should clean-up (rename these test modules) to fix these two errors:

```
import file mismatch:
imported module 'test_validation' has this file attribute:
/src/py-evm/tests/beacon/test_validation.py
which is not the same as the test file we want to collect:
/src/py-evm/tests/core/validation/test_validation.py
HINT: remove pycache / .pyc files and/or use a unique basename for your test file modules
______________________________________________________________________________________________ ERROR collecting tests/database/test_chaindb.py _______________________________________________________________________________________________
import file mismatch:
imported module 'test_chaindb' has this file attribute:
/src/py-evm/tests/beacon/db/test_chaindb.py
which is not the same as the test file we want to collect:
/src/py-evm/tests/database/test_chaindb.py
HINT: remove pycache / .pyc files and/or use a unique basename for your test file modules
```

**Comment by ralexstokes** [comment]
@pipermerriam yep totally -- didn't realize the code blocks would handle off panel scrolling (thanks github!)

and those names sound good to me... i'll be eagerly awaiting to `pytest` :)

**Comment by ralexstokes** [comment]
@veox it seems like this issue has been resolved, just tried from a fresh install and had no problems getting the tests to run, as far as i can tell the above activity fixed the original issue

**Comment by cburgdorf** [comment]
@ralexstokes thanks for checking
