### ISSUE TITLE
Add `Computation.is_success` and `Computation.is_error` API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#165]
### What is wrong?

There are many places in the codebase that use the check `if computation.error` to check for whether a given round of computation resulted in an error.  This would be better implemented as a dedicated API so that future changes to the EVM semantics on what constitutes an error are not directly tied to the presence or absence or truthyness of what lives at `computation.error`

### How can it be fixed

Add a these new APIs to the `Computation` object:

* `Computation.is_success`
* `Computation.is_error`

`is_success` should be a computed `property` that returns `True` if `computation.error is None`.  Conversely,  `is_error` should be a computed property that returns the opposite of whatever `is_success` returns.

**Comment by mohit2agrawal** [comment]
Hi!! Can I start with this?
Thank you ...

**Comment by pipermerriam** [comment]
@mohit2agrawal have at it.  Please reach out if you need guidance.

**Comment by mohit2agrawal** [comment]
@pipermerriam  created PR#171

**Comment by pipermerriam** [comment]
closed via #171 

Thanks @mohit2agrawal
