### ISSUE TITLE
Update constants

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1672]
### What is wrong?

- Remove `MIN_VALIDATOR_REGISTRY_CHANGE_INTERVAL`: https://github.com/ethereum/eth2.0-specs/pull/340/
- Update `INACTIVITY_PENALTY_QUOTIENT`: https://github.com/ethereum/eth2.0-specs/pull/347
- Update `TARGET_COMMITTEE_SIZE`: https://github.com/ethereum/eth2.0-specs/pull/341

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by Bhargavasomu** [comment]
I'm working on this.
