### ISSUE TITLE
Update all `toolz` imports to come from `eth_utils.toolz`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1711]
Loosely depends on https://github.com/ethereum/py-evm/pull/1710 to ensure `eth-utils` is new enough.

### What is wrong?

We have `toolz/cytoolz` compat via `eth_utils.toolz` but this library still directly uses `cytoolz`

### How can it be fixed

Update all `toolz` imports to come from `eth_utils.toolz`

```
from cytoolz import assoc
# should become
from eth_utils.toolz import assoc
```

**Comment by stringray55** [comment]
i have already done this on  trinity , can i take up this issue ?

**Comment by ashish10677** [comment]
Is this issue still open? I am very new to open source, can I contribute to this issue?

**Comment by cburgdorf** [comment]
@ashish10677 that one just landed but feel free to browse through https://github.com/ethereum/py-evm/labels/Good%20First%20Issue for inspiration :)
