### ISSUE TITLE
Builder documentation is empty

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1725]
### What is wrong?

https://py-evm.readthedocs.io/en/latest/api/tools/api.tools.builders.html

The docs for the chain builder are empty on RT

https://github.com/ethereum/py-evm/blob/master/docs/api/tools/api.tools.builders.rst

But they should be pulling from the various function docstrings.

### How can it be fixed

Figure out why they aren't being built correctly

**Comment by Bhargavasomu** [comment]
I don't see the docs empty though.

**Comment by pipermerriam** [comment]
looks like it has been fixed!
