### ISSUE TITLE
Convert VM.block and .header to .get_block() and .get_header()

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1752]
Remove the `@property` values for `vm.header` and `vm.block`, and replace with a `get_header()` and `get_block()`

```python
class VM:
    def get_header(self):
        ...
    def get_block(self):
        ...
```

Makes it a lot clearer that they have side effects.

_Originally posted by @pipermerriam in https://github.com/ethereum/py-evm/pull/1747_

**Comment by carver** [comment]
This API is used in a lot of places, so it will take some work to hunt them all down. But there shouldn't be any subtleties. As long as the tests pass, we should be good. So this seems like a good first issue.

**Comment by dherykw** [comment]
Hi,

I have this issue solved with all test passed, I also had to add set_block() function in order to remove the property properly.

My doubt is if you want me to create a new branch before to do the pull request or you want me to add the modification to a current branch.

**Comment by pipermerriam** [comment]
New branch and new pull request please.

**Comment by csurfer** [comment]
Looks like this issue is already [addressed and completed](https://github.com/ethereum/py-evm/blob/1af151ab218b905f4fdf7a285cbe14ebf094a7c4/eth/vm/base.py#L113-L123). Suggesting to close this issue for cleaner issue queue.

**Comment by carver** [comment]
Thanks for taking a look!
