### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#177]
We should expand the documentation to cover the following topics.

#### The `Chain` class. 

* High level description of it's purpose/role/responsibilities
* Brief explanation of how it wraps VM classes.
* List of public methods (they don't need to be individually documented yet)

#### The `BaseChainDB` class

* High level overview of it's purpose/role/responsibilities
  * It's like an ORM for the `Chain` class.
* List of public methods (they don't need to be individually documented yet)

####  The `VM` class.  

* High level overview of it's purpose/role/responsibilities
* Basic explanation of the hierarchy of  `apply_transaction > execute_transaction > apply_message > apply_computation`.    
* List of methods and properties that can be set with simple descriptions of what each is used for

#### The EVM `Computation` API

* Enumerate all of the APIs that are accessible from the `Computation` object and the nested `GasMeter`, `Stack`, `Memory` , `Message`, and `CodeStream` apis.
* List of public methods and properties for these objects

#### Developers Guide

* Chains go in `evm.chains.<name>`
* Fork rules go in `evm.vm.forks.<name>`

**Comment by cburgdorf** [comment]
Closing in favor for https://github.com/ethereum/py-evm/issues/557
