### ISSUE TITLE
Optimize JournalDB More

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1775]
### What is wrong?

My latest mainnet test shows `JournalDB` being a major contributor to `import_block()` time:

- `.commit()` taking 13.5% of total time
- `.__getitem__` taking another >2% of time
- `.latest` and `.latest_id` ~1.1%
- `.record()` ~0.85%

A few other methods that are in the 0.5-1% range, but add up to another couple of percent. It looks like a major reason for each of them is `uuid` which is spending 4.3% of total blocktime in `__hash__` and another 2.7% in `__eq__`.

### How can it be fixed

- Look into uuid alternatives
- refactor the data store to always keep the latest data and have the changesets be backwards-facing diffs (since gets get is called 17k times, commit called 43k times, and `discard` only called 274 times, we should optimize for the "happy path" where everything gets committed).

I think this will wrap up the `import_block()` performance sprint for now (`HexaryTrie` is the next major contributor, but that will take some serious new features, and I think it's fast enough to make Beam Sync progress)

**Comment by pipermerriam** [comment]
UUID is for uniqueness.  We should be able to just use an `itertools.count()` and use sequential numbers right?

**Comment by carver** [comment]
> UUID is for uniqueness. We should be able to just use an `itertools.count()` and use sequential numbers right?

Right, that's my first instinct too. Since the journal itself only exists on one thread/process, and mostly invents its own checkpoints, I expect that to work fine.
