### ISSUE TITLE
JSON-RPC server

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#178]
We need to implement the basic API for JSON-RPC server.  A simplistic start can be found here: https://github.com/ethereum/py-evm/tree/master/evm/rpc

Lets flesh this out further to something more complete.  For now lets keep it as something that must be run as `python evm/rpc/server.py ....`

I suggest sticking to the *read-only* apis for now.

---
Compiled to-do list:

- [ ] support all the `eth_*` read-only methods
  - [x] `eth_protocolVersion`
  - [ ] `eth_syncing`
  - [ ] `eth_coinbase`
  - [ ] `eth_mining`
  - [ ] `eth_hashrate`
  - [ ] `eth_gasPrice`
  - [ ] `eth_accounts`
  - [x] `eth_blockNumber`
  - [x] `eth_getBalance`
  - [x] `eth_getStorageAt`
  - [x] `eth_getTransactionCount`
  - [x] `eth_getBlockTransactionCountByHash`
  - [x] `eth_getBlockTransactionCountByNumber`
  - [x] `eth_getUncleCountByBlockHash`
  - [x] `eth_getUncleCountByBlockNumber` block int
  - [x] `eth_getUncleCountByBlockNumber` block string
  - [x] `eth_getCode`
  - [ ] `eth_call`
  - [ ] `eth_estimateGas`
  - [x] `eth_getBlockByHash`
  - [x] `eth_getBlockByNumber` block int
  - [x] `eth_getBlockByNumber` block string
  - [ ] `eth_getTransactionByHash`
  - [x] `eth_getTransactionByBlockHashAndIndex`
  - [x] `eth_getTransactionByBlockNumberAndIndex`
  - [ ] `eth_getTransactionReceipt`
  - [x] `eth_getUncleByBlockHashAndIndex`
  - [x] `eth_getUncleByBlockNumberAndIndex` block int
  - [x] `eth_getUncleByBlockNumberAndIndex` block string
  - [ ] `eth_getCompilers`
  - [ ] `eth_getLogs`
  - [ ] `eth_getWork`
- [x] serve over socket
- [ ] make score available on block object, so that a returned block dict can be formatted without a `chain` reference ?

To save for another PR:

- [ ] server over HTTP

**Comment by carver** [comment]
Reasonable approach: only serve json-rpc over sockets, plus an HTTP proxy like: https://github.com/chfast/json-rpc-proxy/blob/master/jsonrpcproxy.py

**Comment by pipermerriam** [comment]
Yeah, I'd only implement *one* of the IPC/HTTP API with preference towards socket based on the thing you linked and the conversation from all-core-devs.

**Comment by pipermerriam** [comment]
More notes to self.  This was said somewhere in our conversations.  cc @chfast  Pulling the `Manager` layer out of web3 *might* make sense here so that it can be use din the proxy library.  Reasoning is that it would also allow for use of the middleware API in the proxy which seems like a really nice feature, allowing many degrees of freedom in what the proxy can actually do.

**Comment by carver** [comment]
> Pulling the `Manager` layer out of web3 _might_ make sense here so that it can be use din the proxy library.

At the very least, pulling `IPCProvider` out of web3.py would be straightforward, but I agree that it's worth exploring what it would take to extract all of `Manager` (and with it, a middleware lib).

I'm starting to look at how to test this, and here's my plan so far:

1. Generate a short test chain with MainnetTesterChain, with known values for various items, like block hashes, transaction hashes, etc.
2. Store the chain.db and known values in `/tests` (as well as a script for generating them)
3. In RPC tests, load the chain.db and request values from it using standard JSON-RPC calls
4. Assert that the retrieved values match the known values from step 2

**Comment by pipermerriam** [comment]
Future TODO: make gas price strategy for `eth_gasPrice` pluggable and implement the Eth Gas Station strategy:  https://github.com/ethereum/web3.py/issues/496

**Comment by pipermerriam** [comment]
Quick information drop about `eth_estimateGas`.

This *may* be as simple as returning `computation.gas_meter.start_gas - computation.gas_meter.gas_remaining`.  However, if memory serves, I think it's more complicated that that.

The way that I recall go-ethereum doing this is to execute the transaction with some very large upper bound of gas like `50,000,000`.

- if it errors out: return an error over RPC
- if it passes, proceed into a binary search, re-running the transaction at each gas value until you find the spot where it succeeds/fails and use the success value.

I'll re-iterate that the binary search approach may not be necessary based on how we do gas consumption tracking.  Let's see.
