### ISSUE TITLE
readme note `--recursive` when cloning for dev

### ISSUE THREAD

**Issue by djrtwo** [ethereum/py-evm#180]
### What is wrong?
- tests fail if do not clone in with `--recursive` option
- this is not noted in "Development" setup and it is not clear that it is the source

### How can it be fixed

- add note about `git clone --recursive` to the Development section of readme

**Comment by djrtwo** [comment]
Can handle if you give me a thumbs up

**Comment by pipermerriam** [comment]
I'll even give you a ⛄️ and a 🏩
