### ISSUE TITLE
Observe all opcodes triggered when a transaction is invoked

### ISSUE THREAD

**Issue by kimdora** [ethereum/py-evm#1801]
I want to measure coverage. Is there API to observe all opcodes triggered when a transaction is invoked on EVM?

**Comment by cburgdorf** [comment]
Not really an API but does tracing output count? You can follow all opcodes
through that.

**Comment by kimdora** [comment]
Actually, I couldn't understand clearly what you say.

Assume that we have a smart contract file written in Solidity.
```
pragma solidity >= 0.4.22;

contract Calculator {
    int256 public result = 0;
    
    function getResult() public view returns(int256) {
        return result;
    }
    function add(int256 a) public {
        result = result + a;
    }
    function sub(int256 a) public {
        result = result - a;
    }
    function mul(int256 a) public {
        result = result * a;
    }
    function div(int256 a) public {
        require(a != 0);
        result = result / a;
    }
}
```
I want to trace a transaction which calls 'add(5)'.
So, I executed this transaction on evm like:
```
_, _, computation = self.chain.apply_transaction(signed_new_tx)
```

But the 'computation.code' just shows all contract bytecode. But I want to know just executed opcodes during transaction.

**Comment by kimdora** [comment]
@cburgdorf 

What did you mean <code>output count</code>?
And how to catch output count?

**Comment by cburgdorf** [comment]
What I meant to say is: I'm not sure if there's an API that does exactly what you want but you might be able to extract the information you are looking for from the logging output.

Put this in your script:

```python
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=0)
```

Then you'll get fine grained logging output of the execution showing you exactly the steps that it takes. Maybe this will get you closer to your goal?

**Comment by kimdora** [comment]
Wow, really thank you so much to help me friendly!!

**Comment by cburgdorf** [comment]
You're welcome! Happy to hear it helped! :tada:

**Comment by pipermerriam** [comment]
This would  be a good thing to add to the documentation.
