### ISSUE TITLE
Add Istanbul block number to Ropsten

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1838]
### What is wrong?

The Ropsten network definition does not include Istanbul.

### How can it be fixed

- Wait for a block number to be picked for Ropsten.
- Add the block number to `eth/chains/ropsten/__init__.py`

**Comment by carver** [comment]
6485846 https://gitter.im/ethereum/AllCoreDevs?at=5d822fa2ab4244767bbfde75

**Comment by voith** [comment]
@carver already done in https://github.com/ethereum/py-evm/pull/1851
