### ISSUE TITLE
Tracking: some upstream test fixtures fail when updating to v7.0.0-beta.1

### ISSUE THREAD

**Issue by veox** [ethereum/py-evm#1857]
This issue is to track findings on why [upstream fixtures](https://github.com/ethereum/tests/releases/tag/v7.0.0-beta.1) fail in PR #1852, so I don't trash the PR discussion.

Working in [`update-fixtures-to-v7.0.0-beta.1` branch of mine](https://github.com/veox/py-evm/commits/update-fixtures-to-v7.0.0-beta.1), rolling off the one in PR #1852.

-----

There are 6 failures for `--fork Istanbul`, all in `fixtures/BlockchainTests/GeneralStateTests/stRevertTest`:

```
RevertPrecompiledTouch.json:RevertPrecompiledTouch_d0g0v0_Istanbul
RevertPrecompiledTouch.json:RevertPrecompiledTouch_d3g0v0_Istanbul
RevertPrecompiledTouch_storage.json:RevertPrecompiledTouch_storage_d0g0v0_Istanbul
RevertPrecompiledTouch_storage.json:RevertPrecompiledTouch_storage_d3g0v0_Istanbul
RevertPrecompiledTouchExactOOG.json:RevertPrecompiledTouchExactOOG_d7g2v0_Istanbul
RevertPrecompiledTouchExactOOG.json:RevertPrecompiledTouchExactOOG_d31g2v0_Istanbul
```

These were added in https://github.com/ethereum/tests/pull/580, then updated/refilled in https://github.com/ethereum/tests/pull/609 and https://github.com/ethereum/tests/pull/610.

For the first four, [data indices 0 and 3 produce the same result upstream](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchFiller.json#L14), so it's no surprise that 0 and 3 fail while 1 and 2 do not.

The last two [are also grouped upstream](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchExactOOGFiller.json#L130).

**Comment by veox** [comment]
`RevertPrecompiledTouch.json` has [program of the following form](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchFiller.json#L78):

```
{
 (CALL 50000 1 0 0 0 0 0)
 (CALL 50000 2 0 0 0 0 0)
 (CALL 50000 3 0 0 0 0 0)
 (CALL 50000 4 0 0 0 0 0)
 (CALL 50000 5 0 0 0 0 0)
 (CALL 50000 6 0 0 0 0 0)
 (CALL 50000 7 0 0 0 0 0)
 (CALL 50000 8 0 0 0 0 0)
 [[1]] (GAS)
 [[2]] (GAS)
 [[3]] (GAS)}
```

That is, sequentially call precompiles `1` through `8`, then store remaining gas 3 times in this contract's storage.

The [comment](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchFiller.json#L76) shows that it's expected to OOG-fail.

-----

Guess: the difference between `py-evm` and `geth` (which [filled the tests](https://github.com/ethereum/tests/pull/609)) is due to different gas use.

[Trace](https://gist.github.com/veox/4b134ddbb1df14f62c47052a56379c79) shows tx fee of 98780; haven't found number for `geth` yet.

-----

Guess: very telling is the fact that variants 0 and 3 of the test say that [precompile 3 (`RIPEMD160`) should get its nonce cleared](https://github.com/ethereum/tests/blob/cfbcd15f91d4d6e1785d9cae5c5c37f47e8bad46/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchFiller.json#L25-L26). `RIPEMD160` is a special cookie...

**Comment by veox** [comment]
Relating to candidate 2: `ethereum/EIPs` issue https://github.com/ethereum/EIPs/issues/716 ("Clarification about when touchedness is reverted during state clearance").

**Comment by veox** [comment]
So, in short:

In `collect_touched_accounts()`, we now have to also check when a `computation` touches `RIPEMD160`, succeeds itself, but the parent (or someone along the call ladder) fails, and the failee is not necessarily the origin computation.

I can't figure out how to do this without a double-pass through the nested computations, or ugly hacks - not today, at least, and got to run anyway.

**Comment by veox** [comment]
[This commit](https://github.com/veox/py-evm/commit/6c6db730311a5f956a98a1535f7b896c350b0f11) fixes the first four failing cases.

`RevertPrecompiledTouchExactOOG` still fail - investigating.

**Comment by veox** [comment]
The test cases

```
RevertPrecompiledTouchExactOOG.json:RevertPrecompiledTouchExactOOG_d7g2v0_Istanbul
RevertPrecompiledTouchExactOOG.json:RevertPrecompiledTouchExactOOG_d31g2v0_Istanbul
```

get [insufficient (69K) gas is provided](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchExactOOGFiller.json#L280), and should OOG-fail according to upstream.

The precompile called, `0x08`, [should remain as-is](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/GeneralStateTestsFiller/stRevertTest/RevertPrecompiledTouchExactOOGFiller.json#L129-L138), whereas if 120K gas is provided, its storage should be cleared (highlighted in same link).

This seems consistent to me.

The call that OOG-fails is nested, as shown in [the trace from `py-evm`](https://gist.github.com/veox/b8605347f34e0038d029809f1697f6de). On exit from that, remaining gas is enough to finish the parent and grand-parent computations.

`py-evm` then proceeds to clear `0x08`'s, which seems incorrect.

**Comment by veox** [comment]
Slowest tests: https://gist.github.com/veox/02336c518f049cb749608657622d127f

**Comment by veox** [comment]
Closing since PR #1858 was superseded by PR #1871 and addressed this; the issue was left hanging.

-----

JIC, I was reminded of this because [a discussion arose recently on gitter](https://gitter.im/ethereum/tests?at=5e9def278e987f3a5e31d422) of `geth` (!) failing to produce an expected result for @adria0, for case `RevertPrecompiledTouchExactOOG_d30g2v0_Istanbul` in particular.

That said, I don't remember if `py-evm` had issues with the `d30g2v0` variant... The sherlocking is now split across several issues/PRs pertaining to different network upgrades, and tests filled by two different implementations.

So, just dropping this here for future archeologists.

Pinging @holiman, too, as participant in gitter discussion.

**Comment by adria0** [comment]
@veox, finally I found the way to fix it https://github.com/openethereum/openethereum/pull/11597/commits/74eabccda5b286bfc68138dc65b5b4dcd5c2ce3e.

In short, this test has a preexistent `0000...0008` in the account trie with zero gas. The test makes a  call/staticcall to this address, so since this *empty* account is touched, the account should be removed from the trie. But, the call does not have enough gas to call the precompile, so it reverts, and as [EIP161](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md) says *that empty account deletions are reverted when the state is reverted*.

OE was not "reverting the deletions", so there was a problem in the state trie root.

Take care, with the current gas parameters defined in the `RevertPrecompiledTouchExactOOG.json`, some of the tests do not OOG (needs to be fixed) and this cause some confusion when debugging the test cases.

**Comment by veox** [comment]
> But, the call does not have enough gas to call the precompile, so it reverts, and as EIP161 says _that empty account deletions are reverted when the state is reverted_.

... Except if it's pre-compile number `3`, in which case _the deletion should be left as-is_, including in [cases when the parent computation eventually fails](https://github.com/ethereum/py-evm/issues/1857#issuecomment-538460472) anyway, whether it's the origin computation or not; unless [the test-filling implementation changes](https://github.com/ethereum/py-evm/issues/1857#issuecomment-538433394), as this github issue has shown, then do as Simon says, and don't be the last one to find a chair...

Toodly-doo!.. :saxophone:

In all seriousness: always mention the exception.

-----

This is all OT to the issue(s) you've found; still!

`<rant>`

A "proper" way to address the above would be<sup>†</sup> to have an irregular state transition (IST) to "right" this previous "accidental" IST that we let slip through, because it was a secondary failure in an already debilitating net-wide consensus failure.

The common reasoning against such "right the wrong" ISTs is "the tech debt only increases with that"; to which I can only reply that the _cognitive_ debt keeps piling on, with each new node implementation, with each new developer who is about to find out the hard way. :exploding_head: 

Doesn't matter if you start from a snapshot, doesn't matter if you're running a testnet. I swear, we'll take this `RIPEMD160` ghost to Eth 2.0 with us, as an annoying weird uncle to Casper. :smile: 

Perhaps I should write an EIP for that, if only for it to be filed as a formal complaint. Maybe next March 32nd, instead of dealing with integer overflows...

<sup>†</sup> Or "would have been", I gather, considering this is years-old.

`</rant>`

**Comment by adria0** [comment]
> ... Except if it's pre-compile number 0x3, in which case the deletion should be left as-is, including in cases when the parent computation eventually fails anyway, whether it's the origin computation or not; unless the test-filling implementation changes, as this github issue has shown, then do as Simon says, and don't be the last to find a chair, because it's not there!..

Haha, it has been an interesting issue to fix, to be the first one :sweat_smile:

I agree with you that this TriePrunning/0x3 specific issue maybe is one of the cases that deserve an IST, because it happens that the embedded logic to fix this irregular stuff is also deployed to other blockchains, not only mainnet. I put on the agenda to ping you on next March 32 (with integer overflows :stuck_out_tongue_winking_eye:), hehe.
