### ISSUE TITLE
Add py3.8 tests

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1872]
### What is wrong?

No tests validating 3.8 support.

### How can it be fixed

Add new tox environment and circle CI tests.
Also, be sure to add pip constraint blake2b-py v0.1.3:
https://github.com/ethereum/vyper/pull/1678#issuecomment-552017732

**Comment by veox** [comment]
I'm taking a look at this. First step is to get a local virtualenv with Python 3.8.

-----

Dependency `coincurve` has [pre-built wheels for Python 3.8 starting with `v13` (most recent ATM)](https://pypi.org/project/coincurve/#id3).

Using an earlier version (like currently-pinned `v10`) doesn't work on Arch Linux: attempting to build wheel results in error of:

```
    building '_libsecp256k1' extension
    creating build/temp.linux-x86_64-3.8/build
    creating build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.8 -c build/temp.linux-x86_64-3.8/_libsecp256k1.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/_libsecp256k1.o
    build/temp.linux-x86_64-3.8/_libsecp256k1.c:493:10: fatal error: secp256k1_ecdh.h: No such file or directory
      493 | #include <secp256k1_ecdh.h>
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by veox** [comment]
Working branch in https://github.com/veox/py-evm/commits/add-python3.8-testing - will re-visit later.

**Comment by veox** [comment]
I've tried installing `libleveldb-dev` for Python 3.8 jobs only, using [this wonderful way (commit)](https://github.com/ethereum/py-evm/commit/63683874211720b67247c45aaa7d4819d8deb5e2) (via [docs](https://circleci.com/docs/2.0/writing-yaml/)).

Problem is, [it doesn't work](https://circleci.com/gh/veox/py-evm/4568) (CircleCI only takes the first step). There are a couple topics on CircleCI's forums about this:

https://discuss.circleci.com/t/yaml-anchors-implementation-incomplete/16916
https://discuss.circleci.com/t/allow-bundling-several-steps-e-g-by-supporting-nested-steps/15339/7

-----

So the two remaining options are:

* install `libleveldb-dev` on _all_ CI jobs, even ones that don't need it;
* wait for `plyvel` to get Python 3.8 wheels.

I'll now perform a magic trick be doing both at the same time. :smile: :drum:

**Comment by veox** [comment]
Specific to Python 3.8 linting, it turned out `pyflakes` (a nested dependency) [also needs to be updated](https://github.com/ethereum/py-evm/pull/1885#issuecomment-564213570). However, a tagged version hasn't yet been released.
