### ISSUE TITLE
Consensus failure on contract create/destruct within same block (both FrontierVM and PetersburgVM)

### ISSUE THREAD

**Issue by veox** [ethereum/py-evm#1912]
* py-evm Version: ever since [`v0.2.0-alpha.43`](https://github.com/ethereum/py-evm/releases/tag/v0.2.0-alpha.43)
* OS: Arch Linux
* Python Version (python --version): Python 3.7
* Environment (output of `pip freeze`): MISSING

### What is wrong?

First raised in https://github.com/ethereum/trinity/issues/1478: failure to perform full-sync, tested on main-net/Goerli (pretty sure this is chain-independent). There is a state root mismatch.

It [seems](https://github.com/ethereum/trinity/issues/1478#issuecomment-579715506) that if a contract is created and deleted within the same block, then we're erroneously re-creating its storage as "empty".

Probably has something to do with how accounts and their stores are marked "dirty" when they're created/destroyed.

See https://github.com/ethereum/trinity/issues/1478 for much more debug details, traces, etc..

### How can it be fixed

There is quite some indirection there - journals, caches...

[Bisect showed](https://github.com/ethereum/trinity/issues/1478#issuecomment-575335557) the culprit to be https://github.com/ethereum/py-evm/pull/1735.

[Debug-tracing showed](https://gist.github.com/veox/bbc4586e5d59f44c3cdc089ee801481a#file-the-diff) the following (diff between good/bad `py-evm` versions in linked gist):

```
>   DEBUG2  01-29 13:33:37      AccountStorageDB  Deleting all storage in account 0xb214cbce30676bd117f95a8695d34427295cd6f7, hashed 0x88593f406750a4f40bdf82a1efbacbec6a5297e62830ee1a8942f083de97ad14
> ...
>   DEBUG2  01-29 13:33:37             AccountDB  Updating account 0xb214cbce30676bd117f95a8695d34427295cd6f7 to storage root 0x856157ca7b18901a14648a8d426b568dcba060e3997d5a409c25fe09d77351b6
> ...
>   DEBUG2  01-29 13:33:37             AccountDB  Updating account 0xb214cbce30676bd117f95a8695d34427295cd6f7 to storage root 0x856157ca7b18901a14648a8d426b568dcba060e3997d5a409c25fe09d77351b6
> ...
```

* First, seems we're going through the "dirty" list twice.
* Then, the "deleting all storage in account" message can be slightly misleading: the "hashed" value `0x8859...` printed is a hash of the address, `0xb214c...` - not sure this is intended; if anything, I'd expect the account's storage root to be here instead, or at least also present.
* More importantly, _this_ is the snippet that seems to show the account's storage is deleted, and then re-created.

**Comment by carver** [comment]
Thanks! I think I've got this reproduced in a fairly small test now... (in #1913 )

Unless I get pulled into something else today, I expect to get a draft of a fix up by end of day.

**Comment by carver** [comment]
Whelp, now we're syncing to 116530 before failing... I'm guessing that it's somehow related to the same bug (or the fix for the bug).

**Comment by carver** [comment]
Ok, looks like #1913 gets the job done. I'm still wondering if there's a better solution, or a worthwhile refactor.
