### ISSUE TITLE
Handle case of gap incorrectly being filled with checkpoint header

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1928]
### What is wrong?

Consider the following scenario:

```
A3 (set checkpoint)
B0:2 (now canonical)
A2 (set checkpoint)
# At this point `A2` becomes the new head and `get_header_chain_gaps`
# will report no gaps. While that is technically true `B1` is not a parent of `A2`
# and so we allowed getting into a situation where we do not recognize a gap,
# yet don't have a well-connected chain.
```

### How can it be fixed

From https://github.com/ethereum/py-evm/pull/1924#discussion_r427207209

When we set A2 as a new checkpoint it becomes the new canonical head and we stop caring about A3. I think that is the way it should be (For some reason, the user decided to set the checkpoint to A2, imho that should be given precedence).

But know what happens is that A2 is closing a gap "backwards" which isn't what we want here! We get into a situation where our gap tracking would think we have a well-connected chain which isn't the case!

So, my idea is that `persist_checkpoint_header` must be altered to notice situations when it is backwards filling a gap and then do one of these things:

1. Raise an exception. Let client code now that they can not pick this checkpoint before they bring the database into a different state

2. Alternatively, remove the B1 header to create a new gap to continue to track this missing connection. Removing just the single header before A2 should be enough because we do not know where exactly the fork might be (which are uncles, which are actual parents)

**Comment by carver** [comment]
> When we set A2 as a new checkpoint it becomes the new canonical head and we stop caring about A3. I think that is the way it should be (For some reason, the user decided to set the checkpoint to A2, imho that should be given precedence).

Hm, I'd like to think about this some more. If I reuse the *same* checkpoint multiple times, it doesn't mean I want to reset the chain head back to the old checkpoint, it just means I want the same base. This is a truly weird corner case (how often will it be set to precisely the parent of an old checkpoint?) but I *think* I'd want it to stitch together with an existing canonical chain if there is one.

**Comment by carver** [comment]
> 2\. remove the B1 header to create a new gap to continue to track this missing connection. Removing just the single header before A2 should be enough because we do not know where exactly the fork might be (which are uncles, which are actual parents)

Got a version of this in #1930
