### ISSUE TITLE
Dependency Conflicts (eth-utils 1.10.0 requires eth-hash<0.4.0,>=0.3.1, but you'll have eth-hash 0.2.0)

### ISSUE THREAD

**Issue by arjunaskykok** [ethereum/py-evm#1968]
* py-evm Version: 0.3.0a20
* OS: osx
* Python Version (python --version): 3.9.0
* Environment (output of `pip freeze`):

blake2b-py==0.1.3
cached-property==1.5.2
cytoolz==0.11.0
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keys==0.3.3
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
lru-dict==1.1.6
mypy-extensions==0.4.3
py-ecc==4.1.0
py-evm==0.3.0a20
pyethash==0.1.27
rlp==2.0.1
sortedcontainers==2.3.0
toolz==0.11.1
trie==2.0.0a5
typing-extensions==3.7.4.3

### What is wrong?

```bash
$ pip install py-evm
Installing collected packages: eth-typing, eth-hash, toolz, cytoolz, eth-utils, eth-keys, cached-property, mypy-extensions, py-ecc, eth-bloom, blake2b-py, pyethash, lru-dict, rlp, sortedcontainers, hexbytes, typing-extensions, trie, py-evm
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

eth-utils 1.10.0 requires eth-hash<0.4.0,>=0.3.1, but you'll have eth-hash 0.2.0 which is incompatible.
Successfully installed blake2b-py-0.1.3 cached-property-1.5.2 cytoolz-0.11.0 eth-bloom-1.0.3 eth-hash-0.2.0 eth-keys-0.3.3 eth-typing-2.2.2 eth-utils-1.10.0 hexbytes-0.2.1 lru-dict-1.1.6 mypy-extensions-0.4.3 py-ecc-4.1.0 py-evm-0.3.0a20 pyethash-0.1.27 rlp-2.0.1 sortedcontainers-2.3.0 toolz-0.11.1 trie-2.0.0a5 typing-extensions-3.7.4.3
```

**Comment by carver** [comment]
How does this work for you if you use the recommended `pip install --use-feature=2020-resolver py-evm`?

**Comment by arjunaskykok** [comment]
Yeah, no problem with that approach. So is the bug invalid because this is pip issue? Feel free to close the bug. Maybe I need to upgrade the pip software.

**Comment by carver** [comment]
Yeah, that 2020-resolver functionality is the default in the latest `pip` versions, so I'll close as invalid. Thanks for confirming!
