### ISSUE TITLE
Berlin support

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1970]
Meta-source: https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/berlin.md

EIPS: 
- [x] https://eips.ethereum.org/EIPS/eip-2565 at #1972 
- [x] https://eips.ethereum.org/EIPS/eip-2718 at #1973
- [x] https://eips.ethereum.org/EIPS/eip-2929 at #1974
- [x] https://eips.ethereum.org/EIPS/eip-2930 at #1975 (note dependencies)

Tests:
- [x] Upgrade to v8 #1985
- [x] Enable Berlin CI job #1991 

No longer scheduled:
- [x] ~https://eips.ethereum.org/EIPS/eip-2315 at #1926~
- [x] ~2537 at #1927~

**Comment by palango** [comment]
Do you have an estimate on when this will be finished and released?

**Comment by carver** [comment]
Yes, my estimate is... sometime today :)

**Comment by carver** [comment]
... and it's out https://py-evm.readthedocs.io/en/latest/release_notes.html#py-evm-0-4-0-alpha-1-2021-03-22
