### ISSUE TITLE
Upgrade tests to v8.0.1

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1985]
### What is wrong?

Want the latest Berlin tests in ethereum/tests, found in v8.

### How can it be fixed

For v8.0.0:
Upgrade and fix any new issues. Note that this test is apparently broken:
> draganrakitaToday at 12:07 AM
> Hi, can somebody check if this nonce in post state is okay, when test is run i am getting 1000000000000:
> https://github.com/ethereum/tests/blob/3f25e873a442700d0024168c54a45f6a9d2dec6e/BlockchainTests/GeneralStateTests/stBugs/extcodehashEmpty.json#L164
> Test is related to ExtcodehashEmpty.json

> DimitryToday at 2:02 PM
> Its not. This test is bug

https://discord.com/channels/595666850260713488/753271902520213625/818394550451961892

I'm *pretty* sure that's fixed in v8.0.1 though. See also:
> All state tests now have an rlp `txbytes` field. So no need to parse transaction arrays and do the signing.

**Comment by kclowes** [comment]
@carver - do you want me to close this PR or leave it open since we still need to actually run against the Berlin tests once all the code updates are in?

**Comment by carver** [comment]
Ah, no, it's a good point to add another item in #1970 , but it's okay to close this issue.
