### ISSUE TITLE
Persistent DB between sessions

### ISSUE THREAD

**Issue by gpsanant** [ethereum/py-evm#2027]
It seems as though there is no place in the documentation that explains how to user py-evm with a persistent database where the chain picks up from where it left off before termination from the previous process. How would I go about doing this?

**Comment by carver** [comment]
All of that logic is up to the user. When you pass in a database to the chain during initialization, that's when you would load the database from disk, for example.

**Comment by gpsanant** [comment]
> All of that logic is up to the user. When you pass in a database to the chain during initialization, that's when you would load the database from disk, for example.

Sorry, I don't think my question was clear. How do initialize a chain with a given database?

**Comment by carver** [comment]
The entry points for creating a chain take in a database as an argument. For example, see: https://py-evm.readthedocs.io/en/latest/guides/building_an_app_that_uses_pyevm.html#writing-the-application-code
