### ISSUE TITLE
RPC implementation

### ISSUE THREAD

**Issue by gpsanant** [ethereum/py-evm#2028]
* py-evm Version: Latest

### What is wrong?

I was wondering whether there is an RPC for py-evm to interact with the cahin in a normal way so I could hook Metamask up to a py-evm instance. Is this possible? If not, I was thinking of implementing my own, but can seems to figure out how to implement the event listeners for filtering logs and the `eth_call` method. Any ideas?

**Comment by carver** [comment]
py-evm only implements the virtual machine, not a full node. There was an attempt to build a full node, called Trinity, but it's currently on ice. If you want a development chain based on py-evm, you could try out eth-tester (which is integrated into web3.py).
