### ISSUE TITLE
Update reference to project template in docs

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#2032]
### What is wrong?

Project template is going to `carver`s fork instead of the main `ethereum` org fork of the template on this page:
https://github.com/ethereum/py-evm/blob/master/docs/guides/building_an_app_that_uses_pyevm.rst

### How can it be fixed

Replace both references with the `ethereum` org version of the template.

**Comment by MukulKolpe** [comment]
Hey @carver can I work on this issue?

**Comment by fselmo** [comment]
@MukulKolpe it's all yours. Thanks for the interest 👍
