### ISSUE TITLE
Cannot replay transactions with `v=0` using `py-evm`

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/py-evm#2042]
* py-evm Version: Using `web3["tester"]@latest` bundle with 5.24.0
* OS: osx
* Python Version (python --version): 3.8

### What is wrong?

I believe there is a validation check in current main that is incompatible with London transactions (https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/frontier/transactions.py#L92). This validation check currently checks if `v >= 27` but, for example, Hardhat transactions now all have `v=0` in London. Specifically, these are type 1/2 transactions in EIP-1559.

### How can it be fixed

It may already be fixed in the upcoming py-evm version that will ship with london support but wanted to flag in case it isn't :).

**Comment by fselmo** [comment]
@Pet3ris Welcome and thanks for the inquiry! Yeah, the signing also changes for typed transactions and this was implemented differently from the legacy transactions in the Berlin changes for `py-evm` and the London changes picked up from there.

That validation check you linked to is for a `Frontier` fork transaction. The "legacy" transactions for each fork inherit from each other all the way up to the most recent [LondonLegacyTransaction](https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/london/transactions.py#L68) which inherits from [BerlinLegacyTransaction](https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/berlin/transactions.py#L78)... which inherits from [MuirGlacierTransaction](https://github.com/ethereum/py-evm/blob/21759ee681315f7099b14893b6ac6d1a5e659bc0/eth/vm/forks/muir_glacier/transactions.py#L14) and so on... down to the `FrontierTransaction` that you linked above.

However, when we get to Berlin and London (the introduction of typed transactions), there is also [AccessListTransaction](https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/berlin/transactions.py#L176) and [DynamicFeeTransaction](https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/london/transactions.py#L155) and unsigned versions of those as well. The signing field is also no longer referred to as `v` but `y_parity`.

The `validate` method that you linked to is a nice-to-have method for validating the `FrontierTransaction` class only and thus would not apply to the typed transactions mentioned above. The `y_parity` field can also be `1` thought, it is not always `0`.

I'm going to close this based on the above but feel free to re-open if I missed something.

**Comment by Pet3ris** [comment]
Thank you for the detailed explanation. I'm not fully aware of what the implications are for how to implement type 2 transactions in `web3.py` so perhaps it's simpler if I offer more context of what I was trying to do:

Effectively I was:

- downloading a recent transaction from mainnet by using `eth.getTransaction`
- turning it into a raw transaction with the following code:

```python
v = tx["v"]
r = int.from_bytes(tx["r"], "big")
s = int.from_bytes(tx["s"], "big")
unsigned_transaction = serializable_unsigned_transaction_from_dict(transaction)
raw_tx = encode_transaction(unsigned_transaction, vrs=(v, r, s))
```
- then using `eth_sendRawTransaction` to send this `raw_tx` to a local node to replay it


Does `w3.eth.sendRawTransaction(raw_tx)` need some adjustment to interpret the transaction as a type2 perhaps or would the transaction itself need some changes than what is returned from `eth.getTransaction`?

**Comment by fselmo** [comment]
You would have to clean up the `transaction` in this case to only have the necessary fields for the transaction type you want (so getting rid of `blockHash`, `blockNumber`, `gasPrice`, `hash`, `input`, etc... from the `eth_getTransaction` call) so that it has only the valid params of an unsigned transaction. Then it can be passed into `serializable_unsigned_transaction_from_dict`.

You can also re-create the transaction and use `w3.eth.account.sign_transaction()` as outlined [here](https://web3py.readthedocs.io/en/latest/web3.eth.account.html?highlight=interpreted%20based#sign-a-transaction).

In the latter case you can strip all the parameters that don't exist in an unsigned transaction and run it similarly to the example above without having to re-write everything.

Are you attempting to use eth-tester with py-evm? Because if not, none of this actually touches py-evm. So I'm curious about what the py-evm inquiry is here.

**Comment by Pet3ris** [comment]
I see, really appreciate the clarification. I definitely still had `gas`, `gasPrice` and other arguments in there and it worked well previously but stopped working with type 2 transactions. I'll try stripping out those arguments to see if I can make `py-evm` route it to the type 2 validator and not check the `v` argument and hopefully it will work.

This is what I was doing to make it work pre-london:

```python
  transaction = {
      "to": tx["to"],
      "gas": tx["gas"],
      "gasPrice": tx["gasPrice"],
      "value": tx["value"],
      "nonce": tx["nonce"],
  }
  if "data" in tx:
      transaction["data"] = tx["data"]
  if "input" in tx:
      transaction["data"] = tx["input"]
```

Because these are mainnet transactions, unfortunately I don't have access to the keys so not able to sign them directly.

Yeah I'm sending the transaction to `py-evm` under the hood.
