### ISSUE TITLE
Support hardhat's `console.log`

### ISSUE THREAD

**Issue by yihuang** [ethereum/py-evm#2059]
We did a monkey patch to support `console.log(...)` in py-evm: https://github.com/mpc-poker/prototype/blob/main/pyevm-pokerclient/pokerclient/console_log.py#L396
Not sure is it ok to merge it to upstream.

**Comment by carver** [comment]
project is gone. Presumably spam

**Comment by yihuang** [comment]
> project is gone. Presumably spam

not spam, it's just goes private now ;D
