### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by kclowes** [ethereum/py-evm#2071]
### What is wrong?

py-evm doesn't support Python 3.10. There was a change in the C API in Python 3.10 that we're running into. From the [docs](https://docs.python.org/3/whatsnew/3.10.html#id2): 

> The PY_SSIZE_T_CLEAN macro must now be defined to use [PyArg_ParseTuple()](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTuple) and [Py_BuildValue()](https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue) formats which use #: es#, et#, s#, u#, y#, z#, U# and Z#.]

[Here](https://app.circleci.com/pipelines/github/ethereum/py-evm/2115/workflows/d035f6b4-68f8-4268-9206-288601f1eb36/jobs/158022) is a link to the failed test run. The error message is: `SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats`.

### How can it be fixed

I believe this change needs to happen in https://github.com/ethereum/ethash where the `mkbytes_cache` function is defined. Then we'll need a release and to pull the release in here.

**Comment by fselmo** [comment]
closed by #2088
