### ISSUE TITLE
Update fixture tests to latest version

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#208]
### What is wrong?

The transaction tests in the JSON fixture tests have been updated to include versions that can be run against each set of fork rules.

### How can it be fixed

Update the `fixtures` submodule to this commit:

https://github.com/ethereum/tests/commit/47b09f42c0681548a00da5ab1c98808b368af49a

Update the tests in `tests/json-fixtures/test_transactions.py` to configure the proper VM and run the tests against all of the VMs.  The state tests can serve as an example of how to implement this structure.

**Comment by cburgdorf** [comment]
This was long done
