### ISSUE TITLE
Add `isort`

### ISSUE THREAD

**Issue by pacrob** [ethereum/py-evm#2094]
### What is wrong?

Imports are not sorted.

### How can it be fixed

Add `isort` to the linting process.

**Comment by ketan3108** [comment]
Hi @pacrob , I would like to contribute in this issue . Can you please elaborate in which all files it needs to be implemented ?

**Comment by pacrob** [comment]
isort is part of our linting process, so would apply to most of the files in the repo. You can read more about it [here](https://pycqa.github.io/isort/). For implementation, you can use [web3.py](https://github.com/ethereum/web3.py) as an example.

**Comment by pacrob** [comment]
Closed by #2099
