### ISSUE TITLE
error: no commands supplied

### ISSUE THREAD

**Issue by jimmycchan** [ethereum/py-evm#2181]
### What happened?

python setup.py                                 

/home/kali/Desktop/py-evm/venv/lib/python3.11/site-packages/setuptools/dist.py:508: InformationOnly: Normalizing '0.10.1-beta.1' to '0.10.1b1'
  self.metadata.version = self._normalize_version(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

Why this error?

**Comment by pacrob** [comment]
Calling `setup.py` directly is deprecated. I'm not sure what you're trying to do exactly but I'll direct you to our [Discord](https://discord.gg/GHryRvPB84) for help with usage questions.

If you do find a problem with the lib itself, please open a new issue with more information.
