### ISSUE TITLE
Implement merkle proof verification

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#220]
The LightChain has a method to fetch proofs but currently there's no way to verify those. We need that

**Comment by pipermerriam** [comment]
This *might* actually belong in the [`py-trie`](https://github.com/ethereum/py-trie) codebase but tracking it here for now is fine, or even implementing it here and then migrating it to that codebase is fine.

**Comment by gsalgado** [comment]
Implemented and py-trie: https://github.com/ethereum/py-trie/commit/1c4fbbe080ddf51a439cd596098dead17fb78638
