### ISSUE TITLE
Add a transaction by hash lookup

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#228]
Need to support a transaction lookup by hash for the json-rpc method `eth_getTransactionByHash`.

First impression for an approach:
- add transactions to the key-value store (even pending transactions should be retrievable)
- key = hash, value = transaction root & index (so that we can reuse logic/data in `chaindb.get_block_transactions` and don't store the whole transaction twice in the db)
- need to add transactions in these scenarios
  - import block
  - create transaction locally
  - ?

Alternatives:
- Store the transaction body once with a key of the transaction hash, and store the transaction hash under the key= transaction root & index (the reverse of the suggestion above, since transaction lookup by hash might be more common and the cost of a double lookup might be high)

Open questions
- some kind of garbage cleanup for pending transactions that never get included in a block

**Comment by carver** [comment]
@pipermerriam said:
> Let's do the naive approach and store a mapping from txn to block hash (record when mining)

**Comment by pipermerriam** [comment]
Other options to be considered

- just store a direct `txn_hash -> transaction` lookup (this still leaves us needing to know what block a transaction was included in).
- something fancier like keeping a bloom filter for every chunk of N blocks such that the storage costs are sub-linear
- whatever go-ethereum is doing.

**Comment by carver** [comment]
Closed by #260
