### ISSUE TITLE
error on installation in python 2.x and 3.x

### ISSUE THREAD

**Issue by cmaliwal** [ethereum/py-evm#243]
```
pip install py-evm
Collecting py-evm
  Using cached py-evm-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1XqPJD/py-evm/setup.py", line 11, in <module>
        readme = open(os.path.join(DIR, 'README.md')).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-1XqPJD/py-evm/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1XqPJD/py-evm/
```

**Comment by pipermerriam** [comment]
You'll need to specify an exact version or pass in the `--pre` flag to pip.

```bash
pip install py-evm==0.2.0-alpha.7
pip install --pre py-evm
```

**Comment by cmaliwal** [comment]
@pipermerriam , Thanks for the response.

One more thing : 

looks like `pyethapp`  is being replaxced by `py-evm` .
is it right ?

**Comment by pipermerriam** [comment]
We haven't actually formally announced the `pyethapp` replacement yet.

More accurately, `pyethereum` is to `py-evm` as `pyethapp` is to `????`.

We'll be releasing the actual python based ethereum node under it's own name to keep the evm implementation independent from the actual python based ethereum node (which is built on top of py-evm).
