### ISSUE TITLE
Add a new `Configurable` base class

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#245]
### What is wrong?

One of the standard patterns that has developed in this codebase is classes which can be configured.

```python
class VM(object):
    @classmethod
    def configure(cls,
                  name=None,
                  **overrides):
        if name is None:
            name = cls.__name__

        for key in overrides:
            if not hasattr(cls, key):
                raise TypeError(
                    "The VM.configure cannot set attributes that are not "
                    "already present on the base class.  The attribute `{0}` was "
                    "not found on the base class `{1}`".format(key, cls)
                )
        return type(name, (cls,), overrides)
```

This pattern is found in:

- `evm.rlp.blocks.BaseBlock`
- `evm.vm.base.VM`
- `evm.chains.chain.Chain`

As well as in the not yet merged `evm.computation.Computation` and `evm.vm.vm_state.VMState` from #244 

### How can it be fixed

Create a new base class that contains this functionality `evm.utils.datatypes.Configurable` which implements a standard implementation of this `configure` method.   Then modify all of the classes which implement this pattern to instead inherit from this base class.

**Comment by pipermerriam** [comment]
ping @njgheorghita 

This is probably something you could turn around.

**Comment by njgheorghita** [comment]
![giphy 43](https://user-images.githubusercontent.com/9753150/34964869-106ab7aa-fa0d-11e7-8cfa-0127e482c62e.gif)
