### ISSUE TITLE
Interaction between shard chain client and main chain node

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#258]
### What is wrong?
Let's discuss where/when the `ShardChain` object or other objects would call VMC handler.

Some known cases:
1. CLI: the validators would call `deposit` or `withdraw` functions.
2. Shard chain clients need to watch the main chain VMC state **all the time**.
    * The `add_header` log would trigger shard chain clients to update their head collation.
    * Validators have to call `get_eligible_proposer` periodically to check if they are the sampled collator.
3. Before `create_collation` algorithm  (looks like would be implemented in `ShardVM`), the validators need to have some main chain data of `period_start_prevhash`.
3. During `create_collation` algorithm, it requires calling `fetch_candidate_head` to get data from VMC.
4. After `create_collation` algorithm, the collator would call `add_header` function.

### How can it be fixed
TBD

**Comment by hwwhww** [comment]
@mhchia  Would you mind filling this ticket?

**Comment by hwwhww** [comment]
I realized that it's better to focus on how/when/where do the interaction between shard chain client and main chain node, so I updated the title and content of this issue.

**Comment by hwwhww** [comment]
I use some user stories to describe the requirements/functionality and some possible procedures that related to main chain, and there may be *other better mechanisms* to achieve the same goals. (I don’t intend to introduce any new development model into our work, just try to make it intelligible and the user stories may help us to figure out the basic function of the shard clients.)

None of the high-level stuff should be started implementing immediately, but I believe that having a clear picture could benefit the low-level implementation too.

The following doc is still in discussion. Thank @mhchia for reviewing. Any feedback is highly appreciated.

---

## The User Types

### 1. Regular shard client
* Request archival nodes for witness data 
* Types
    1. Validators (Collator)
        * Shuffling depends on VMC
    2. Only watching specific shards

### 2. Archival shard node
* Regular clients + Watching all shards + Storing archive data

### 3. Main chain full node
* Don’t need to mine, just sync with the main chain
* Provide RPC interface

> p.s. we don’t discuss the light client now.


## Communication Approaches

* **[JSON-RPC]**: the shard client calls main chain full node
* **[P2P]**: the Sharding Wire Protocol

## User Stories

### Story 1: The validator needs to have a tool to manage the keystore

### Story 2: The shard client user can deposit on VMC to become a validator
* **[UX]** Trigger **deposit procedure** on CLI;
* **deposit procedure**
	* **[JSON-RPC]** Send the `deposit-tx` to VMC;
	* **[JSON-RPC]** Use log filter to get the execution result - `the_validator_index`;
	* Store the `validator_index` to the profile.

### Story 3: The shard client validator can withdraw from VMC
* **[UX]** Trigger **withdraw procedure** on CLI;
* **withdraw procedure**
	* Get the `validator_index` from the profile;
	* **[JSON-RPC]** Send the `withdraw-tx` to VMC;
	* **[JSON-RPC]** Use log filter to get the execution result - `is_success` or not.
	
### Story 4: The shard regular node and the archival shard node needs to follow the status of VMC
* Get the latest collation header information from VMC:
	* **[JSON-RPC]** Use log filter to watch the `CollationAdded` log from `add_header` function of VMC for the shard that the client’s watching for (in the local `watching` list);
	* **[P2P]** If there’s a new collation in VMC, try to download the collation.
* On receiving a new collation, apply the fork choice rule with the collation info from VMC.

### Story 5: The shard validator needs to be ready to build the collation and then build the collation.
* The shard validator needs to make the message call  `get_eligible_proposor` to check if they are the collator periodically:
    * **[Polling JSON-RPC]** Ask the main chain via message-call;
	    * Now the `SHARD_COUNT` is 100, if we need to poll with 100 times / 14s? (14s is the average block time)
		    * *Or* maybe we can register a callback function doing this to the block filter in web3.py?

                ```python
                def callback(vmc):
                    valcode_addr = vmc.call(params).get_eligible_proposer(shard_id, period)
                    if valcode_addr == my_address:
                        # I am collator, do something
                ```
* If the validator calls `get_eligible_proposer` and finds itself to be the collator (has the permission to propose collation):
	* Add the given `shard_id` in local `watching` list;
	* Do P2P Discovery on the shard chain;
	* `CREATE_COLLATION` - see [sharing/doc.md](https://github.com/ethereum/sharding/blob/develop/docs/doc.md) for detailed procedure, the following steps could be in parallel:
		* [fetch_candidate_head](https://github.com/ethereum/py-evm/pull/265) will apply `getNextLog`;
			* **[JSON-RPC]**  Use log filter to query `CollationAdded` logs.
		* **[P2P]** Download the collation from archival shard nodes;
		* **[JSON-RPC]** Before executing txs, the shard client needs some information from main chain:
			1. *256-previous-main-chain-blockhashes*;
			2. the block header of the `period_start_prevhash` block to provide the blockchain information opcodes in VM.
		 * Transaction-gathering
			 * **[P2P]** Get the available transactions
		 * Apply transactions and finalize the collation
		 * Broadcast the collation
			 * **[P2P]** Broadcast to shard chain via Wire Protocol;
			 * **[JSON-RPC]** Broadcast to main chain via sending `add_header` transaction.

**Comment by vbuterin** [comment]
> Story 4: The shard regular node and the archival shard node needs to follow the status of VMC

You also need to handle the possibility of a reorg on the main chain, so blocks (and therefore `CollationAdded` logs) getting reverted.

> Do P2P Discovery on the shard chain;

Note that for v1, if we want to simplify this part we can just do everything over one p2p network. Creating a p2p network where you can reliably do discovery on any of the shard sub-channels within a few seconds may be nontrivial.

> Now the SHARD_COUNT is 100, if we need to poll with 100 times / 14s? (14s is the average block time)

If this is really that bad for efficiency, then we could add to the valmgr contract a multi-poll option where you do one call and it checks the eligible proposer on all the shards.

> fetch_candidate_head will apply getNextLog;

Technically, it's `guess_head` that you want to do here, not `fetch_candidate_head`. `fetch_candidate_head` is a method that just outputs a possible head; `guess_head` _uses_ `fetch_candidate_head` but then tries to check that block's ancestors

> [JSON-RPC] Before executing txs, the shard client needs some information from main chain:
256-previous-main-chain-blockhashes;

Note that this is required not just to make your own collation, but also to verify previous collations as part of `guess_head`.
