### ISSUE TITLE
Deduplication of `Message.gas_price` and `Message.origin`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#262]
### What is wrong?

The `Message.gas_price` and `Message.origin` are copied for every level of computation during VM execution, despite them remaining *constant* for the entire context of the VM execution.

It would be nice to remove this duplication in favor of having these values stored in *one* location.

Also see: `sighash` from https://github.com/ethereum/py-evm/pull/259/files

### How can it be fixed

Implement a `TransactionContext` object, similar to the `ExecutionContext` object introduced in #273 

This would be an object that we treat as immutable which houses information like `gas_price`, and `sighash` for the in-progress sharding work.

Since the info for this object will change over time with changes to the VM rules we should use the following API to allow for changing out the class which contains this data.

```
# vm_state.py

class VMState:
    transaction_context_class = None  # must be set in individual VMState classes

    @classmethod
    def get_transaction_context_class(cls):
        # error check to be sure it's set
        return self.transaction_context_class
```

Then, within the `VMState.execute_transaction` implementation, after the `message` instance is created, we should also generate the transaction context instance.

Then, we modify `vm_state.get_computation` to take both `message` and `transaction_context` as arguments.   The `transaction_context` should be stored on the `Computation` object.  When child computations are spawned, this object should be passed into those instances.

Any opcodes which previously accessed values from the `Message` which now reside on the `TransactionContext` object will need to be updated.

**Comment by pipermerriam** [comment]
@gsalgado got any ideas on this one?

**Comment by gsalgado** [comment]
I've had a look at that code and couldn't think of anything other than what you suggest, but I'm not very familiar with that area of the code. I'll sleep on it and maybe I'll come up with something...

**Comment by pipermerriam** [comment]
With respect to #273 

The `BlockInfo` object there holds *constants* that are true for the entire execution context of a block.  We could follow the same pattern and introduce a `TransactionInfo` object that mirrors this for data that is constant through the execution of a transaction.

**Comment by pipermerriam** [comment]
@lrettig this would be a good issue for you to look into.

**Comment by lrettig** [comment]
Do we want to include `message.is_static` here as well? Per https://github.com/ethereum/EIPs/blob/master/EIPS/eip-214.md, this appears to be static in sub-calls.
