### ISSUE TITLE
Implement gas estimation

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#264]
### What is wrong?

We need to implement gas estimation for the JSON-RPC interface.

An ideal gas estimation API should take into account the following.

- total gas used isn't always right due to gas refunds.
- transactions can alter execution flow based on the txn gas.

### How can it be fixed

This should be implemented using a swappable backend API.  Accurate gas estimations are likely to be computationally expensive where-as naive estimations based on gas used are likely to work for most use cases and should be computationally cheap.

The API can be something as simple as a function which takes `VM` instance and a `Transaction` instance and returns the gas estimation.  It *might* be appropriate to include this as an API on the `Chain` and `VM` as `Chain.estimate_transaction_gas()` and `VM.estimate_transaction_gas()`

#### Strategies

We should first implement a `PeekGasUsedStrategy` which uses the peek gas usage

1. run the computation with the gas limit set at the full gas limit for the next pending block.
2. return the `computation.gas_meter.start_gas - computation.gas_metea.gas_remaining` for the outer computation.

Then we should implement what I believe is the current strategy used by go-ethereum which starts with running the transaction using the gas limit for the next pending block and then performs a binary search, re-running the transaction at each level of the search until it finds the threshold for which the transaction succeeds/fails.

> Note that the binary search can be performed at a higher granularity than 1 gas.  From @carver comment, a 1024 granularity should produce approximately a 2x speedup.

**Comment by carver** [comment]
> run the computation with a high gas limit (I think geth uses 50000000) .

FWIW, the [json-rpc spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas) says:
> If no gas limit is specified geth uses the **block gas limit from the pending block as an upper bound**. As a result the returned estimate might not be enough to executed the call/transaction when the amount of gas is higher than the pending block gas limit.

---

I think it's implied, but just to be specific about the binary search: I assume we don't need precision down to the single gas.
> perform a binary search, re-running the transaction at each level of the search until it finds the threshold for which the transaction succeeds/fails.

Getting within, say 1024 gas seems sufficient, and would save ~10 evaluations per estimate.
Starting from a limit of ~8 Mgas per block, that is ~2x speedup from the ~23 evaluations needed to estimate to the 1 gas precision.

**Comment by pipermerriam** [comment]
Thanks, I updated the spec to reflect the gas limit and the granularity.

**Comment by carver** [comment]
I'll take this on, at least the framework. While working on web3 & eth-tester, another thing became apparent: if the block that you want to test against has no gas left in the block, then the current approach becomes impossible. You run out of gas while executing.

I think the best approach is to spawn a new block from your point of interest (an old block, the latest block, or even on top of the pending block). It will not have any transactions, and so will have plenty of gas space in the block for running estimations.

**Comment by carver** [comment]
I've got the code ready, but it is only compatible with #260 so I'll wait for that merge before pushing and entering the Travis queue.

**Comment by pipermerriam** [comment]
Did you link to the wrong thing?  #260 is an issue (not PR)

**Comment by carver** [comment]
@pipermerriam huh? It is a PR

**Comment by pipermerriam** [comment]
I have no idea what I was looking at.  Disregard.
