### ISSUE TITLE
Tasks with Vyper

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#266]
For sharding implementation and testing, we may need some help from Vyper team. 🐍
I listed some tasks that we need to coordinate with Vyper team for follow-up.

1. New opcodes (TBD: do we need a sharding branch in Vyper?)
    * `CREATE2`  #224
    * `PAYGAS`  #234
    * `SIGHASH`  #226 

2. `access_list` generator
    * TODO: write VIP

3. VMC compatible issue
    * Need https://github.com/ethereum/vyper/issues/629: VIP: Standardize type conversions

**Comment by jannikluhn** [comment]
See also https://github.com/ethereum/vyper/issues/632

**Comment by hwwhww** [comment]
deactivate
