### ISSUE TITLE
Remove `is_stateless` flag

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#268]
### What is wrong?

There's an `is_stateless` in `VM` configuration now: 
https://github.com/ethereum/py-evm/blob/4f476908dff42e290c15fc4cfb6a3c5e65e37dfe/evm/vm/base.py#L98-L127

In `is_stateless` mode, the `block` will be deeply copied and the get the result `block` from `VMState` with updated header and transactions. And in the non-stateless mode (the old route), the state transition result would be updated in `VM`.

### How can it be fixed

1. Remove the `is_stateless is False` route.
2. Modify `Chain.apply_transaction` to update the local vm state before returning the `computation` object.

**Comment by hwwhww** [comment]
@pipermerriam  
In the previous PR review feedback, you pointed out that we should **modify Chain.apply_transaction to update the local vm state before returning the computation object**.

1. Do you mean that updating `Chain.header` in `apply_transaction`?

**Chain.apply_transaction(transaction**
```python
    def apply_transaction(self, transaction):
        """
        Apply the transaction to the current head block of the Chain.
        """
        vm = self.get_vm()
        computation, block = vm.apply_transaction(transaction)
        state_trie_data = computation.vm_state.access_logs.writes

+       self.header = block.header

        return computation
```

2. Some of the methods of `Chain` haven't been used in lightclient, I wonder what is the use case of `Chain.apply_transaction(transaction)`?

**Comment by pipermerriam** [comment]
> you pointed out that we should modify **Chain.apply_transaction to update the local vm state before returning the computation object.**

I **think** what I was referring to was that *previously* the `Chain` class's state root would get updated *automatically*, but with the recent changes, that is no longer the case.  So, the `Chain` object now needs to manually update the state root since it no longer happens automatically.

**Comment by hwwhww** [comment]
> I **think** what I was referring to was that *previously* the `Chain` class's state root would get updated *automatically*, but with the recent changes, that is no longer the case.  So, the `Chain` object now needs to manually update the state root since it no longer happens automatically.

Thanks for making it clear! So previously, the `state_root` is passed with `Chain.header` to `Chain.get_vm()` immutably. When `Chain.apply_transaction(transaction)` calls `VM.apply_transaction(transaction)` and updates the `VM.header`, it also updates `Chain.header`. 

I think the line I added can solve this. Will add a test.

**Comment by hwwhww** [comment]
> For testing, full nodes, and mining are the use cases I can think of.  It's a mid/low level interface for building blocks incrementally.

The function of building block method may be similar to `VM.create_block(transaction_packages, prev_hashes, coinbase, parent_header)`, but will be non-stateless version (no witness in `transaction_packages`) for full node. The input parameter may be the whole transactions pool of the client.

Do you think this kind of functions should be implemented in `Chain` object? For stateless clients + current codebase, it looks easier to build a block via `vm_state.apply_transaction(transaction, block)` function because it requires switching `vm_state.chaindb` to `witness_db` during applying transaction. I think it's okay to implement in totally different ways for stateless & non-stateless nodes, just want to bring it up to discuss some possible strategies.
