### ISSUE TITLE
Decouple blockchain opcodes and state mutable data

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#270]
### What is wrong?

1. Decouple `VMState.block_header` and `VMState` properties (`timestamp, block_number, difficulty, and gas_limit)`, because shard chains use `period_start_prevhash` block properties of main chain in contracts, but `VMState.state_db()` should use the `state_root` of `VMState.collation_header` to build the state root trie.
2. Note that only `COINBASE` opcode refers to the shard coinbase.

### How can it be fixed

1. As v suggested, implement a simple `BlockInfo` class:

    ```python
    class BlockInfo():
        # For shard chain, refer to the shard coinbase.
        _coinbase = None

        # For shard chian, block data of period_start_prevhash.
        _timestamp = None
        _number = None
        _difficulty = None
        _gas_limit = None
        _prev_headers = None

        def __init__(
                self,
                coinbase,
                timestamp,
                number,
                difficulty,
                gas_limit,
                prev_headers):
            self._coinbase = coinbase
            self._timestamp = timestamp
            self._number = number
            self._difficulty = difficulty
            self._gas_limit = gas_limit
            self._prev_headers = prev_headers

        @property
        def coinbase(self):
            return self._coinbase

        @property
        def timestamp(self):
            return self._timestamp

        @property
        def number(self):
            return self._number

        @property
        def difficulty(self):
            return self._difficulty

        @property
        def gas_limit(self):
            return self._gas_limit

        @property
        def prev_headers(self):
            return self._prev_headers
    ```

2. Pass  `block_info` to initialize `VMState`.
3. Assign `coinbase` separately.
4. Arrange/Refactor the temporary mutable data during state transition: 
	* Part of  the given block’s header from `VMState.__init__(..., block_header, ...)` and replace with  `VMState.apply_transaction(...,block,...)`
		* `state_root`
		* `gas_used` - update in `VMState.make_receipt`
	* `receipts`  - now is part of `VMState`
	* **Solution 1**: generalize `VMState.block_header` to `VMState.header` and make sure it’s compatible for both `BlockHeader` and `CollationHeader` structure.
	* **Solution 2**:
		1. pass `block` to `VMState.make_receipt` function so that we just use the given block to maintain `gas_used`.
		2. pass `state_root` and `receipts` to `VMState.__init__(...,state_root, receipts, ...)`
	* **Solution 3**: apply Vitalik’s suggestion to arrange these variables to a new simple `StateObj` structure. And the apply transaction would become:

    ```python
    # In create_block level function
    # state_obj: previous state_obj or new StateObj

    state_obj = StateObj(
        state_root=state_obj.state_root,
        gas_used=state_obj.gas_used,
        receipts=state_obj.receipts,
    )
    block_info = BlockInfo(
        coinbase=block.header.coinbase,    # or collation.coinbase
        timestamp=block.header.timestamp,
        number=block.header.number,
        difficulty=block.header.difficulty,
        gas_limit=block.header.gas_limit,
        prev_headers=prev_headers,
    )
    vm_state = cls.get_state_class()(
        chaindb=witness_db,
        state_obj=state_obj,
        block_info=block_info,
    )
    computation, result_block, _ = vm_state.apply_transaction(
        transaction=transaction,
        block=block,
        is_stateless=True,
    )
    state_obj = computation.vm_state.state_obj
    ```
    I'd like to try **Solution 2** first because I want keep the `VMState` simple, and I'm also fine with **Solution 3**.

5. Check with @pipermerriam : do we design that `VMState` only be used for handling the “transaction level” state transition? Or we would introduce “block level” function like `VMState.apply_block` function?
 
6. About uncle validation, there are: 
	* `Chain.mine_block` or `Chain.import_block(block)`
	    └─ `Chain.validate_block(block)`
			    └─ `Chain.validate_uncles(block)`
	*  `VM.pack_block(block)`
	    └─  `VMState.validate_block(block)`
			    └─`VMState.validate_uncle(block, uncle)`

    Regarding (5):
    * If `VMState` only handle “transaction level” state transition:
	    * The  `VMState.validate_block(block)` should be move to `VM`.
	    * With this change, we can also modify `VMState.prev_header` to simpler `VMState.prev_hashes`.
    * If `VMState` also handle “block level” state transition, should we move some more functions from `VM` to `VMState`?

**Comment by pipermerriam** [comment]
@hwwhww great writeup.  Here are my thoughts which I hope are helpful.

- I like having an `apply_block` function but it's not clear to me where it should live.  `VM` or `VMState` both strike me as suitable candidates and until I see it in action I don't think I'll know.
- I like having `VMState` be transaction level and `VM` be block level, but that doesn't mean it's the right API.  If that separation feels clean that would be an indicator to me that it's the right architecture.  If it feels cumbersome and it doesn't feel like it actually simplifies anything then it's probably wrong.
- I'd like to avoid anything like initializing an object and then *patching* the `coinbase` onto it later to support sharding.  That type of thing seems indicative of an architecture problem that should be sorted out.

I hope this is enough to get you moving.  When there's code I can look at I suspect I'll have an easier time giving better feedback.

**Comment by hwwhww** [comment]
@pipermerriam thank you for sharing your thoughts.
* I’d like to try to move `validate_block` to `VM` since `VM.import_block(block)` and  `VM.mine_block()` are in `VM` now.
* Sorry for the unclear expression, yes, the `coinbase` should only be set in initialization method.
