### ISSUE TITLE
Base class for asyncio services to avoid duplication

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#280]
### What is wrong?

We already have a few asyncio-based services that run in an infinite loop (e.g. `LightChain`, `DiscoveryProtocol`) and they all provide an `async def run()` method that loops forever, together with some logic to cause the loop to stop and return from `run()`. 

### How can it be fixed

This (and possibly other bits) should be moved into a base class so that we don't have to duplicate the code in all our asyncio services

**Comment by gsalgado** [comment]
May be worth considering some of the generic cancellation mechanisms described in https://vorpus.org/blog/timeouts-and-cancellation-for-humans, specially this:

> Trio's cancel scopes then piggy-back on this system: we declare that whenever you see an await, that's a place where you might have to handle a Cancelled exception – either because it's a call to one of Trio's primitives which directly check for cancellation, or because it's a call to a function that indirectly calls one of those primitives, and thus might see a Cancelled exception come bubbling out.

**Comment by carver** [comment]
Note to self: review if `start` in evm/rpc/ipc.py should use whatever generalization gets added.

**Comment by gsalgado** [comment]
While working on #334 I ended up spending a lot of time debugging service termination/cleanup issues, so I'll try to find some time to work on this sooner rather than later

**Comment by gsalgado** [comment]
#345 should either make this irrelevant or pretty straightforward to implement

**Comment by gsalgado** [comment]
Fixed by implementing `p2p.BaseService`
