### ISSUE TITLE
Need a persistent way to keep track of peer details/reputation

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#282]
### What is wrong?

Our `PeerPool` currently provides no API for its clients to choose the _best_  peer when they need to make a request, so they end up picking one randomly.

The `PeerPool` also has to either use a hard-coded list of peers or run the discovery bootstrap from scratch every time it is initialized since we don't have a persistent DB with peer details (i.e. peer ID, chain ID, genesis hash, supported sub-protocols, latest hash/difficulty)

### How can it be fixed

We need to keep peer details/reputation in a persistent store so that the `PeerPool` can reuse known good peers from previous runs as well as provide APIs for clients to pick the _best_ peer for a request.

I'm not sure how to define _best_ here, but I believe a weighted round-robin based on a peer's latency would be a good start. Although we may also need a way to restrict the choices only to those peers that are at least at a certain block height/td

**Comment by pipermerriam** [comment]
Closing in favor of https://github.com/ethereum/py-evm/issues/757#issuecomment-391693228 since it fleshes out the implementation details a bit.  Will update with anything from here that isn't covered.

**Comment by gsalgado** [comment]
Should've been closed already, as per previous comment
