### ISSUE TITLE
Compatibility / Functioning of py-evm chain/storage

### ISSUE THREAD

**Issue by step21** [ethereum/py-evm#294]
* py-evm Version: 0.6.0
* OS: Linux Ubuntu 16.04.3
* Python Version (python --version):
2.7.12 and 3.5
* Environment (output of `pip freeze`):
aiohttp==2.3.1
apipkg==1.4
asn1crypto==0.24.0
async-generator==1.9
async-lru==0.1.0
async-timeout==2.0.0
attrs==17.4.0
bumpversion==0.5.3
cffi==1.11.4
chardet==3.0.4
coverage==4.4.2
cryptography==2.1.4
cytoolz==0.9.0
eth-bloom==0.5.2
eth-keys==0.1.0b3
eth-utils==0.7.4
execnet==1.5.0
flake8==3.5.0
hypothesis==3.30.0
idna==2.6
leveldb==0.194
mccabe==0.6.1
multidict==4.0.0
pluggy==0.6.0
py==1.5.2
py-ecc==1.4.2
-e git+git@github.com:pipermerriam/py-evm.git@8bc9a42943730fd09e29695dab0c2a1e869e913f#egg=py_evm
pycodestyle==2.3.1
pycparser==2.18
pyethash==0.1.27
pyflakes==1.6.0
pysha3==1.0.2
pytest==3.1.2
pytest-asyncio==0.8.0
pytest-cov==2.5.1
pytest-logging==2015.11.4
pytest-xdist==1.18.1
rlp==0.4.7
six==1.11.0
toolz==0.9.0
tox==2.7.0
trie==1.1.0
typing==3.6.2
virtualenv==15.1.0
yarl==1.1.0

### What is wrong?
When trying to read an existing chain (made with go-ethereum) based on the examples (http://py-evm.readthedocs.io/en/latest/quickstart.html#accessing-an-existing-chain-database) I get `evm.exceptions.CanonicalHeadNotFound: No canonical head set for this chain` - ideally, this should still work as far as I understand. Though it is a bit hard to verify when comparing the codebases, whether these should be compatible or not (apparently not). While it is my understanding that things like rlp and trie should be implemented in a compatible way, I found it kind of hard to check that and even more so how this then gets saved on disk.
Getting back to the issue at hand, so it seems that py-evm sets `b'v1:canonical_head_hash'`as default and on lookups sets this properly. At least this `b'v1:canonical_head_hash'` or similar I couldn't find anywhere else in other implementations. (confirmed by checking almost empty leveldbs manually)
So the main issue/question is - is there a way around this, so as to use for example py-evm's chain/state/etc logic and maybe also leveldb/db parts but use it to access geth chains or others? Could this maybe even be a configuration option? (ofc geth also must somehow keep track of the head, but def doesn't have a special, unencoded db key for it as far as I can tell)

Complete output:
```chain = MainnetChain(chaindb)Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/py-evm/evm/chains/chain.py", line 68, in __init__
    self.header = self.create_header_from_parent(self.get_canonical_head())
  File "/home/user/py-evm/evm/chains/chain.py", line 160, in get_canonical_head
    return self.chaindb.get_canonical_head()
  File "/home/user/py-evm/evm/db/chain.py", line 58, in get_canonical_head
    raise CanonicalHeadNotFound("No canonical head set for this chain")
evm.exceptions.CanonicalHeadNotFound: No canonical head set for this chain
```

**Comment by gsalgado** [comment]
The chaindb format used by geth is not compatible with ours, so this is indeed not expected to work.

**Comment by pipermerriam** [comment]
It would be possible for someone to write a DB  backend that used the geth database schema but that's outside of the scope of this project.

**Comment by step21** [comment]
Ok thanks for clarifying
