### ISSUE TITLE
Read-only property decorator

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#336]
### What is wrong?
See https://github.com/ethereum/py-evm/pull/273#discussion_r161866203
In `ExecutionContext` (evm.vm.execution_context) and `TransactionContext` (#327), it's better to write an explicit decorator `read_only_property` or `immutable_property` which includes a setter that raises such an `AttributeError` when someone try to modify these properties.

### How can it be fixed
1. Write the decorator in [eth-utils](https://github.com/ethereum/eth-utils) or a new file `evm/utils/decorators.py`
2. Update the decorator of `ExecutionContext` and `TransactionContext`

**Comment by pipermerriam** [comment]
we can vendor this locally for now and migrate it to `eth-utils` *eventually*

**Comment by jannikluhn** [comment]
I think this is the default already if no setter is defined explicitly:

```
In [1]: class Test:
   ...:     @property
   ...:     def read_only(self):
   ...:         return 5
   ...:     

In [2]: Test().read_only
Out[2]: 5

In [3]: Test().read_only = 5
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-95b62475fe87> in <module>()
----> 1 Test().read_only = 5

AttributeError: can't set attribute
```

**Comment by pipermerriam** [comment]
Well lookey there, thanks for correcting my *incorrect* version of the behavior of `@property`.  Looks like we can maintain the current implementations and close this issue since it's already default behavior.  cc @lrettig @hwwhww since I lied to you two.
