### ISSUE TITLE
BaseChainDB no longer supports a header-only DB

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#337]
### What is wrong?

`BaseChainDB._set_as_canonical_chain_head()` now expects the DB to contain transactions as well, and that breaks `LightChain` since it only syncs headers.

When there's a chain reorg, that method will try to [remove tx lookups from the DB](https://github.com/ethereum/py-evm/blob/master/evm/db/chain.py#L108-L110), but that crashes because we have no transactions in the DB

**Comment by gsalgado** [comment]
Looks like this was introduced in #260

**Comment by pipermerriam** [comment]
Thoughts on using different chaindb classes for light and full chains?

**Comment by pipermerriam** [comment]
cc @carver

**Comment by carver** [comment]
> Thoughts on using different chaindb classes for light and full chains?

First impression: :+1: . This seems like the first of many things that will be different about what they expect to have in storage.

If this was the only difference, I might say we just make this a `remove_or_noop`. There's not really a great reason to crash here when trying to delete a missing transaction, besides catching errors early in debugging.

**Comment by gsalgado** [comment]
We might want to take it a step further and have one DB containing just the headers and another one containing just the block bodies/receipts. That would potentially allow us to have a single header DB for both light/full modes. Also, given the way full-node sync should be implemented (i.e. fetching/validating header chains before fetching the block bodies), having separate DBs would make it easier for us to parallelize parts of it

**Comment by carver** [comment]
> We might want to take it a step further and have one DB containing just the headers and another one containing just the block bodies/receipts

Seems reasonable. Which invites the question: how do we coordinate both databases when the canonical chain head updates?

Some options:
1. Introduce a pub/sub where the `ChainBodyDB` can subscribe to events in the `ChainHeaderDB` (like "block header A is no longer in canonical chain", or "block header B is now in the canonical chain"). This might be useful elsewhere
1. Have the `ChainBodyDB` be a subclass of a `ChainHeaderDB`, hooking in some logic for canonical head updates (and wherever else becomes apparent)
3. Add two orchestration classes where we would extract a lot of the current canonical logic: a headers-only and a headers-plus-transaction one
4. Change approach from proactively caching canonical transaction locations to looking them up on demand. Presumably, this is too slow to use in practice without caching. Effective caching would probably need one of the above solutions.

At first glance, I'm in favor of 1. It seems like a clean separation, and other objects might benefit from this feature. One downside is that we don't follow that subscription pattern anywhere else that I've seen.

**Comment by gsalgado** [comment]
We now have separate `HeaderDB` and `ChainDB` classes, and the former's `_set_as_canonical_chain_head()` method doesn't expect the DB to contain transactions in case of a chain reorg, so this is fixed
