### ISSUE TITLE
Consider abreviation for `computation` variable

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#343]
### What is wrong?

The variable `computation` is kind of long.  Maybe there's a nice abbreviation or alternate name we could use?

### How can it be fixed

Consider the following

- use `comp` instead of `computation` for instance names
- rename class to `Execution` and use `exc` as variable name. (maybe too similar to built-in `exec`)
- anyone got any better ideas.

This also may not be worth the visual *optimization*

Alternate approach would be to instead make more shortcut methods on the `Computation` class

```python
computation.gas_meter.consume_gas(child_msg_gas_fee, reason=self.mnemonic)
# becomes...
computation.consume_gas(child_msg_gas_fee, reason=self.mnemonic)
# or maybe shortcut accessors...
computation.gm.consume_gas(child_msg_gas_fee, reason=self.mnemonic)
```

**Comment by carver** [comment]
> anyone got any better ideas.

I haven't picked one in here that I love yet, but ideas to keep the train rolling...

Things that maybe convey the idea of a single execution run, like:
- `job`
- `task`
- `run`

One approach would be to prefix it with `Virtual*` (as in Ethereum **Virtual** Machine), like:
- `vexec` (`VirtualExecution`)
- `vcompute` (`VirtualExecution`)
- `vcomp`
- `vjob`
- `vtask`
- `vrun`

... but I don't love the compression of the word to one letter, for learnability.

Maybe just `run` is my favorite of these.

**Comment by pipermerriam** [comment]
closing in favor of #362 which should shorten these statements.
