### ISSUE TITLE
Re-organize networking code for Trinity

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#361]
### What is wrong?

Currently, all of the networking code lives under `evm.p2p`.  The *long* term plan is to split the core DevP2P components from this code into a separate library (probably the existing `devp2p` python library).  To prepare for this, we should start drawing firmer lines between the different sections of code that currently live in this repository.

1. Py-EVM code: deals specifically with the EVM
2. DevP2P code: deals with the generic DevP2P protocol
3. Trinity code: deals with running an Ethereum node over the DevP2P protocol using the `py-evm` EVM.

### How can it be fixed

Perform the following code re-organization.  This should be done in multiple steps to keep the pull requests smaller.

1. Everything from `evm.p2p` to a new root level module `devp2p`
2. Move everything from the new `devp2p` module which is not *strictly* DevP2P protocol code to `trinity.p2p`
3. Find *any* imports in either of these sections of code which import from `evm.utils.*` and change them to use their own local utilities, **or** migrate the utility to `eth-utils` so it can be shared.

**Comment by pipermerriam** [comment]
@gsalgado I also think that means we move most of the work you're currently doing over to the `trinity` branch (or maybe better, go ahead and merge `trinity` into master and just build from that common base.

**Comment by gsalgado** [comment]
When you say DevP2P I guess you mean the base-protocol (https://github.com/ethereum/wiki/wiki/%C3%90%CE%9EVp2p-Wire-Protocol) plus anything related to discovery and sub-protocols as well? If so, I'd prefer to call the new root-level subpackage just `p2p`.

Also, I think in trinity it'd make more sense to have separate, meaningfully named subpackages for the individual p2p services (e.g. `trinity.lightchain`, `trinity.sync`, etc), but it might make sense to start with everything under `trinity.p2p`

**Comment by pipermerriam** [comment]
> I'd prefer to call the new root-level subpackage just `p2p`

👍 

> Also, I think in trinity it'd make more sense to have separate, meaningfully named subpackages

👍 

Once we get #379 merged would you like to do that re-org?
