### ISSUE TITLE
Remove `evm.utils.padding` in favor of built-in ljust and rjust methods.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#388]
### What is wrong?

The utility functions `pad_left` and `pad_right` are not necessary and are likely causing a performance hit.

### How can it be fixed

Replace all usage of them with calls to `str.ljust` `str.rjust`, `bytes.ljust`, `bytes.rjust`.

**Comment by cburgdorf** [comment]
I think this can be closed now (forgot to close it from the commit message)
