### ISSUE TITLE
Add tx.hash global variable

### ISSUE THREAD

**Issue by k06a** [ethereum/py-evm#401]
### What is wrong?

Sometimes it is needed to store hash of the transaction in blockchain. I am sure it is possible to make `tx.hash` available in EVM.

### How can it be fixed

Add `tx.hash` support to EVM

**Comment by pipermerriam** [comment]
@k06a this isn't the correct place for this type of request.

Changes to the core protocol are done via the EIP process here: https://github.com/ethereum/EIPs

I believe this functionality is already part of the sharding roadmap.

**Comment by k06a** [comment]
@pipermerriam thanks: https://github.com/ethereum/EIPs/issues/901
