### ISSUE TITLE
failed to install py-evm after running pip install -e . -r requirements-dev.txt

### ISSUE THREAD

**Issue by sunxivincent** [ethereum/py-evm#408]
* py-evm Version: 0.2.0-alpha.11
* OS: osx
* Python Version (python --version): 2.7
* Environment (output of `pip freeze`):

### What is wrong?

Collecting hypothesis==3.44.26 (from -r requirements-dev.txt (line 3))
  Using cached hypothesis-3.44.26.tar.gz
    Complete output from command python setup.py egg_info:
    /private/var/folders/g7/hhzznhfx6rzczkdnnfrx90hw0000gn/T/pip-build-5XDM3o/hypothesis/setup.py:39: UserWarning: This version of setuptools is too old to correctly store conditional dependencies in binary wheels.  For more info, see:  https://hynek.me/articles/conditional-python-dependencies/
      'This version of setuptools is too old to correctly store '
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in hypothesis setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34; python_version=="2.7" at ; python_version=="2.7"

### How can it be fixed

Sounds like I have multiple python versions on my mac, and some of dependencies in requirement-dev.txt is only compatible with python3

Try: `python3 -m pip install -e . -r requirements-dev.txt` works for me

**Comment by pipermerriam** [comment]
I'd highly suggest using a virtual environment rather than your global python.  Some quick googling should find you plenty of resources on how to set them up.
