### ISSUE TITLE
Allow `VM` class to specify what `ChainDB` class it uses.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#410]
### What is wrong?

In #350 the differences between shard collations and blocks required a bit of a hack to make the `persist_block_to_db` to work with both blocks and collations.

While we *could* try to sufficiently abstract the API, such as separating things into `persist_block_to_db` and `persist_collation_to_db`, I don't believe this is the right solution.  Eventually, we are bound to have either blocks, transactions, or something that require more such logic forks to handle.

Py-EVM has so far largely avoided these types of logic forks in it's code by sufficiently abstracting the overall API so that underlying implementations can be swapped out within each VM.

### How can it be fixed

I think that the `Chain` class should be modified so that it takes a backend `DB` type, and then delegates to the active `VM` for the appropriate block number to get the `ChainDB`.  Each `VM` class can then define their own `ChainDB` class.  Then the `ShardVM` class can expose it's own `ChainDB` class with modified `persist_block_to_db` method.

**Comment by pipermerriam** [comment]
Here's the *usage* profile I see for the `ChainDB`

- The `VM` class: 
  - `get_block_uncles`
  - `get_block_transactoins`
  - `get_receipts`
  - `persist_trie_data_dict_to_db`
  - `get_block_header_by_hash`
  - `get_pending_transaction`
  - `clear`
- The `VMState` class:
  - `get_state_db`
  - `exists`
  - `snapshot`
  - `revert`
  - `commit`
 - The `Chain` class:
  - `get_transaction_index`
  - `get_transaction_by_index`
  - `add_pending_transaction`
  - `get_block_header_by_hash`
  - `get_canonical_head`
  - `lookup_block_hash`
  - `persist_block_to_db`

High level analysis:

- The `VM` usage mostly is centered around retrieving `Block` data to instantiate blocks.
- The `VMState` is isolated to `snapshot/revert/commit` API and access to the underlying db backend for the state database.
- The `Chain` class deals with the broadest usage, retrieving transaction information, storing blocks/headers, and looking up blocks/headers, as well as the canonical chain information.

**Comment by pipermerriam** [comment]
One way to look at this (but that I'm not sure is correct).

We *might* benefit from isolating our database usage.  

I'm going to define two terms 

- Database Backend: A low level connection to a database.  Currently we only support key/value store based backends.
- Database Adapter: A high level wrapper around a database backend.

In the current code:

- Existing *backends* are the `MemoryDB` and `LevelDB`.
- We have one existing *adapter* which is our `ChainDB` class.

I am proposing that we split up the `ChainDB` into multiple classes.  Initial starting point looks to be trying out an *adapter* for each of `Chain/VM/VMState` since their usage of the current `ChainDB` don't have very much overlap.

**Comment by pipermerriam** [comment]
Now to explore actual usage examples.

### Light Client

The light client needs basic database access to store and retrieve block headers for the canonical chain.  

In order to serve JSON-RPC requests the light client needs to proxy certain `Chain` methods which would normally access the chain database to instead fetch the needed data from peers.  This use case is *orthogonal* to this issue since the abstraction layer to accomplish this is likely to be at the `Chain` object itself since the JSON-RPC server interacts directly with the `Chain` class.

### Full Node

This is the current *default* mode of operation that we're trying to add flexibility to.  Stores everything.

### Stateless client

It's not clear to me exactly what is stored by stateless clients.  Nothing?  Headers?

### Log Shard Clients [https://ethresear.ch/t/log-shards-and-emv-abstraction/747](https://ethresear.ch/t/log-shards-and-emv-abstraction/747]

Since this is currently theoretical and I don't know much about it I'm unable to detail exactly how this fits into our architecture.  It sounds like it's an entirely separate `VM` type with potentially fundamentally different semantics.

**Comment by pipermerriam** [comment]
So, maybe to tie this all together, though I'm not confident that I've got all the pieces right.

- Independent *adapter* implementations for `VM` give internal flexibility with regard to EVM semantics, enabling different logic for dealing with `blocks`, `transactions`, `collations`.
- Independent *adapter* implementations for the `VMState` currently have no direct need that I see, but the implementation looks pretty simple.
- Independent *adapter* implementations for the `Chain` as well as different implementations of the `Chain` class itself *should* enable the Fill/Light/Stateless use cases.

**Comment by pipermerriam** [comment]
This is probably at least tangentially related to https://github.com/ethereum/py-evm/issues/337

**Comment by pipermerriam** [comment]
So far this is turning out interesting and I **think** promising.  The `VMState` object's usage is basically direct database access so it's looking like I may be able to completely eliminate the `snapshot/commit/revert` API as well as moving the API for the account state database to be directly on the `VMState` object.

**Comment by hwwhww** [comment]
**Stateless Node** only stores the "state root" and cache recent data (validated collation headers, data from VMC...) in memory.

**Comment by hwwhww** [comment]
Sorry for that I just went through it carefully. Some preliminary notes for database adapter:

1. `Transaction` and `Blob`:
	* Instead of transactions, the recent design is storing **blobs** as just some binary data.
	*  `CollationHeader` includes `blobs_root` instead of `transaction_root`, copy from @vbuterin: the `blobs_root` is a simple Patricia tree root, where the keys are two bytes: `0x0000`, `0x0001`, `0x0002`, etc; a collation can contain a maximum of 65536 blobs.
	* We don't use any transaction-related functions in Phase 1. But probably will be considered and adapted in Phase 2. Right now we could just don't implement them.
2. `CollationHeader` and `BlockHeader`:
	* Have to rename a lot `block_number` -> `collation_number`/`score` in the adapter...?
	* A refactoring idea: maybe we can make a `number` property in `BlockHeader` class that returns `self.block_number` and make a  `number` property in `CollationHeader` class that returns `self.number` or `self.score`, then modify all `block_header.block_number` usage to `block_header.number`?

**Comment by pipermerriam** [comment]
@hwwhww I think your changes to the `*Header` API would be a good abstraction/improvement.  We *could* also do away with the `block_` and `collation_` prefixes and just change the base field names.  I think the fact that the object is a `Block` or `Collation` is sufficient justification to remove those prefixes.

**Comment by pipermerriam** [comment]
Replaced by https://github.com/ethereum/py-evm/issues/507
