### ISSUE TITLE
Look into removing Collation.transaction_fee_sum from

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#412]
### What is wrong?

The `Collation` object currently uses a stateful and mutation based mechanism for storing the total transaction fee.

https://github.com/jannikluhn/py-evm/blob/65d7b24d718b1aa1238ba72a385d16baa93498e7/evm/vm/forks/sharding/collations.py#L29

It would be better if we can find a way to track that value and expose it in the appropriate place(s) in a more explicit way.

### How can it be fixed

Need to investigate.

**Comment by hwwhww** [comment]
deactivate
