### ISSUE TITLE
Minimal testnet for sharding

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#419]
### What is wrong?

We need the minimal P2P code to do the following.

- Maintain connections to peers, probably from a hardcoded list or at least a list of bootnodes.
- Gossip protocol to pass around new blocks/collations.
- ???

### How can it be fixed

Starting point should probably be

- `p2p.lightchain.LightChain` 
- `p2p.peer.LESPeer`
- `p2p.les`

We'll need to implement `Command` classes for a minimal subset of commands needed to pass around blocks.  Looking at the existing commands we will probably need a set of commands loosely as follows.

- `Status` - For initial handshake and connecting to *useful* peers.
- `Announce` - For letting peers know they have a new block.
- `GetXXX` and `XXX` for things like requesting and sending blocks or headers.

Then we'll need to implement a `Protocol` class to wrap these commands, similar to `LESProtocol`.

And then finally, a `ShardChain` class like `LightChain` which uses the protocol to join the network, find suitable peers, learn the appropraite chain of blocks that it should sync with and then request the blocks and headers and do whatever is needed with them.

**Comment by pipermerriam** [comment]
@hwwhww Yes, I think this could be practical.  Are we talking about purely using block headers? or do you want blocks too?  Right now the `LightChain` implementation will sync the full header chain so part 1 is done.

Exporting the data could be done any number of ways with some simple scripting.

ping @gsalgado right now we appear to have code to connect to external peers, but am I correct that we would still need to implement something that listens for incoming connections?

**Comment by gsalgado** [comment]
That's correct, we need to listen to incoming connections and use `p2p.auth.HandshakeResponder` to establish the shared secrets and get a `Peer` instance that can then perform the base- and sub-proto handshakes. The tests in `test_auth.py` show how to use `HandshakeResponder`

**Comment by pipermerriam** [comment]
@gsalgado 

Further questions about how this would be setup.

I'm assuming we'd need to use [`asyncio.start_server`](https://docs.python.org/3.5/library/asyncio-stream.html#asyncio.start_server) to bind something to listen on the desired address/port.  That returns a `reader/writer` pair.  From what I can tell the `reader/writer` pair can then be used to initialize a `Peer` instance.  What I'm not sure of is where the `HandshakeInitiator` comes into play.

I feel like I'm missing something because `p2p.auth.handshake` seems to do what we want, but only when we *know* what the enode is already.

Sorry if I'm being dense, but I'm having trouble understanding how `HandshakeInitiator` would be used with any of the mechanisms that I currently understand for starting a server or listening for incoming connections.

**Comment by gsalgado** [comment]
For the `Peer` we need the reader/writer plus the shared secrets established as part of the auth handshake. What we have currently is `p2p.auth.handshake`, which uses `HandshakeInitiator` to connect to a remote peer, send the initial auth msg, read the auth ack and, from those two msgs, derive the shared secrets. What we are missing is a new function (`p2p.auth.receive_handshake()`, maybe) that uses a `HandshakeResponder` to accept a connection, read the auth init msg, reply with a auth ack and derive the shared secrets from those two msgs

**Comment by gsalgado** [comment]
Actually, it seems like the new `receive_handshake()` function could be the callback passed to `asyncio.start_server`; it'd take a reader/writer and do the following: 

1. Read the auth init msg
2. Decrypt/decode it (`HandshakeResponder.decode_authentication()` does that, but it will have to be moved into a standalone function, I believe) and from that get the remote's pubkey
3. Create a `HandshakeResponder` instance using the remote's pubkey and its address (obtained via `writer.get_extra_info()`, it seems) 
4. Call `HandshakeResponder.create_auth_ack_message()` to create the reply
5. Send that to the remote
6. Call `HandshakeResponder.derive_shared_secrets()` and use that to create a `Peer` instance

**Comment by pipermerriam** [comment]
> Actually, it seems like the new `receive_handshake()` function could be the callback

I assume that's in one of your currently pending pull requests?

**Comment by hwwhww** [comment]
@pipermerriam 
> Are we talking about purely using block headers? or do you want blocks too?

Just block headers.

**Comment by gsalgado** [comment]
> Actually, it seems like the new receive_handshake() function could be the callback
>> I assume that's in one of your currently pending pull requests?

Nope, that's the function name I'd suggested in the previous comment, to handle the auth handshake for incoming peer connections

**Comment by hwwhww** [comment]
@gsalgado @pipermerriam Am I right that what we *need* for sharding minimal testnet includes implementing `receive_handshake()` function? If this is a task that research team could do, would you give us some recommended reading resource and create a new ticket for that? Thank you.

**Comment by pipermerriam** [comment]
@hwwhww yes, I believe all of that is correct.

I believe that @gsalgado 's [comment from a bit higher up in this issue](https://github.com/ethereum/py-evm/issues/419#issuecomment-369374563) gives a pretty decent outline of what is to be done.  I'll recap here.

* create a new stand-alone function `receive_handshake(reader, writer, ...)`
* the `receive_handshake` function will be used as the `client_connected_cb` parameter for the [`asyncio.start_server`](https://docs.python.org/3.5/library/asyncio-stream.html#asyncio.start_server) function.
* Use the `reader` to read the auth init message.
* Use `HandshakeResponder.decode_authentication(auth_init_message)` on the auth init message.
* Some extra changes are likely required to allow retrieval of the remote's public key from the auth init message.
* extract the remote's address via the [`writer.get_extra_info()`](https://docs.python.org/3.5/library/asyncio-stream.html#asyncio.StreamWriter.get_extra_info) API.
* Use `HandshakeResponder.create_auth_ack_message()` to create a reply for the handshake.
* Use the `writer` to send the reply to the remote.
* Use `HandshakeResponder.derive_shared_secrets()` and use the return values to instantiate a `Peer` instance.

@gsalgado where do you think this orchestration code should live.  I assume in the `PeerPool`?

**Comment by pipermerriam** [comment]
lets call it something like `PeerListener`

**Comment by gsalgado** [comment]
I suggested `p2p.Server` because I envisioned it'd be the main service, responsible for orchestrating all others. It'd accept incoming peer connections but also run the `DiscoveryProtocol`, tell `PeerPool` to connect to more nodes when necessary, and pass that pool to other services like `LightChain` or the new `ChainSyncer`

**Comment by jamesray1** [comment]
Given that light clients won't be implemented until phase 3 with the new roadmap I would say that this issue can be labeled phase 3.

**Comment by hwwhww** [comment]
@jamesray1 This issue is not for implementing sharding state light client. It's for the basic phase 1 testnet.

**Comment by jamesray1** [comment]
OK, I guess when I looked at the proposal `p2p.lightchain.LightChain`, `p2p.peer.LESPeer`, `p2p.les`, `LESProtocol` I thought it might have something to do with light clients, but I don't know anything about these.
