### ISSUE TITLE
Implement blobs related structure

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#436]
### What is wrong?
In the new spec, the state execution layer and validity layer are separated. To further emphasize this, we refer to what would previously be referred to as transactions as “blobs”. The validity layer simply treats them as *binary data* and does not attempt to assign them any meaning; assigning meaning is entirely the responsibility of the state execution layer.

### How can it be fixed

[Blob serialization](https://ethresear.ch/t/blob-serialisation/1705/)

~~1. The `blobs_root` is a **simple Patricia tree root**, where the **keys are two bytes**: 0x0000, 0x0001, 0x0002, etc; a collation can contain a maximum of 65536 blobs.~~ **[TBD]**
2. blobs don't need to be broadcasted over P2P network for now.

**Comment by jannikluhn** [comment]
A simple way to do this would be to introduce a `BlobCollation` class similar to the `Collation` class, but using the field type `binary` for `transactions` and `witness_nodes`. `Collation` could inherit from `BlockCollation` (sharing the header access helpers like `shard_id` etc.).

**Comment by hwwhww** [comment]
#555
