### ISSUE TITLE
STUB: Add protection against eclipse attacks in Trinity.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#440]
See: http://www.cs.bu.edu/~goldbe/projects/eclipseEth

### What is wrong?

We should build in some basic protections against eclipse attacks.

### How can it be fixed

- Require that a certain percentage of the peer connections are initiated as outgoing connection requests.
    - Configuration parameter that sets required number of connections that originate from a dial-out connection
    - Configuration parameter that sets the ratio of allowed dial-in to dial-out connections.
- Ensure that the IP addresses for peer connections are not all to the same IP address.
    - Configuration parameter that sets the maximum number of connections to a single IP address that are allowed, default to something like 3.

**Comment by gsalgado** [comment]
FWIW, currently we only support outgoing connections

**Comment by pipermerriam** [comment]
And am I correct that you're looking to implement at least the base framework for listening to incoming connections in conjunction with other things you're working on?  I seem to recall this being stated somewhere but I can't seem to find it.

Also, linking https://github.com/ethereum/py-evm/issues/419 as it talks about how this should be implemented.

**Comment by gsalgado** [comment]
Soon I should start working on the main p2p service (`p2p.Server`), but not yet for listening to incoming connections

**Comment by njgheorghita** [comment]
Started working on a basic `p2p.Server` that listens to incoming peers and handles the initial auth/p2p handshakes

**Comment by goldbe** [comment]
Hi guys.  I'm one of the eclipse paper authors.  I have not audited your client, but I wanted to make sure that you implement one of the most important countermeasures, which is to make sure that a client does not make all its connections to node IDs that are hosted at the same IP.  This is countermeasure 2 in our paper.  http://www.cs.bu.edu/~goldbe/projects/eclipseEth

**Comment by pipermerriam** [comment]
@goldbe thanks for highlighting this for us.  I've updated the main issue description to explicitly include this.

**Comment by goldbe** [comment]
Thanks. It would be good to limit the number of node IDs that map to the same IP in the peer tables as well. I would prefer a limit of one node ID per one IP

**Comment by gsalgado** [comment]
We now have a limit of at most 2 connections for any given IP address, as well as a inbound/outbound ratio of 0.75
