### ISSUE TITLE
Type Annotations for the `evm` module

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#444]
### What is wrong?

We should have full type annotations for the EVM module.

### How can it be fixed

This should probably be done incrementally in roughly the following steps.

- `evm.utils.*`
- `evm.db.*`
- `evm.computation` and the related `evm.vm.gas_meter`, `evm.vm.stack`, etc
- `evm.logic` and `evm.precompiles`
- `evm.estimators`
- `evm.vm.base` and `evm.vm.forks` and `evm.consensus`
- `evm.chains`
- whatever is left.

**Comment by gsalgado** [comment]
Should we merge this with #132? There's some useful info there about tools that can be used to help generate the type hints

**Comment by cburgdorf** [comment]
I tried monkeytype but couldn't get it to work properly so I ended up adding them manually so far. I plan to continue working on this.

**Comment by pipermerriam** [comment]
Didn't remember #132 existing.  Closing in favor of that.
