### ISSUE TITLE
Improve CancelToken API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#447]
### What is wrong?

I am finding the API for using `CancelToken` awkward and somewhat cumbersome.

- Always have to import both `CancelToken` and `wait_with_token`
- Many `wait_with_token` statements in a function body become repetitive.

### How can it be fixed

I see three options.

#### 1. Add `CancelToken.wait_with` method

This would be a wrapper around the `wait_with_token` API that makes it so you only have to pass in the `*futures` argument.

Benefit of this one is that it reduces the necessary imports to only the `CancelToken`

#### 2. Add a `Cancelable` mixin base class.

```python
class Cancelable:
    CancelToken = CancelToken  # convenience API?
    cancel_token: CancelToken = None
    
    def __init__(self, cancel_token):
        self.cancel_token = cancel_token

    async def wait_with_token(self, *futures, **kwargs):
        return await wait_with_token(*futures, token=self.cancel_token, **kwargs)
```

Benefit of this one is that you only have to import the `Cancellable` class.  However, this approach only helps use of `CancelToken` in classes.

#### 3. Make `wait_with_token` curry-able.

This makes use of cancel tokens in *functional* code easier to use.  A function body with *many* `await` statements can create a local curried `wait_with_token` and then call it only with the `*futures`.

This approach doesn't alleviate the need to import both the `CancelToken` and `wait_with_token` function.

**Comment by pipermerriam** [comment]
I'm in favor of doing 1 and 3.  @gsalgado I know you pushed back on 1.  How strongly do you feel about that?

**Comment by gsalgado** [comment]
A `CancelToken.wait_with()` method just doesn't feel natural to me, and I don't think it's a big deal to have an extra name imported together with `CancelToken`, but I could certainly live with that 

As for making it curry-able, I don't see the point as ISTM we don't have any functions/methods calling it multiple times

**Comment by pipermerriam** [comment]
@gsalgado Most of these concerns went away when I redid my recent pull request.

Turns out currying `wait_for_token` doesn't work because it immediately evaluates once `token` has been provided since `*futures` is optional.

Closing for now.
