### ISSUE TITLE
Add `loop` parameter to `wait_with_token` API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#448]
### What is wrong?

If I understand correctly:

[This call to `asyncio.wait`](https://github.com/ethereum/py-evm/blob/fa07b6819c7f597bb5aa7ae13614d881a84081ae/p2p/cancel_token.py#L84) will used the *default* event loop if no loop parameter is provided

https://docs.python.org/3.5/library/asyncio-task.html#asyncio.wait

If that is the case, then in our tests, won't the cancel token be running in a different loop than other things that are using our local `event_loop` fixture?

### How can it be fixed

Change the `wait_with_token` API needs to accept an extra optional `loop` parameter.

**Comment by gsalgado** [comment]
The `event_loop` fixture also installs that as the default event loop, so if you create the CancelToken inside a test (or fixture) that depends on the `event_loop` fixture, it will use the same one, like I described in https://github.com/ethereum/py-evm/pull/382#discussion_r173425077

**Comment by pipermerriam** [comment]
This was another issue that went away when I refactored my recent PR.  closing for now.
