### ISSUE TITLE
Make use of the `abc` module for base classes

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#466]
### What is wrong?

There are a number of base classes in both the `evm` and `trinity` codebases which implement methods which **must** be implemented when subclassed.

Python provides mechanisms for this pattern which enforce these requirements in the [`abc`](https://docs.python.org/3.5/library/abc.html) module.

### How can it be fixed

Across the various base classes, use the [`abc.abstractmethod`](https://docs.python.org/3.5/library/abc.html#abc.abstractmethod) API on any of the methods which raise `NotImplementedError`.

**Comment by cburgdorf** [comment]
Coming https://github.com/ethereum/py-evm/pull/467
