### ISSUE TITLE
JournalDB makes ChainDB.persist_trie_data_dict() up to 20x slower on a fully populated DB

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#495]
`ChainDB.persist_trie_data_dict()` is yet another bottleneck I've found when running a full-node sync: it takes between 3 to 9 seconds to persist a batch of (128) bodies or (256) receipts, and most of that was spent on `JournalDB.set()`, which does a `wrapped_db.get()` before setting the new value.

This is specially problematic when performing a chain sync, but at the same a chain sync doesn't need a journaled DB, so maybe in that case we can just use a custom, non-journaled, DB class? Can anybody think of possible problems with that? Also, does that mean we'd need to extend trinity's DB-serving process to also offer a non-journaled chaindb?

**Comment by pipermerriam** [comment]
I'm planning on writing it up later today, but we worked out the architecture for an overhaul of the db system that py-evm uses.  I *think* that this is going to give us a good path to fix this in a *good* way.  In the meantime you should feel free to implement whatever fix you need to bypass the journal.
