### ISSUE TITLE
Create new eth_typing lib

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#499]
This is a follow up of [this discussion](https://github.com/ethereum/py-evm/pull/459#discussion_r174853525)

### What is wrong?

We currently have many API that take/return `bytes` [1] where we could really benefit from stricter type checking by introducing [`NewType`](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#newtypes)s. In short a `NewType` lets us create a substitute for a type (e.g. `miles` for `int`) so that an API that takes `miles` as inputs can not be called with any arbitrary `int` instead. These kind of errors already killed NASA missions when `km` and `miles` where [accidentally twisted](http://edition.cnn.com/TECH/space/9909/30/mars.metric.02/)

[1] also applies to other types (e.g. `int`) but is mostly problematic with `bytes` in our case

### How can it be fixed

1. Create NewTypes for types that we currently define to loosely (mostly `bytes` but we should check also our usage of `int`)

2. Put them in a new library `eth_typings` that can be distributed on `pypi` so that it can be shared across different projects

**Comment by pipermerriam** [comment]
I think we should create this locally here in the py-evm repo and then migrate it to something separate once we have something semi-stable.  Feel free to do this as a new top-level module `eth_typing` like `evm/p2p/trinity`.
