### ISSUE TITLE
Delete most of the sharding code

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#508]
### What is wrong?

Most of the code that's been implemented for sharding is no longer part of the phase 1 roadmap.  Given that the future of this code is uncertain and we have no direct use for it now....

### How can it be fixed

Lets delete as much of it as seems reasonable.

**Comment by hwwhww** [comment]
1. The things that I suppose would be implemented in eWASM or the Python interpreter?
	1. `ShardingAccountStateDB`
	2. account list restrictions
	3. part of account abstraction?
2. #452 : move SMC and SMCHandler to sharding repo 
3. Remove all:
	1. `Shard` (`evm/shard.py`)
	2. `ShardVM` (`evm/vm/shard_vm.py`)
	3. `ShardingVM` (`evm/vm/forks/sharding`)
	4. `TrackedDB` and the the usage
4. Considering:
	1. `ShardingAccountStateDB` (@pipermerriam  your call)
	2. `evm/auxiliary` (seems no harm?)

**Comment by pipermerriam** [comment]
Less about harm of leaving things in and more about whether they are used.  I know *most* of that stuff will be used eventually, but given the ease of resurrecting it, I'd prefer to take the route of delete and then revive later when we need it again.

**Comment by carver** [comment]
> I know most of that stuff will be used eventually, but given the ease of resurrecting it, I'd prefer to take the route of delete and then revive later when we need it again.

I think we are better off finding a different way to indicate that the sharding code is dormant for the next phase:

We are setting ourselves up to do a lot of work when reviving the code, because the internal APIs are so fluid. I expect that it's going to be like the recent merge of the sharding branch, all over again. Instead, if we leave the code in, the tests will catch it when internal API changes break the dormant sharding code.

**Comment by jannikluhn** [comment]
I guess it depends on what would take more effort:

- keeping the sharding code running at all times through the API changes
- resurrecting it once

Intuitively I'd say resurrecting once is easier, especially given that both the py-EVM and the sharding state execution model (-> alternative execution engines) will change. Also I would be surprised if there are no additional EVM changes coming. But I wasn't involved in the recent merges, so this is just my gut feeling, with no practical experience to justify it.

**Comment by hwwhww** [comment]
closed via #518
