### ISSUE TITLE
Both `VM` and `State` classes define a `block_class`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#513]
### What is wrong?

Both the `VM` and `State` (aka `VMState`) objects implement a `block_class` or (`_block_class` from the `VM`) property and API.  There should only be one `block_class` defined for a given VM ruleset.

### How can it be fixed

- Remove the `block_class` API from the `VM` class and change all usage to delegate to the `State` class API.
- Change the `State` class to have a `get_block_class()` which is a `classmethod` for retrieval of the class instead of directly accessing it via the attribute.

**Comment by cburgdorf** [comment]
Took a stab at it here https://github.com/ethereum/py-evm/pull/516
