### ISSUE TITLE
Got a LevelDBError (Too many open files) when running a state sync

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#524]
I saw this in the logs when running the StateDownloader on a fully synced ropsten DB (28 GB). We may be leaking file descriptors somewhere, or it may just be that we need to pass a higher `max_open_files` when creating a `LevelDB` database

```
Traceback (most recent call last):
  File "/home/salgado/src/py-evm/p2p/state.py", line 65, in handle_peer
    await self._handle_peer(peer)
  File "/home/salgado/src/py-evm/p2p/state.py", line 90, in _handle_peer
    self.scheduler.process([(node_key, node)])
  File "/home/salgado/virtualenvs/pyevm/lib/python3.6/site-packages/trie-1.3.1-py3.6.egg/trie/sync.py", line 168, in process
    self.commit(request)
  File "/home/salgado/virtualenvs/pyevm/lib/python3.6/site-packages/trie-1.3.1-py3.6.egg/trie/sync.py", line 184, in commit
    self.db[keccak(request.data)] = request.data
  File "/home/salgado/src/py-evm/evm/db/backends/base.py", line 40, in __setitem__
    return self.set(key, value)
  File "/home/salgado/src/py-evm/evm/db/backends/level.py", line 25, in set
    self.db.Put(key, value)
leveldb.LevelDBError: IO error: /home/salgado/.local/share/trinity/ropsten-full-3/1375440.ldb: Too many open files
```

geth doesn't seem to change the default for max_open_files so ideally we shouldn't have to either. Maybe this won't happen once we've fixed #523

**Comment by pipermerriam** [comment]
I'm inclined to think we're leaking file descriptors, potentially when we kick processor intensive things out to an executor in a different process?  It's possible that multiprocessing is pickling/unpickling something with a reference to the db, which *might* cause a dangling file descriptor somehow?

However, bumping the `max_open_files` in `LevelDB`, assuming the default is sufficiently low could at least be an intermediate fix to see if the problem arises again.

**Comment by gsalgado** [comment]
`LevelDB` instances cannot be pickled -- I found that out when trying to run parts of the p2p code in a `ProcessPoolExecutor` and had to refactor our code so now what gets passed between processes are just `p2p.Command`, `evm.rlp.Receipt` or `evm.rlp.BlockHeader`

**Comment by pipermerriam** [comment]
It looks like the default is `1000` for max open files.  Seems like a strong indicator that we have dangling file descriptors somewhere.

**Comment by pipermerriam** [comment]
goss, the python leveldb library is at least a year old.  I know rocksdb is supposed to be similar if not better.  Are there other options we should look into switching to? Cost of switching should be very low.

**Comment by gsalgado** [comment]
Haven't seen this ever again, so closing for now
