### ISSUE TITLE
ChainSyncer: add tx lookup entries to DB

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#529]
### What is wrong?

Currently (when doing a fast sync) it generates the transactions trie manually (using `make_trie_root_and_nodes()`) and persists that to the DB, so we don't get the DB entries that allow us to lookup the block of a given tx by hash.

### How can it be fixed

We could redesign `ChainSyncer` so that it uses `ChainDB.persist_block()`, but that would certainly affect performance significantly because that trie generation would be done in the DB process and that is quite expensive.

Another option would be to duplicate (or refactor) parts of `persist_block()` so that `ChainSyncer` calls `ChainDB._add_transaction_to_canonical_chain()` after it calls `ChainDB.persist_header()`

**Comment by pipermerriam** [comment]
linking to #507 as I think this topic might be tangentially related.

The DB process could be modified to only expose the base level DB connection which would allow the `ChainSyncer` to use it's own adapter or re-use an existing adapter while still giving us control over where the actual processing happens.

**Comment by gsalgado** [comment]
Actually, `persist_block()` only generates the trie to validate the transaction_root. If we [move that to a validation method](https://github.com/ethereum/py-evm/pull/533) we should be able to use `persist_block()` in ChainSyncer without too much of a performance penalty
