### ISSUE TITLE
Implement Shard class

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#530]
### What is wrong?
After the old codes are removed, we can start to implement the `Shard` class which is similar to `Chain` class.

### How can it be fixed
Implementing `evm/chains/shard.py` and it's NOT an inheritance/implementation of the `BaseChain` now.

**Comment by hwwhww** [comment]
Actually this ticket was aim to the `Chain` object, not `db`.

**Comment by jannikluhn** [comment]
Oops, sorry for that

**Comment by hwwhww** [comment]
close via #570
