### ISSUE TITLE
Missing dependencies after fresh install

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#538]
* py-evm Version: `0.2.0-alpha.14`
* OS: linux
* Python Version (python --version): `3.6.4`
* Environment (output of `pip freeze`): 

```
aiohttp==2.3.10
apipkg==1.4
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==2.0.1
attrs==17.4.0
backcall==0.1.0
bumpversion==0.5.3
cffi==1.11.5
chardet==3.0.4
coverage==4.5.1
cryptography==2.2.2
cytoolz==0.9.0.1
decorator==4.2.1
eth-bloom==1.0.0
eth-hash==0.1.2
eth-keys==0.2.0b3
eth-utils==1.0.2
execnet==1.5.0
flake8==3.5.0
hypothesis==3.44.26
idna==2.6
idna-ssl==1.0.1
ipython==6.3.1
ipython-genutils==0.2.0
jedi==0.11.1
mccabe==0.6.1
multidict==4.1.0
mypy==0.580
parso==0.1.1
pexpect==4.4.0
pickleshare==0.7.4
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.3
py-ecc==1.4.2
-e git+https://github.com/ethereum/py-evm.git@3cadfc739b469bb4c24324a32851eb5a7b28a9d2#egg=py_evm
pycodestyle==2.3.1
pycparser==2.18
pycryptodome==3.6.0
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pytest==3.1.2
pytest-asyncio==0.8.0
pytest-cov==2.5.1
pytest-logging==2015.11.4
pytest-xdist==1.18.1
rlp==0.6.0
simplegeneric==0.8.1
six==1.11.0
toolz==0.9.0
tox==2.7.0
traitlets==4.3.2
trie==1.3.2
typed-ast==1.1.0
virtualenv==15.2.0
wcwidth==0.1.7
yarl==1.1.1
```

### What is wrong?

I'm planning to improve the developer guide for py-evm / trinity. I noticed that when I do a fresh clone, create a fresh `virtualenv` and run `pip install -e . -r requirements-dev.txt` I'm left with a system that doesn't have all dependencies installed to run the entire test suite without failures.

So, the TLDR of that issue is that it seems that our current developer guide doesn't leave you with a system that can satisfy all tests and hence isn't complete from a developers perspective.

In particular, at this point we are missing the `leveldb`, `web3`, `pysha3` and potentially other libs.

This happens both on my local system as well as in a fresh `python:3.6` docker container.

It doesn't seem to be a problem on CI though. My naive guess is that the tox setup triggers different installs.

The shortest path (that I'm aware of) to get all tests green is to run:

```
pip install -e .[trinity] -r requirements-dev.txt
pip install pysha3
```

At this point one should have all dependencies installed. 

I just want to double check if running the two commands above is something that is by design and the developer guide should highlight this or if our setup should be adjusted in any way. 

Or, maybe, if I'm just doing it wrong (in which case I really hope I wouldn't be the only person on the planet to run into this).

**Comment by pipermerriam** [comment]
It looks like you can drop this down to a one-liner with `pip install -e .[trinity,p2p] -r requirements-dev.txt`

If we adopt the style that @carver is using now we could trim this down to `pip install -e .[trinity,p2p,dev]`.

see: https://github.com/ethereum/eth-account/blob/master/setup.py#L8-L35

**Comment by cburgdorf** [comment]
Well, in fact if we adopt the [@carver pattern](https://github.com/ethereum/eth-account/blob/master/setup.py#L30-L35) (deliberately making up a new term) we get rid of the `requirements-dev.txt` and are down to just `pip install -e .[dev]` to set up a full dev environment. I like it. Happy to make the change if no one beats me to it.

**Comment by ldct** [comment]
Not sure if this is related, but I did a `pip3 install -r requirements-dev.txt` and still had to install the following packages manually: py_ecc, pyethash, eth_bloom, eth_keys, trie, eth_utils, rlp. For each of them there is code in this repo importing it but I can't find any of these dependencies in `requirements.txt`.

**Comment by cburgdorf** [comment]
Yes, that's related. I'm about to send a PR that fixes this and updates the
developer guide with instructions on how to set up the system.
