### ISSUE TITLE
Minimal sharding protocol

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#539]
# Minimal sharding protocol - the basic sharding committee

Aimed to https://ethresear.ch/t/a-minimal-sharding-protocol-that-may-be-worthwhile-as-a-development-target-now/1650

## What's new

1. No more proposing-collating game.
2. "collator" -> "notary"
3. `Notaries` will sign the collation (more like Casper validators).
4. Constants
    * `COMMITTEE_SIZE` := 135
    * `QUORUM_SIZE` := 90
5. `COMMITTEE_SIZE` **notaries** are sampled per block from the `notaries_pool` per period per shard.
6. No lookahead and no windback in this scheme: notaries are selected at the start of the period, and they only need to download the collation created in that period.

#### Collation
```
[
    header: CollationHeader,
    body: CollationBody
]
```

#### CollationHeader
> Don't need to be broadcasted in the P2P network.
```
[
    shard_id: uint256,
    chunk_root: bytes32
    period: uint256,
    proposer_address: address,
]
```

#### CollationBody
```
We don't really care for now.
```

### SMC
see https://github.com/ethereum/sharding/issues/76

## Proposing-Voting Procedure
1. When the shard clients know block10 hash = 0x1234 (period 2 starts) -> sample `COMMITTEE_SIZE` notaries
    1. **[Proposer]** 
        * creates collation
        * signs collation
        * sends `add_header` tx to SMC
        * broadcasts the collation to shard network
    2. **[Selected notary]**
        - monitors the SMC, looks at the first `HeaderAdded` of the given period -> calculate the collation hash.
        - verifies the data availability of the collation
        - `submit_vote` txs are sent on chain and included in period 2
    3. **[Shard full node]**
        - monitors the SMC, look at the first `HeaderAdded` of the given period -> calculate the collation hash.
        - monitors the SMC, look at the `Vote` logs
            - If the collation gets `QUORUM_SIZE` notaries vote for it, downloads it and accepts it as part of the canonical chain.
            - Else, abandons this collation.

2. When the shard clients know block15 hash = 0x5678 (period 3 starts)
    * repeat it.

## Client Full Syncing Procedure

1. **[Query receipts]** Starts the query from `SMC.deployed_block_number` block and finds the first `HeaderAdded` log of the given shard with the given period. 
2. **[Query receipts]** Calculates the `Vote` logs of the given shard with the given period
3. If voting passed, tries to download the collation body and asks shard chain peers for the collation.
    * **🍵🍵🍵: We just assume it *should* be available, so if the collation unavailable... throw an exception for now?**
    [Vitalik] In practice, there are two ways out. Post-tight-coupling, if this ever happens, the entire main chain from that point, including all collations in other shards, should be thrown out. 

> **🍵🍵🍵: Asking peers for one collation each time is inefficient. Maybe querying a series of collation headers and then asking a series of collation bodies?**
    [Vitalik] Sure, sounds sensible

**Comment by hwwhww** [comment]
Eww, there will be a problem when full sync: before the client calculates the votes, they have to check who are the selected committee members via calling `SMC.get_committee(shard_id, period)`. But by the time, `notary_pool_len` may be already changed because some notaries register or deregister. So the return value from `SMC.get_committee(shard_id, period)` may be different from the real selected committee that was generated right before the period started.

It's similar to https://github.com/ethereum/py-evm/issues/456

**Comment by NIC619** [comment]
IMO the most viable way is to check in `submit_vote` that the voter is qualified.

**Comment by hwwhww** [comment]
Lastest discussion: https://ethresear.ch/t/sharding-phase-1-spec-retired/1407
