### ISSUE TITLE
Setting the log level on Trinity doesn't change log level for p2p/evm

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#552]
### What is wrong?

Please include information like:

If one starts trinity with debug logging enabled (`trinity -l debug`) one does really only see debug messages from trinity but not those that are logged via the p2p or evm layer (these layers remain on log level `info`). 

Considering that trinity is the main user facing software, am I right to assume that we actually do want to see debug messages from p2p/evm if one starts trinity with `-l debug`?

**Comment by pipermerriam** [comment]
Yes, I think it should set the log level for both of the `evm.*` and `p2p.*` logging namespaces.

**Comment by pipermerriam** [comment]
Actually, I'm going to eat my words.

I think for now we can have a mechanism for this, but no, I think that the logging that comes out of running `trinity` should be *largely* restricted to things in the `trintity.*` logging namespace.  However, I think there are some things that currently are in the `p2p.*` namespace that should be in the `trinity.*` namespace.

I don't think anything in the `evm.*` namespace should be effected by trinity logging.

**Comment by cburgdorf** [comment]
Ok, so I'm putting myself into the shoes of a user who wants to run an ethereum node and ended up using `trinity`. The user may not know (and care) how `trinity` is layered what different technologies it uses underneath to accomplish what it does.

Let's consider the user is having trouble to connect to the network. Running `trinity` with `-l debug` I think it would be beneficial to see messages such as the following even though they are technically coming from the `p2p` layer which may be an independent project.

```
09:42:56 DEBUG: Sending msg with cmd_id: 0
09:42:56 DEBUG: Waiting for 32 bytes from <Node(0x7a34@35.227.38.243)>
09:42:56 DEBUG: Waiting for 32 bytes from <Node(0x7a34@35.227.38.243)>
09:42:56 DEBUG: Got msg with cmd_id: 1
09:42:56 DEBUG: Successfully decoded Disconnect (cmd_id=1) msg: {'reason': 4, 'reason_name': 'too_many_peers'}
09:42:56 DEBUG: Could not complete handshake with <Node(0x7a34@35.227.38.243)>: HandshakeFailure('ETHPeer <Node(0x7a34@35.227.38.243)> disconnected before completing handshake: too_many_peers',)
```

**Comment by pipermerriam** [comment]
So my point about some of the `p2p`namespace stuff needing to be `trinity` namespace stuff should cover the majority of this.  For example, the `p2p.peer.LESPeer` uses the logger `p2p.peer.Peer`.  This should really probably be relocated to be under the `trinity` python module and to use a `trinity.` namespaced logger.

This should fix **most** of these, though there may be a few where we *should* explicitly include some `p2p` namespaced logging in the trinity output which we can handle as special cases (like maybe loggers burried deep in the authentication code in the `p2p` module)

**Comment by cburgdorf** [comment]
>This should really probably be relocated to be under the trinity python module and to use a trinity. namespaced logger.

Yep, understand :+1: 

>This should fix most of these, though there may be a few where we should explicitly include some p2p namespaced logging in the trinity output which we can handle as special cases (like maybe loggers burried deep in the authentication code in the p2p module)

Alright, sounds good to me.

**Comment by cburgdorf** [comment]
Should we close that issue then?
