### ISSUE TITLE
Cleanup `evm.utils.numeric`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#568]
### What is wrong?

The `evm.utils.numeric` module could be cleaned up.

### How can it be fixed

- switch to use `eth_utils.int_to_big_endian` and `eth_utils.big_endian_to_int`
- change `int_to_bytes32` to use `value.to_bytes(32, 'big')` but preserve the validation checks.
- remove `int_to_byte` as it doesn't appear to be used anywhere.
- remove `byte_to_int` as it isn't used.
- remove `safe_ord` as it should not be needed anymore.

**Comment by hiteshramani** [comment]
I'll be taking this up and submitting a PR soon.

**Comment by hiteshramani** [comment]
I was going through the methods to be double sure if they're not used anywhere and came across one use of `safe_ord` in `p2p.discovery` which is as follows:

`cmd_id = safe_ord(message[HEAD_SIZE])`

Wanted to be sure if this is not needed anymore?

**Comment by gsalgado** [comment]
> cmd_id = safe_ord(message[HEAD_SIZE])
> Wanted to be sure if this is not needed anymore?

It shouldn't as message should be of type `bytes`, but in order to get rid of safe_ord() there you'll also need to update other methods there to change the type of arguments from `AnyStr` to `bytes`: https://paste.ubuntu.com/p/B9qBPPQNmw/

**Comment by hiteshramani** [comment]
@pipermerriam 
> - switch to use eth_utils.int_to_big_endian and eth_utils.big_endian_to_int

When you say "switch to use" you mean the entire repo needs to use the above rather than the numeric methods, right?

**Comment by hiteshramani** [comment]
I am creating a PR with the rest of  the changes, I will commit the one left as soon as the doubt is clarified.

**Comment by pipermerriam** [comment]
Thanks for the contribution @hiteshramani
