### ISSUE TITLE
Fix corner case in Server

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#574]
link: https://github.com/ethereum/py-evm/pull/496

### What is wrong?

As pointed out by @hwwhww 

https://github.com/njgheorghita/py-evm/blob/647e6eeb31bb511b24b034e5eb2080f1d311eb1d/p2p/server.py#L90

This line will hang indefinitely if authentication is an invalid pre eip-8 auth message as there will be no more bytes to read. 

### How can it be fixed

Probably with a timeout.

**Comment by jannikluhn** [comment]
Same here I guess: https://github.com/ethereum/py-evm/pull/496/files#diff-c9071b8ec03b78dc6c5a5bd48bd5536bR80

**Comment by gsalgado** [comment]
Oh, and we must actually use `wait_with_token()` in both those places

**Comment by hwwhww** [comment]
closed via #583
