### ISSUE TITLE
Use TCP port in Server

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#578]
### What is wrong?

The `p2p.Server` is using the `udp_port` when it **should** be using the `tcp_port`

### How can it be fixed

https://github.com/njgheorghita/py-evm/blob/647e6eeb31bb511b24b034e5eb2080f1d311eb1d/p2p/server.py#L65

Update that section of code to use the `tcp_port`

**Comment by hwwhww** [comment]
Fixed in f6b743d55927dd864ee9e54b9de6d5342a508ca2
