### ISSUE TITLE
Add tests to prove we aren't leaving cruft in the db when things are reverted

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#582]
### What is wrong?

While working on #569 I noticed it is far to easy to accidentally bypass the `JournalDB` altogether and still get the entire test suite to pass. I don't have a definite prove for that yet but it seems we don't have a test that actually tests that we aren't leaving cruft in the database when things are reverted.

I'm adding this issue as a reminder for me to follow up on that.

### How can it be fixed

Add missing tests

**Comment by dylancaponi** [comment]
@cburgdorf I've noticed this issue is over two years old. Has it been implemented? If not, would you mind breaking down the steps or provide advice on how to begin?

**Comment by cburgdorf** [comment]
Hey @dylancaponi happy to hear you want to contribute. To be honest, my memory around this issue isn't very well. I can't break down steps from the top of my head and it's likely that the tests around the journal db have progressed a lot in the past two years.

I guess the general idea was:

1. Make changes in the db
2. Revert the changes
3. Assert that the changes are in fact reverted

The main idea was to ensure we have would notice if we accidentally bypass the `JournalDB` at some point. I would rather close this issue because I really can't tell how much the situation has changed and I certainly can't give the support that justifies this as a *Good First Issue*.
