### ISSUE TITLE
Expand Chain object tests to use all mainnet VM rules

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#597]
### What is wrong?

The tests in `tests/core/chain-object` are all using only the `SpuriousDragonVM`

https://github.com/ethereum/py-evm/blob/48e94db187ed0b6166a6572f499ef624d5f987ce/tests/core/fixtures.py#L13

We really should be running these tests across all of the mainnet VMs.

### How can it be fixed

Change the tests so that they run against each set of VM rules.  This is probably best done by parametrizing the chain fixtures that are used.

**Comment by Bhargavasomu** [comment]
I'm on this.
