### ISSUE TITLE
New JournalDB doesn't seem to persist everything when importing a block

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#606]
With the new `JournalDB`, when I import ropsten block 3072902 (via `Chain.import_block()`), the block's state_root doesn't end up in the underlying DB, although it is present in the journal. That doesn't happen when I use the old `JournalDB`

**Comment by gsalgado** [comment]
Here's something else that seems suspicious: https://github.com/gsalgado/py-evm/blob/journal-messup/evm/tools/fixture_tests.py#L633-L635

**Comment by cburgdorf** [comment]
Oops. So, from the top of my head this is what I think:

- either this means there is a code path that should not use through the `JournalDB` but rather the underlying db directly or, 

- we need a another `persist()` call at some later point to also persist this missed data

- we need to move the existing `persist()` call to some later point in time to include all changes. Currently at is called at the end of every single transaction processing

**Comment by cburgdorf** [comment]
Would it possible to add a test or change an existing test to fail that would have succeeded before? Then I could sprinkle a couple of conditional breakpoints across the code base to identify the part that needs to be fixed.

**Comment by gsalgado** [comment]
https://github.com/ethereum/py-evm/issues/606#issuecomment-384948658

**Comment by cburgdorf** [comment]
Oh, I meant a lookup of a key in the MemoryDB that should exist but doesn't. But yeah, the pending changes there are most likely unintended. But we need to identify the place where they should have been persisted. So far I *assumed* we only hit the `JournalDB` for the transaction processing, hence calling `persist()` at the end of every transaction processing should cut it but this bug seems to indicate there are other changes that either need to be offloaded from the `JournalDB` or need another or moved `persist()` call.

**Comment by gsalgado** [comment]
In that test, any keys from `chain.chaindb.journal_db.journal.latest.keys()` should exist in `chain.chaindb.db`, no?

**Comment by cburgdorf** [comment]
Maybe. But at least I could verify that but looking up one of the keys there and then running that test again against the previous JournalDB and see if it ends up in the MemoryDB. Then I can set a conditional breakpoint to figure out at which code path it would have been written. Unfortunately I'm in a train though and have to head out for my stop.

**Comment by gsalgado** [comment]
So, I've been thinking about the new `JournalDB` and how some `ChainDB` methods use it whereas others use the underlying db directly, and I believe this is not ideal and will probably lead to more issues like this one. How do you guys feel about that? Is there a plan to improve that in the short term?

**Comment by cburgdorf** [comment]
In general I think that separating the parts that need journaling / batching from the parts that do not may not be so bad after all. But I agree that the way the different code paths in `ChainDB` *currently* either use the one or the other isn't the right way and is only in place as a short term solution. I think it would be better if the parts that need journaling / batching are clearly separated.

**Comment by pipermerriam** [comment]
> How do you guys feel about that? Is there a plan to improve that in the short term?

Issue #507 are meant to fully address this stuff but that's more medium term.  @carver can you investigate a bit whether there may be a good short term bandaid for this?

**Comment by gsalgado** [comment]
Ok, found it! In this case we were just not persisting the pending journaled changes at the end of `BaseState.finalize_block()`, but somebody reading that code would not immediately see it is using the `JournalDB` so it is very easy to forget that persist() call

**Comment by cburgdorf** [comment]
@gsalgado can you confirm this works again on latest master so that we can close this?

**Comment by gsalgado** [comment]
Yep, it seems to work!
