### ISSUE TITLE
Circle CI sometimes fails at merge PR step. Needs auto restart.

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#624]
### What is wrong?

We sometimes see this.

![image](https://user-images.githubusercontent.com/521109/39482374-13b1c0b0-4d6f-11e8-92fa-f27c006d55c5.png)

Seems to work after manual restart.

### How can it be fixed

Configure auto retry (1-2 times) for *this particular* build step.

**Comment by carver** [comment]
Note that the step that seems to be failing is the `curl` of the pull-request info from github, a straightforward thing to retry a few times. :+1:
