### ISSUE TITLE
Use separate database names for light/full sync

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#632]
### What is wrong?

Trinity currently doesn't use different databases for `full` and `light` mode. It should as toggling between these modes will yield unexpected results with a shared database

### How can it be fixed

Add a suffix to the `database-dir` part of the path.

- `~/.local/share/trinity/mainnet/light-chain/`
- `~/.local/share/trinity/mainnet/full-chain/`

This will need to be done in the `trinity.utils.chain.ChainConfig`

**Comment by gsalgado** [comment]
Do we need separate `data_dir`s? I think it'd be preferable to have just one `data_dir` per network_id, with separate DBs depending on the sync mode.

**Comment by cburgdorf** [comment]
Oh yes, makes sense!

**Comment by cburgdorf** [comment]
Updated text to reflect we are just talking about the name of the db, not the data directory.
