### ISSUE TITLE
Need to add NAT port mapping support to p2p.Server

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#636]
Most of the times people will run py-evm behind a NAT so other peers in the network won't be able to connect unless we have NAT port mapping configured. However, we should not require users to mess with their routers to set it up manually, so we must do that automatically for them. One way to achieve that is via upnp, and there are python libraries for that: https://github.com/flyte/upnpclient

**Comment by gsalgado** [comment]
As I've already noticed, the discovery (v4) protocol is far from ideal on networks other than mainnet, and it seems to me that a geth instance on ropsten, for instance, gets most of its peers from incoming connections, so we're going to need this in order to finally ditch `HardcodedNodesPeerPool`. It'd be great if we could get this working for the alpha as otherwise syncing may be way too slow or not work at all

**Comment by pipermerriam** [comment]
I started tinkering with it yesterday.  Looked like we can get at least a minimal janky version going pretty easily.

**Comment by gsalgado** [comment]
Yeah, I'm working on that now, should have something ready before EOD
