### ISSUE TITLE
Lazily evaluate vm.previous_hashes

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#648]
### What is wrong?

`vm.previous_hashes` hits the database a lot. Caching helps, but it still involves ~`255 * n` DB reads when importing n blocks. There are probably a lot of blocks that never use the `BLOCKHASH` evm opcode, and so these reads are wasted.

### How can it be fixed

Send a callable (like `lambda: self.previous_hashes`, though probably not literally that) to execution_context that it will invoke, as needed.

I would put a [Good First Issue], but the API is changing a lot, and I don't want to ask a new contributor to do a bunch of ugly rebases.

**Comment by pipermerriam** [comment]
Potential easy path would be exposing them as a generator that lazily evaluates (but allows re-evaluation) for subsequent calls.
