### ISSUE TITLE
Decide when FullNodeSyncer should run a fast-sync

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#654]
The ETH fast-sync protocol (which is currently the first step performed by `FullNodeSyncer`) was developed because when doing the initial sync of a relatively old chain (e.g. ropsten/mainnet), the regular (block-processing) sync could take forever to complete. The idea is that once the initial fast-sync is completed, the client would switch to regular-sync mode and never go back to fast sync.

That is what I originally [intended to do as well](https://github.com/ethereum/py-evm/issues/330), but currently things are a bit more complicated than that as our performance is significantly worse than other clients and if we run `FullNodeSyncer` with a local DB that is only a few days behind, it may take several days for us to catch up. To give an idea, it currently takes between 5-8 seconds to process a block with ~150 transactions, and on mainnet blocks had [(for example, on May 6th) on average ~130 transactions](https://etherscan.io/chart/tx). With one new block every 15 seconds and a local DB 3 days behind it could take us up to 2 days to catch up (assuming a 5 second processing time for a 130tx-heavy block).

Given that, I think it'd make sense for us to have `FullNodeSyncer` run a fast-sync before switching to regular-sync [1] if the local chain is N blocks (or a certain difficulty delta) behind. The choice of N is somewhat tricky though, because running a fast-sync when the local chain is not too far behind may be slower than running a regular-sync since the state-download step has to (potentially) traverse the whole trie and make lots of requests just to get to the few missing nodes [2].

[1] We currently do that always, but that was meant to be temporary
[2] This is a very time-consuming thing to test, so I don't have actual numbers for it

**Comment by pipermerriam** [comment]
I think that we can just set this number at an arbitrary value (2 days?) and work from there.  I'm confident there are still lots of performance improvements we can do to hopefully cut that time down a lot more which will make this way less of a problem.
