### ISSUE TITLE
Need timeouts and proper task-cancellation when dealing with trinity's proxied-services

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#665]
Currently our chain syncer implementation do things like:

```
await wait_with_token(chaindb.coro_import_block(block), token=self.cancel_token)
```

Where chaindb is a `multiprocessing` proxy that runs the actual block importing in a separate process. Since we're dealing with a separate process that may die halfway through importing the block, or hang completely and never respond, I believe we should always specify timeouts when dealing with them -- in the same way we do for network operations.

Also, by wrapping those with wait_with_token() only cancels the outer task and not the one that is actually doing the work, which is created inside coro_import_block() by the await loop.run_in_executor(...) call. Maybe we just need to pass the CancelToken to coro_import_block() and have it use that with wait_with_token() instead of us.

**Comment by carver** [comment]
> I believe we should always specify timeouts when dealing with them -- in the same way we do for network operations.

Thoughts on blocking the shutdown of the db process until all of the other processes are closed out? Otherwise, we're likely to get a spread of `ConnectionResetError`, `BrokenPipeError`, etc. in addition to timeout errors.

**Comment by gsalgado** [comment]
> Thoughts on blocking the shutdown of the db process until all of the other processes are closed out? Otherwise, we're likely to get a spread of ConnectionResetError, BrokenPipeError, etc. in addition to timeout errors.

Isn't that how we do it, currently? trinity.main() first kills the networking process and only after that process is terminated it moves on to kill the database process

**Comment by carver** [comment]
Ah yes, on closer look of the logs, the problem seems more likely to be that asking the networking process to shut down is the problem itself. Here is an example of the connection getting reset:

(first line: networking process asked to shut down)
```
    INFO  06-02 12:15:23        main  Keyboard Interrupt: Stopping
   DEBUG  06-02 12:15:23     service  Cancelling <trinity.nodes.mainnet.MainnetFullNode object at 0x7fd6067672b0>
    INFO  06-02 12:15:23     service  <p2p.chain.FastChainSyncer object at 0x7fd606f41470> finished: Cancellation requested by MainnetFullNode token
    INFO  06-02 12:15:23       chain  Sync with ETHPeer <Node(0x3688@213.168.13.151)> aborted: Cancellation requested by FastChainSyncer:FullNodeSyncer:Server:MainnetFullNode token
   ERROR  06-02 12:15:23        sync  Unclean exit from FullNodeSyncer
Traceback (most recent call last):
  File "/home/jcarver/code/py-evm/p2p/sync.py", line 44, in _run
    await self._sync()
  File "/home/jcarver/code/py-evm/p2p/sync.py", line 60, in _sync
    head = await self.chaindb.coro_get_canonical_head()
  File "/home/jcarver/code/py-evm/trinity/utils/mp.py", line 23, in method
    args,
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```
(last line: connection reset, before database process is asked to shut down)

**Comment by gsalgado** [comment]
@carver actually, they're not terminated in order: https://github.com/ethereum/py-evm/issues/827#issuecomment-394317506

**Comment by gsalgado** [comment]
#860 addresses part of this

**Comment by gsalgado** [comment]
When I wrote this I assumed these method calls on multiprocessing-proxied instances would hang forever if the process died, but that doesn't seem to be the case (AFAICT they raise an exception when that happens), so given that task-cancellation now works as expected when a cancel token is triggered, I'm closing this as we don't seem to need timeouts
