### ISSUE TITLE
Move `validate_seal` down to the VM class

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#667]
### What is wrong?

The `validate_seal` method exists on the `Chain` class, however seal validation can and should be a `VM` level operation.

### How can it be fixed

Move the `validate_seal` method to the `VM` class.  The `VM` class should call out to this within it's `validate_block` method.

**Comment by pipermerriam** [comment]
We can also consider moving the body of `validate_block` into individual methods to make `VM.validate_block` purely an orchestration layer with each piece of validation happening in their own individual methods.

**Comment by glaksmono** [comment]
@pipermerriam would like to take a stab on this

**Comment by cburgdorf** [comment]
Landed with #707 (thank you @darxtrix for the hint)
