### ISSUE TITLE
p2p and sub-proto handshakes cannot be cancelled externally

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#670]
The `peer.handshake()` coroutine gets passed a `CancelToken` so that it can be cancelled, but that token is only used during the auth handshake (it gets passed to the `auth.handshake()` coroutine), and not during the p2p/sub-proto handshakes as those are implemented as methods on the `Peer` class and there we use the instance's own `CancelToken`. The problem is that the instance's token cannot be triggered externally until after the `peer.handshake()` coroutine has returned the instance itself (i.e. after the p2p/sub-proto handshakes).

We could change the `Peer` constructor to take an optional `CancelToken` and chain that with a new one to obtain its own, but that would cause the `Peer` instance to finish when the original `CancelToken` is triggered. I think that makes sense when the original token comes from a `PeerPool`, but will have to double check that this won't have unintended consequences in other cases

**Comment by gsalgado** [comment]
The only real problem with this is that when we kill trinity and there are pending handshakes, asyncio might complain with the infamous "Task was destroyed but it is pending" error.

**Comment by pipermerriam** [comment]
Unfortunately I don't really have a good enough grasp on this to give any constructive feedback.  Getting more and more up-to-speed on the networking stack every day... If you're in need of a second opinion I'll dig in as soon as I can.  Let me know.

**Comment by gsalgado** [comment]
No need to worry, that comment was just to say that this is not really high priority, but also so that this comes up when people search for the "Task was destroyed but it is pending" error.
