### ISSUE TITLE
LightChain integration test is broken

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#711]
Some LightChain methods (e.g. `get_canonical_block_by_number()`) have been removed recently and now `tests/p2p/test_lightchain_integration.py` is broken.

Not sure if there's a plan to add them back or if the functionality is being moved somewhere else

**Comment by carver** [comment]
Did someone ignore a CI failure, or is that not being tested in circle?

**Comment by carver** [comment]
Found it: https://github.com/ethereum/py-evm/pull/685/files#diff-354708b81c89737c927333afd3f068fdL257

Unless someone else wants to jump in, I'll take a look at reviving these methods tomorrow morning. I'm thinking that some of them might go into another class that orchestrates the retrieval and local storage of block/transaction data.

**Comment by carver** [comment]
These all got added back in. Closing...
