### ISSUE TITLE
Convert path types to use `PurePath`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#725]
### What is wrong?

In the `trinity` module we have a number of path objects that are typed as `str`.  

The `pathlib` standard library module has a [`PurePath`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath) class which is more appropriate.

### How can it be fixed

Update the `trinity` module to use the `PurePath` type for all filesystem paths.  If it seems appropriate, lets also update the code to actually use and return `PurePath` objects.

**Comment by glaksmono** [comment]
@pipermerriam would like to take a stab on this 🗡

**Comment by pipermerriam** [comment]
⚔️ stab away
