### ISSUE TITLE
Add logging output for chain reorgs

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#733]
### What is wrong?

Chain re-orgs happen and it would be nice to see some info about them when running trinity.

### How can it be fixed

Whenever trinity is syncing and it encounters a chain reorg we should log something with depth and hashes.  Probably configurable to a certain minimum depth.

For lightchain, this should be relatively easy.

https://github.com/ethereum/py-evm/blob/master/p2p/lightchain.py#L214

Anywhere that `headerdb.coro_persist_header` is called should return an iterable of headers which are *new* to the canonical chain.  If the returned list contains more than 1 entry then the chain just re-organized.

Doing this for full sync is going to require updates to the Py-EVM API so that `chain.import_block` returns an iterable of blocks that are part of the new canonical chain.

**Comment by voith** [comment]
registering this  for myself.

**Comment by voith** [comment]
did not get time to work on this. If this is blocking anyone, I have no problem with anyone else picking this up!

**Comment by voith** [comment]
is this still valid? It seems like the link provided in the title is outdated. #975 did some refactoring. Also, logging seems to have been added in #974.
