### ISSUE TITLE
Extend `HardCodedNodesPeerPool` class to also do discovery.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#741]
### What is wrong?

We currently use a stop-gap solution for working around v4 discovery, `p2p.peer.HardCodedNodesPeerPool`.  It contains known nodes to connect to, specifically for LES connections.

This approach is problematic because these nodes are not guaranteed to be online or to have capacity so.  If they are, then Trinity will not be able to connect until a slot becomes available.  Worse, there's no way without code modification to add new nodes to this list.

### How can it be fixed

Extend how we use this class to to *also* do discovery.  For the first iteration it should treat the hard coded list the same as any nodes that have been connected to via discovery.

Also, add a new CLI flag which can be used to add nodes to this list.

```bash
$ trinity --static-node "enode://deadbeef...@1.2.3.4:30303"
```

This flag should be accepted multiple times to allow specifying multiple nodes.

**Comment by gsalgado** [comment]
>  For the first iteration it should treat the hard coded list the same as any nodes that have been connected to via discovery.

Not sure what you mean by that?

**Comment by pipermerriam** [comment]
Alright, how about this logic which should be simple to implement.

1. For each static node, maintain a timestamp of the last attempted time to connect.
2. When we request a *random* node, we first exhaust our static node list, ignoring any for which we recently (maybe 300 seconds?).
3. If there are no nodes in our static nodes list which we can try (all of them have been tried in the last 300 seconds), we pull random nodes from the routing table.
