### ISSUE TITLE
Enable logging to file by default for alpha releases

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#742]
### What is wrong?

Users of the alpha releases are very likely going to encounter errors for which we need debug level logging output to diagnose.  They however are unlikely to be both logging at the `DEBUG` level **and** retaining log output.

### How can it be fixed

Lets enable file based logging in a `$XDG_TRINITY_ROOT/<chain-dir>/logs` at the `DEBUG` level.  This way when a user has an issue we can get them to dig out the relevant logfiles for us.

**Comment by pipermerriam** [comment]
@glaksmono sorry for the confusion, updated to correctly reference `$XDG_TRINITY_ROOT`.

https://github.com/ethereum/py-evm/blob/master/trinity/utils/xdg.py

**Comment by glaksmono** [comment]
@pipermerriam Would like to take a stab on this 🔪 

Do we want this file logging behavior to be the `default`?

**Comment by pipermerriam** [comment]
@glaksmono just in case there was still any question, yes, I think this logging should be on by default.

- make use of the rotating file handler so that logfiles don't become too large.
- if it's possible to place an upper bound on the total size of the logs 👍 
- lets display in the terminal when trinity starts up where the logfile is located.

**Comment by cburgdorf** [comment]
This seems to be solved. Please reopen if I you feel there's something unaddressed.
