### ISSUE TITLE
Changes to `Chain.import_block`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#772]
Blocks: https://github.com/ethereum/py-evm/issues/733

### What is wrong?

Currently `chain.import_block(..)` returns the block that was imported.  Sometimes, this will cause a chain re-org, but this API doesn't expose sufficient information to determine this.

### How can it be fixed

Change `Chain.import_block` to return two iterables:

- blocks which are *new* to the canonical chain.
- blocks which were *previously* part of the canonical chain (but no longer are).

With this, callers can inspect the return value and determine that a re-org happened when more than a single block is returned.

This will also require changing `ChainDB.persist_block` to return the same data format, an iterable of blocks which are part of the new canonical chain.

**Comment by carver** [comment]
With HeaderDB, we ended up also returning a list of dropped headers on re-org, right? That might make sense here, too.

**Comment by voith** [comment]
registering this for myself.

**Comment by voith** [comment]
did not get time to work on this. If this is blocking anyone, I have no problem with anyone else picking this up!

**Comment by glaksmono** [comment]
Already confirmed with @voith that I will take on this task 🍴

**Comment by glaksmono** [comment]
Haven't had a chance working on this. Would be ok if anyone could take on it

**Comment by carver** [comment]
I expect this to be a common question, so wanted to add the conversation from chat:
>  How can there be multiple blocks that are new? Because ChainDB.import_block is importing 1 block at a time

It's returning the blocks that are new to the canonical chain. Let's say you have chain:

```
A -- B - C
  `- D
```

where C is the current canonical head.

Then you import E with parent D, where the total difficulty of E is higher than C. Now, you have added D and E to the canonical chain, and removed B and C.

**Comment by voith** [comment]
Is this issue still valid? It seems like logging when a re-org happens has been added in #974. So I assume that whatever logic was needed to resolve the blocker has been addressed.

**Comment by carver** [comment]
> Is this issue still valid?

Yes, `import_block()` still only returns one block.

**Comment by carver** [comment]
Closed by #1151
