### ISSUE TITLE
Trinity `Auth ack msg too short`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#776]
### What is wrong?

```
   ERROR  05-24 15:52:55        peer  Unexpected error during auth/p2p handshake with <Node(0x4382@104.149.231.208)>
Traceback (most recent call last):
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 739, in connect
    self.cancel_token)
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 136, in handshake
    ) = await auth.handshake(remote, privkey, token)
  File "/Users/piper/sites/py-evm/p2p/auth.py", line 55, in handshake
    initiator, reader, writer, token)
  File "/Users/piper/sites/py-evm/p2p/auth.py", line 77, in _handshake
    ephemeral_pubkey, responder_nonce = initiator.decode_auth_ack_message(auth_ack)
  File "/Users/piper/sites/py-evm/p2p/auth.py", line 179, in decode_auth_ack_message
    raise ValueError("Auth ack msg too short: {}".format(len(ciphertext)))
ValueError: Auth ack msg too short: 0
```

This error occurs semi regularly during fast sync (and in general during running the trinity node.)

### How can it be fixed

Explicit error handling.

**Comment by glaksmono** [comment]
@pipermerriam just want to be clear on the terminology, when you said "fast sync", you are referring to `trinity --light` mode correct?

**Comment by pipermerriam** [comment]
No, I'm referring to the sync mode that trinity uses by default when you just run `trinity` but I actually think that's irrelevant to this issue.

I think we just need one more `except` block in the `try/except` within the `Peer.connect` method.

**Comment by glaksmono** [comment]
@pipermerriam I'm thinking about adding more log message to understand the root cause. Thoughts?
