### ISSUE TITLE
Trinity fails if `$HOME` environment variable is not set.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#784]
### What is wrong?

```bash
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/venv/bin/trinity", line 11, in <module>
    load_entry_point('py-evm', 'console_scripts', 'trinity')()
  File "/home/ubuntu/py-evm/trinity/main.py", line 101, in main
    initialize_data_dir(chain_config)
  File "/home/ubuntu/py-evm/trinity/chains/__init__.py", line 88, in initialize_data_dir
    chain_config.data_dir,
ValueError: The base chain directory provided does not exist: `//$HOME/.local/share/trinity/mainnet`
```

If the `$HOME` environment variable isn't set Trinity crashes.

### How can it be fixed

Gracefully handle this not being set and provide a helpful error message informing the user that they can:

- set `$HOME` to the desired path.
- set `$XDG_TRINITY_HOME` to the desired path.
- set `$TRINITY_DATA_DIR` to the desired path.
- run trinity with the `--data-dir /some/path` where `/some/path` is the desired path.

All of these should be tested to work as solutions.

**Comment by MysticRyuujin** [comment]
It seems that the default `data-dir` if not specified is `./\$HOME` also which seems weird

**Comment by cburgdorf** [comment]
I have a fix with solid test coverage brewing.
