### ISSUE TITLE
SMC integration with py-EVM

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-evm#799]
Right now, the `ShardSyncer` passively listens to their peers for new collations and downloads all of those. In a real network however, it should check the SMC for headers and specifically download the bodies for those. To this end, we need a way to interact with the SMC.

In the sharding repository we have the classes `ShardTracker` and `SMCHandler` that provide an interface for accessing the SMC. We need a service that uses those and bridges to the `ShardSyncer`. Here's how I imagine it to look like:

### `class SMCService`

* Has an `SMCHandler`
* Has a `ShardTracker`
* Periodically (at least once per block) triggers the `ShardTracker` for new logs
* Processes those logs to keep an always up-to-date view of relevant part of the SMC state
* Other services can register queues to receive headers whenever they are added or confirmed (`register_added_header_queue`, `register_confirmed_header_queue`)
* Provides a method to add headers (mostly pass-through method `SMCHandler`)

For notaries `SMCService` is subclassed:

### `class NotaryService(SMCService)`

* Has a private key
* Provides events `registered`, `deregistered` and `released`
* Provides a method `submit_vote` (mostly pass-through method `SMCHandler`)

The shard syncer will

* Register to the `register_added_header_queue` and/or `register_confirmed_header_queue`
* Add those headers to the shard
* Wait for a corresponding `NewCollationHashes` message if the header is relatively new (say, half a period)
* Request the collation body otherwise
* When receiving a body vote for it if possible

Changes required at `ShardTracker`: As far as I can see only a way to get all header-added and notary-voted logs from the SMC for all of history so that the `ShardSyncer` can sync from genesis.

@hwwhww @NIC619

**Comment by hwwhww** [comment]
Summary of some off-github discussions:
#### Periodically (at least once per block) triggers the ShardTracker for new logs
1. By polling `ShardTracker.get_add_header_logs()`: https://github.com/ethereum/sharding/blob/efa573ed9effaaf0ef877a4e0aa8b046c8893b2c/sharding/handler/shard_tracker.py#L82
	* Some required modification in sharding repo:
		1. `from_block` issue: by default, it uses **the start of current period**, but it’s impossible to guarantee we won’t miss any single period in Trinity level. So we may need to set `from_block` by other means.
			* Possible solution: Tracking the main chain block number as the source of `from_block`.
		2. Parent chain reorg issue
			* Possible solution:
			    1. Tracking `blockhash`. Every round, querying the `blockhash` again and checking if it’s the same.
			    2. Detecting at web3.py layer.
2. Async
	1. Now the `ShardTracker` and `LogHandler`  are both non-async. So invoking those function may block the node.
	2. May also need async web3.py APIs: https://github.com/ethereum/web3.py/issues/657

#### Possible system architecture

The above `NotaryService` design is a part of `ShardSyncer`. Exploring the higher level of Trinity, it may be:
```
[trinity] ShardNode
	-> [p2p] ShardNode._p2p_server: ShardServer
  		-> [p2p] ShardServer.shard_syncer: ShardSyncer
```

**Comment by hwwhww** [comment]
> SMC server periodically (at least once per block) triggers the ShardTracker for new logs

Some thoughts about the roles:
1. A node may use `NotaryService` and `ProposerService` and the same time. So I think the trigger point of calling `ShardTracker.get_add_header_logs()` should be only in one place that shared by the `SMCService`s?
2. A node may watch multiple shards, and the notary pool info from SMC should be shared cross services.

Another direction is  that in the earlier draft design, there is a new `ShardMonitor` **process** that is responsible to poll SMC and notify `ShardManager` that manages multiple shards. `ShardManager` is just a very abstract idea by that time, it can be considered as the middle layer between `ShardServer` and `ShardSyncer`. The sub-services (`NotaryService`, `ProposerService`) of different shards can have a pubsub relationship with `ShardMonitor`.

#### Pros:
1. Making the polling service aside by the server, clearer roles.
2. May be easier to share the same data from SMC?

#### Cons:
1. Neet to maintain a new process alive well.
2. The performance cost of maintaining IPC?

**Comment by jannikluhn** [comment]
> A node may use NotaryService and ProposerService at the same time. So I think the trigger point of calling ShardTracker.get_add_header_logs() should be only in one place that shared by the SMCServices?

I agree. Originally I thought there would only be one `SMCService` running (possibly as a `NotarySMCService`) and a `ProposerService` would just have a reference ot the `SMCHandler` to call something like `propose`. But that would be confusing as a notary and proposer would use a different type of API. So having a general `SMCService` and separating the notary and proposal funcitonality is better.

```
Another direction is that in the earlier draft design, there is a new ShardMonitor process that is responsible to poll SMC and notify ShardManager that manages multiple shards. ShardManager is just a very abstract idea by that time, it can be considered as the middle layer between ShardServer and ShardSyncer. The sub-services (NotaryService, ProposerService) of different shards can have a pubsub relationship with ShardMonitor.
```

`ShardMonitor` seems pretty close to what I envision `SMCService` to be. However, I don't see value in adding a `ShardManager` as another layer between `SMCService` and `ShardSyncer`. It might make sense though to have something like this just to track all the different `ShardSyncers` for the different shards (but that would be extremely light weight).

**Comment by hwwhww** [comment]
> However, I don't see value in adding a ShardManager as another layer between SMCService and ShardSyncer.

What I said is **`ShardServer`** and ShardSyncer. ;)
Because (i) The main chain `Server` looks focused on the networking and not dealing with clien logic and (ii) it seems we use one `ShardSyncer` per shard? So I think a middle layer may be helpful here.
