### ISSUE TITLE
Trinity should support logger-specific levels

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#806]
The log level specified via the command line is used for all loggers. It should be possible to specify logger names/levels pairs as well. Something like `-l p2p.chain:debug,p2p.peer.Peer:warn`

**Comment by dram** [comment]
As this issue has been fixed, those lines may need to be updated:

https://github.com/ethereum/py-evm/blob/v0.2.0-alpha.31/trinity/utils/logging.py#L111-L114

**Comment by pipermerriam** [comment]
https://github.com/ethereum/py-evm/issues/1243
