### ISSUE TITLE
Trinity raises uncaught `HeaderNotFound` exception

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#837]
### What is wrong?

```
   ERROR  05-30 17:56:58  base_events  Task exception was never retrieved
future: <Task finished coro=<FastChainSyncer.sync() done, defined at /home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/chain.py:161> exception=HeaderNotFound('No header with hash 0xe3b100bfd7ab6e5c28bda5e469fb7c3c9082245efda142d26a12220e8e9cb153 found',)>
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/chain.py", line 174, in sync
    await self._sync(peer)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/chain.py", line 220, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/chain.py", line 244, in _process_headers
    target_td = await self._calculate_td(headers)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/chain.py", line 237, in _calculate_td
    td = await self.chaindb.coro_get_score(headers[0].parent_hash)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/trinity/utils/mp.py", line 23, in method
    args,
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
evm.exceptions.HeaderNotFound: No header with hash 0xe3b100bfd7ab6e5c28bda5e469fb7c3c9082245efda142d26a12220e8e9cb153 found
```

In a trinity node I've been running for testing I'm now getting this error.  It's odd as it *thinks* that the head block is around 2.5 million which makes me think that Trinity is on the wrong fork of the mainnet chain.

#832 was a stab at fixing this but now that I've been futzing with it for a while I'm convinced it isn't the right solution.  The following note is present in the `_sync` method:

> Fetch a batch of headers, in reverse order, starting from our current head, and find the common ancestor between our chain and the peer's.

This indicates that we *want* to do something similar to the approach in #832 

Some thoughts:

1. We need *intelligent* peer selection to handle this type of case where the client synced with the *wrong* chain.
2. For the `_sync` loop I think we need a binary search approach to finding the common ancestor in a reasonable number of requests.
3. When we do have to go back into history to find a common ancestor we **might** need to set an upper limit on how big of a chain re-org Trinity will allow.
4. Maybe some sanity checks for each chain can be baked into the client with a *hint* for a minimum height that will be accepted for the pre-configured chains.

**Comment by gsalgado** [comment]
> In a trinity node I've been running for testing I'm now getting this error. It's odd as it thinks that the head block is around 2.5 million which makes me think that Trinity is on the wrong fork of the mainnet chain.

Do you mean your node is fully synced and has a head around 2.5M?

> We need intelligent peer selection to handle this type of case where the client synced with the wrong chain.

We always sync with the peer that announced the highest TD, so IIUC what you think is going on in your node could only have happened if all the peers you were connected to were on the wrong fork, no?

> For the _sync loop I think we need a binary search approach to finding the common ancestor in a reasonable number of requests.

Definitely, but the current implementation always starts fetching headers from `local_head - 192`, and will crash badly if the common ancestor is not found.

> When we do have to go back into history to find a common ancestor we might need to set an upper limit on how big of a chain re-org Trinity will allow.

Agreed

> Maybe some sanity checks for each chain can be baked into the client with a hint for a minimum height that will be accepted for the pre-configured chains.

AIUI, this is not an issue now as we only go back 192 blocks every time we start syncing with a peer, and we'll only start a sync with a peer if that peer's announced TD is higher than ours and the highest announced among all peers

**Comment by gsalgado** [comment]
Can you upload your logs, starting at least a few minutes before where the error occurred? Also, is this happening as soon as you start the node or do you see some progress once you restart and then eventually it hits this again?

**Comment by pipermerriam** [comment]
logs here: https://gist.github.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75#file-trinity-headernotfound-log

**Comment by gsalgado** [comment]
This was indeed another case of us syncing with an ETC peer up to a certain point, and then trying to sync with an ETH peer. The header in question (0xece237530e071cce756971d22923b3af974fddab00be9fb1ab57d722f382610a) is for an ETC block: http://etcchain.com/block/hash/0xece237530e071cce756971d22923b3af974fddab00be9fb1ab57d722f382610a
