### ISSUE TITLE
LightPeerChain should confirm that contract code retrieved matches what was requested

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#849]
Currently `LightPeerChain.get_contract_code()` simply return whatever is served to us by a peer, but we should confirm that it matches the code_hash for the account, as suggested in https://github.com/ethereum/py-evm/pull/841#discussion_r192200495

**Comment by carver** [comment]
Oops didn't see the GFI tag. I'll avoid any others in the milestone.
