### ISSUE TITLE
List of people willing to help test the Py-EVM client.

### ISSUE THREAD

**Issue by Sebohe** [ethereum/py-evm#86]
If you are interested in helping us test early versions of the Py-EVM client please leave a comment indicating as much on this issue:

* @Sebohe 
* @egong 
* @nickray 
* @njgheorghita 
* @juinc 
* @djrtwo 
* @brahbby 
* @pablovem 
* @brianz 
* @jvs87 
* @djrtwo 
* @changwu-tw
* @empea-careercriminal

**Comment by egong** [comment]
I'll help

**Comment by nickray** [comment]
I'm in need of an Ethereum node I can drive from Python. This implies I'm willing to test this Py-EVM client :)

**Comment by njgheorghita** [comment]
I'm down

**Comment by juinc** [comment]
I will help 👍

**Comment by djrtwo** [comment]
Here to help. Following the repo now.

**Comment by pablovem** [comment]
✋  I want to help.

**Comment by brianz** [comment]
Ditto, looking to get deeper into Ethereum guts and would love to participate.

**Comment by jvs87** [comment]
I would like to help too!

2017-11-01 22:51 GMT+01:00 Brian Zambrano <notifications@github.com>:

**Comment by djrtwo** [comment]
I'm in!

**Comment by changwu-tw** [comment]
Would like to help too!

**Comment by empea-careercriminal** [comment]
Want to help.

**Comment by themusicgod1** [comment]
I'm slowly building the dependencies to package this and will do any testing that I can while I'm at it.  See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884796

**Comment by step21** [comment]
Sounds good

**Comment by ankitchiplunkar** [comment]
I am willing to help as well.

**Comment by mateuszk87** [comment]
I would also like to help

**Comment by pipermerriam** [comment]
Closing this as our alpha is now out.

http://py-evm.readthedocs.io/en/latest/guides/trinity/quickstart.html

Please let us know any issues you run into while running the node.  Worth pointing out that we are aware of long sync times.  Expect maybe 1-2M blocks/day syncing with fast sync.
