### ISSUE TITLE
Cleanup how `max_peers` is enforced

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#864]
### What is wrong?

I ended up creating multiple fast-and-dirty attempts to get Trinity to respect it's `max_peers` limit.  This needs to be cleaned up.  We *should* be able to enforce this with code at only a small number of code locations.

1. refrain from `self.connect(...)` when full.
2. refuse incoming connections when full.

### How can it be fixed

Take a look at all of the places where we check `is_full` and condense it down to only the necessary ones.

**Comment by darxtrix** [comment]
Hi @pipermerriam will take this hoping nobody else is working on it and get started with the contributions :)

**Comment by darxtrix** [comment]
Reviewed the file `p2p/peer.py`, Its used at two places line 696 and line 728. Both of them seems necessary to me as the in function `_connect_to_nodes`, the `nodes` can be of any length and hence we need a double check.

Apart from that I can find the use of `is_full` at `p2p/server.py` where it is also used purposefully for rejecting the handshake after receiving once in case the peer pool is full.

I think the issue can be closed, or I am missing something ?

**Comment by pipermerriam** [comment]
You may be correct, taking a look now.

**Comment by pipermerriam** [comment]
Yup, looks like this was already being done correctly.  👍 

cc @gsalgado if you see something I'm not seeing.

**Comment by darxtrix** [comment]
Thanks for the fast review, one more thing on other good first issues there are already PRs and some of them are merged, can we close them https://github.com/ethereum/py-evm/issues/775 , https://github.com/ethereum/py-evm/issues/667

**Comment by cburgdorf** [comment]
@darxtrix you are correct. Both seem implemented. I closed them. Thank you for the hint.

**Comment by darxtrix** [comment]
@cburgdorf 👍

**Comment by gsalgado** [comment]
One thing I suggested in a previous PR is to change `_connect_to_nodes()` to not call `connect()` when the pool is already full. Right now it first connects, then checks if the pool is full and, if so, disconnects, which makes no sense

**Comment by pipermerriam** [comment]
cc @darxtrix could you make the update that @gsalgado suggests.  Simply moving the `is_full` check to before we do the peer connection.
