### ISSUE TITLE
Check if we can initialize the PeerPool earlier

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#877]
### What is wrong?

This is a follow up to the discussion @pipermerriam and I had [here](https://github.com/ethereum/py-evm/pull/867#discussion_r193187256).

Currently the `PeerPool` isn't available until some other async tasks are resolved. This issue serves as a reminder to check whether the `PeerPool` could be created synchronously earlier.

### How can it be fixed

A possible idea would be to create the `PeerPool` early on without the dependencies that first need to be resolved asynchronously and then as a second step, once these dependencies are resolved, call some initialization API on the `PeerPool`. Before that, the `PeerPool` would already exist but would reside in some sort of `bootstrapping` mode until that API is called.

Not sure, if I like that tbh. ¯\_(ツ)_/¯

**Comment by gsalgado** [comment]
ISTM that the problem here is the fact that `Server.peer_pool` only gets set in `Server._run()` and not in `Server.__init__()`, as it should. IIUC we do that because of some (far from ideal) server or sharding tests. If we fix those tests we could then initiate a `PeerPool` and assign it to `Server.peer_pool` in `Server.__init__()`, as I think we should do

**Comment by cburgdorf** [comment]
@gsalgado That is correct but the `PeerPool` depends on the `DiscoveryProtocol`

https://github.com/ethereum/py-evm/blob/af3ac1ddd3c5cf18253b79ce4c9ea356556c83f1/p2p/server.py#L266

Which depends on the external ip address

https://github.com/ethereum/py-evm/blob/af3ac1ddd3c5cf18253b79ce4c9ea356556c83f1/p2p/server.py#L263-L264

Which we get from the `upnp_dev`

https://github.com/ethereum/py-evm/blob/af3ac1ddd3c5cf18253b79ce4c9ea356556c83f1/p2p/server.py#L252

Which we `await` on in the beginning.

https://github.com/ethereum/py-evm/blob/af3ac1ddd3c5cf18253b79ce4c9ea356556c83f1/p2p/server.py#L249

So what I meant to say is that it seems to me that we can create the `PeerPool` early on in `__init__` but we either have to pass in something like an `Awaitable[DiscoveryProtocol]` and `await` that inside or we introduce some method to set the `DiscoveryProtocol` after creation. Either way it seems that this would leave the `PeerPool` in a state where it can't fully operate yet until the `DiscoveryProtocol` (which is waiting on the external IP) is resolved.

Am I reading that wrong?

**Comment by gsalgado** [comment]
Oh, that is right, `DiscoveryProtocol` is the problematic piece... Can't think of a nice way to solve this :-(

**Comment by cburgdorf** [comment]
@gsalgado I have tinkered a bit with the idea of creating the PeerPool and passing in a `Future[DiscoveryProtocol]` (aka `Awaitable[DiscoveryProtocol]`). It's not pretty yet because it basically just pushes down the problem one level deeper (now `PeerPool` will magically have the `self.discovery` appearing in the *done callback*)

But it's really just earlier WIP stuff anyway and it's my first attempt of getting my feet wet with asyncio in Python :sweat_smile: 

https://github.com/ethereum/py-evm/pull/886

**Comment by cburgdorf** [comment]
Solved problem. Closing.
