### ISSUE TITLE
Trinity stalls during sync

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#880]
### What is wrong?

From timestamp `INFO  06-06 23:06:38` till `INFO  06-07 00:42:38` my trinity node synced no headers despite being connected to 10 peers (9 inbound, 1 outbound)

DEBUG LOG: https://gist.github.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/8326dec145f393626b0e402cdac77b482230518f/trinity-stalled-sync.log

### How can it be fixed

Haven't actually dug into the logs yet to see why.

**Comment by pipermerriam** [comment]
Here is the relevant section of that logfile: https://gist.github.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/dde2e7b06cd09e99f0f7d465b2097a00741ce9aa/trinity-stalled-sync-only-good-section.log

Still nothing jumping out at me as the reason syncing stalled.

**Comment by gsalgado** [comment]
Some interesting things to notice:

> DEBUG  06-06 23:05:55        peer  Already connected to 11 peers: [<Node(0x6e5c@72.36.89.13)>, <Node(0x18de@72.36.89.13)>, <Node(0x3cde@72.36.89.13)>, <Node(0x51da@72.36.89.13)>, <Node(0x3167@72.36.89.13)>, <Node(0xc342@72.36.89.13)>, <Node(0x7053@72.36.89.13)>, <Node(0xa845@72.36.89.13)>, <Node(0x45cc@72.36.89.13)>, <Node(0x3b65@178.69.199.63)>, <Node(0x42b3@210.186.135.215)>]; sleeping

Out of the 11 peers above, 9 are the same IP address, but different node IDs

>     INFO  06-06 23:06:02       chain  Head TD (17179869184) announced by ETHPeer <Node(0x3cde@72.36.89.13)> not higher than ours (130894749091490763), not syncing

And they seem to be behind us, so we won't try to sync from them

>    DEBUG  06-06 23:52:52        peer  Already connected to 10 peers: [<Node(0x6e5c@72.36.89.13)>, <Node(0x18de@72.36.89.13)>, <Node(0x3cde@72.36.89.13)>, <Node(0x51da@72.36.89.13)>, <Node(0x3167@72.36.89.13)>, <Node(0xc342@72.36.89.13)>, <Node(0x7053@72.36.89.13)>, <Node(0xa845@72.36.89.13)>, <Node(0x45cc@72.36.89.13)>, <Node(0xe6e0@72.36.89.13)>]; sleeping

Now all your peers are the same node?

> DEBUG  06-07 00:43:07      server  Receiving handshake from Address(72.36.89.13:udp:53558|tcp:53558)

And we keep receiving incoming handshakes from that IP

I was initially tempted to think there could be a bug in `PeerPool` causing us to keep peers in `PeerPool._connected_nodes` even after they've disconnected, but the fact that each of those peers have a different node ID but the same IP address suggests something malicious is going on

**Comment by gsalgado** [comment]
If we refused to pair with multiple peers using the same IP address it should be very unlikely for us to end up in a situation like this, where none of our connected peers have a higher TD than ourselves

**Comment by carver** [comment]
Sounds similar to [the eclipse attack](https://www.cs.bu.edu/~goldbe/projects/eclipseEth). One of the mitigations they suggested was limiting the number of peers with the same address, IIRC, so :+1: to:

> If we refused to pair with multiple peers using the same IP address it should be very unlikely for us to end up in a situation like this, where none of our connected peers have a higher TD than ourselves

**Comment by pipermerriam** [comment]
Yeah, wouldn't surprise me if this is related to the eclipse attack.  Thanks for doing the digging @gsalgado , I looked at these, but didn't notice the same IP addresses.

**Comment by gsalgado** [comment]
Closing as we now have a limit of just 1 peer per IP address so this should no longer happen
