### ISSUE TITLE
Validate genesis header

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#892]
### What is wrong?

Right now, we aren't doing anything to validate that the genesis header we download is compatible with the genesis setup used in `trinity`. (not that we support arbitrary genesis settings now, but we will at some point)

### How can it be fixed

See some discussion at: https://github.com/ethereum/py-evm/pull/883#discussion_r194305867

Evaluate the genesis file setup we'll use (I think an EIP is in draft or merged on this). Does it fully specify the header? If so, force header creation before launching p2p. If not, save the genesis fields for later validation.

**Comment by gsalgado** [comment]
Wait, do we actually download the genesis header? When I said compare the hash there, I meant comparing the `genesis_hash` that is included in the sub-proto handshake

**Comment by carver** [comment]
> Wait, do we actually download the genesis header?

Yes, if I remove the special handling of the genesis header and run trinity in light mode, I get:

```
WARNING  06-11 13:25:11  lightchain  LESAnnouncementProcessingError('Peer LESPeer <Node(0x053d@79.98.29.154)> sent invalid header <BlockHeader #0 41941023>
```

> When I said compare the hash there, I meant comparing the genesis_hash that is included in the sub-proto handshake

Sorry, I don't follow. Are you [talking about this](https://github.com/ethereum/py-evm/blob/master/p2p/p2p_proto.py#L92)? I'm not sure how to tie that in -- still learning how it all fits together.

**Comment by gsalgado** [comment]
That's the base protocol (P2P) handshake. The sub-protocol (LES, ETH, etc) handshake must include the genesis hash, which is used (together with the network ID) to decide if we want to connect to a peer or not. Also, I believe other peers won't connect to us if we send a blank genesis hash in the handshake.

I guess my point is we must assume the genesis header for our chain is present in the DB when we start, and should never try to download it. It looks like currently that check is not explicit, but I believe it should be
