### ISSUE TITLE
Deduplicate p2p auth code

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#899]
### What is wrong?

The following code is duplicated in `p2p.auth`

- https://github.com/ethereum/py-evm/blob/master/p2p/auth.py#L178-L182
- https://github.com/ethereum/py-evm/blob/master/p2p/auth.py#L210-L214

### How can it be fixed

Move it to a small top level function in the module

```
def _pad_eip8_data(data):
    ...
```

**Comment by williambannas** [comment]
I would like to try to fix this issue

**Comment by cburgdorf** [comment]
@williambannas go for it 👍
