### ISSUE TITLE
Limit number of peer connections from the same IP address

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#904]
should fix: https://github.com/ethereum/py-evm/issues/880#issuecomment-395369943

### What is wrong?

https://www.cs.bu.edu/%7Egoldbe/projects/eclipseEth

We should add protection against eclipse attacks.

### How can it be fixed

Two things:

- The peer pool should be configurable for how many connections may be made to the same IP address.  I think a default of `2` should be acceptable here.
- The peer pool should require that a certain percentage of peer connections be outgoing (dial out).  Lets require `1/4` of our peer connections to be outbound (with a strict lower bound of `1` if the peer pool max peers is `>2` and no lower bound if `max_peers == 1`).

**Comment by pipermerriam** [comment]
This can be done in two pull requests.

**Comment by williambannas** [comment]
I would like to try to fix this issue as well

**Comment by pipermerriam** [comment]
go for it! 😄

**Comment by pipermerriam** [comment]
As I believe was suggested in the gitter channel by @gsalgado 

- Add a new method `PeerPool.is_valid_connection_candidate(node)` which takes a `kademlia.Node` instance and returns `True` or `False` depending on whether the node should be considered.  Within this method you can implement the check for whether we have an existing peer with the same IP address.
- In `Server._receive_handshake()` use this new method to either reject the handshake if it returns `False`.
- In `PeerPool.get_nodes_to_connect()` use this new method to filter the returned nodes.

**Comment by cburgdorf** [comment]
This landed as https://github.com/ethereum/py-evm/pull/935
