### ISSUE TITLE
Profile and optimize new VM.validate_header()

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#910]
That method takes 1.4s to complete when I call it passing the DAO fork header (1920000). If it takes as long to validate any header, that will be a huge problem for the light client and fast-sync

Need to profile it and optimize. Unless, of course, it's only when validating the DAO fork header that it takes that long

**Comment by carver** [comment]
I heard a rumor that geth doesn't check the PoW on every header. Would be worth checking out how they do that safely.

**Comment by gsalgado** [comment]
Indeed it doesn't; I describe their approach in https://github.com/ethereum/py-evm/issues/330#issue-292753647

**Comment by gsalgado** [comment]
So, as shown by the profiling data above, doing PoW validation makes light sync much slower, but it's mainly because of pyethash.hashimoto_light, which I imagine won't be easy to optimize, so I think our best bet is #932

**Comment by carver** [comment]
Should we:

1. move this issue to the following milestone, or
2. add kth header validation to Grace Hopper

I think I'm pro 1

**Comment by gsalgado** [comment]
I guess we could do both. 2 is already on its way (#1010)

**Comment by carver** [comment]
With #1010 merged, this issue seems done enough to close.
