### ISSUE TITLE
Rename core module from `evm` to `eth`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#931]
### What is wrong?

The core module used in py-evm is `evm`.  This name is becoming less appropriate and if it is ever going to be renamed, now is the time.

### How can it be fixed

Rename core module to `eth`.  Please discuss whether we should ship an aliased `evm` module for a while or whether our *alpha* status allows for us to make this kind of major breaking change.

**Comment by cburgdorf** [comment]
>Please discuss whether we should ship an aliased `evm`

I feel that we are totally still in that safe alpha space to make these changes without a deprecation strategy.

Btw, do we agree that we should also rename the whole project from `py-evm` to `py-eth`? I think `py-eth` is more future proof.

**Comment by pipermerriam** [comment]
That one feels harder.  The `eth` package on pypi appears to be held by @lmittmann who doesn't appear to be doing anything with it though I'm unable to source any contact information for them.

**Comment by cburgdorf** [comment]
I added "Good First Issue" because it's easy to shoot at in its nature. However due to the fact that this touches a large number of files it is expected to have to deal with several rebases among the review process.

For anyone looking at this, I recommend to leave a note here to coordinate. In general, @pipermerriam do you think there's anything blocking is from doing the rename sooner than later?

**Comment by pipermerriam** [comment]
> do you think there's anything blocking is from doing the rename sooner than later?

No, someone could jump on this now.

**Comment by mneedham91** [comment]
Intermediate Python coder & Ethereum newbie here. This is just searching for necessary references and renaming, correct? I am interested in taking it on. Will try to set time aside to take a crack at it tonight.

**Comment by mneedham91** [comment]
I have begun work on this at [mneedham91/py-evm](https://github.com/mneedham91/py-evm). Changed the main package as well as docs. Will look through rest of py-evm for any other necessary changes. I know I've let some pycharm crap seep in I'll need to take out before creating a pull request when ready, any other feedback would be appreciated.

**Comment by carver** [comment]
@mneedham91 we :heart: early pull requests, even with broken tests and pycharm files. Just add "WIP" to the title (work in progress) and ideally the list of things you know you still need to do in the comments.

**Comment by mneedham91** [comment]
Ok! WIP pull request here: https://github.com/ethereum/py-evm/pull/1002
