### ISSUE TITLE
K-th header PoW verification

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#932]
### What is wrong?

PoW verification is computationally expensive (even for high-performant languages like Go)

### How can it be fixed

instead of verifying the PoW on every header, geth does so on a randomly chosen subset of them, in a way that the
probability of a forgery is smaller than the probability of an attacker producing a SHA3 collision.

**Comment by pipermerriam** [comment]
Regarding label usage.  My intention for the `p2p` label is everything that is not pure (or almost pure) DevP2P protocol.  Anything that's part of the ethereum node syncing code should be `trinity`

**Comment by carver** [comment]
> My intention for the p2p label is everything that is not pure (or almost pure) DevP2P protocol.

Extra *not* in there?

So p2p label would be for "everything that **is** ~not~ pure (or almost pure) DevP2P protocol."

**Comment by gsalgado** [comment]
Fair enough, I thought I was the only one using the `p2p` label, and was doing so to keep track of anything related to the `p2p` package

**Comment by pipermerriam** [comment]
I've been wanting to move most of the *trinity* code from the `p2p` package into `trinity` for a while.  Probably something that should be done sooner than later.
