### ISSUE TITLE
Prevent relaying of invalid transactions (possible DDOS attacks)

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#945]
### What is wrong?

The receipt and processing of transactions from peers is a potential DDOS vector.  A peer could spam us with bad transactions which could overload our node as *checking* the validity of a transaction isn't cheap.

This can also cause us to be disconnected from other peers if we relay these bad transactions.

### How can it be fixed

- We should check the validity of a transaction before relating it.
- We should disconnect from peers who send us too many invalid transactions.

**Comment by cburgdorf** [comment]
Sounds good, do you want that addressed as part of #898 before it lands or can it land in a follow up?

**Comment by pipermerriam** [comment]
Follow up, just tracking the issue.
