### ISSUE TITLE
The --trinity-root-dir argument doesn't seem to have any effect at all

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#951]
### What is wrong?

Trinity promotes `--trinity-root-dir` to overwrite the trinity root dir but we actually don't pick that up anywhere. In other words, passing `--trinity-root-dir` is absolutely useless right now unless I'm missing something.

### How can it be fixed

Revisit in combination with #922

**Comment by pipermerriam** [comment]
closed by #1268

**Comment by pipermerriam** [comment]
not quite merged, got confused.
