### ISSUE TITLE
Exception information lost when it passes through multiprocessing-based services

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#956]
When we call a method on one of our multiprocessing-based services and that method raises an exception, the multiprocessing module catches and re-raises it, but then we end up with a traceback that doesn't show the code which originally raised the exception, like this:

```
   ERROR  06-23 08:26:27  base_events  Task exception was never retrieved
future: <Task finished coro=<FastChainSyncer.sync() done, defined at /home/salgado/src/py-evm/p2p/chain.py:122> exception=KeyError(b'(e\xed\x84\xeark\xf1\x8c\x9d\xb8/\xce\x9f\x
a0l\xe8\x11\xef\x88\x83\x933<4\xab\x15{\xc9+\xfa1',)>
Traceback (most recent call last):
  File "/home/salgado/src/py-evm/p2p/chain.py", line 135, in sync
    await self._sync(peer)
  File "/home/salgado/src/py-evm/p2p/chain.py", line 184, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/home/salgado/src/py-evm/p2p/chain.py", line 610, in _process_headers
    await self.wait(self.chain.coro_import_block(block, perform_validation=True))
  File "/home/salgado/src/py-evm/p2p/service.py", line 32, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/salgado/src/py-evm/p2p/service.py", line 51, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/home/salgado/src/py-evm/p2p/cancel_token.py", line 119, in wait_with_token
    return done.pop().result()
  File "/home/salgado/src/py-evm/trinity/utils/mp.py", line 27, in method
    args,
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: b'(e\xed\x84\xeark\xf1\x8c\x9d\xb8/\xce\x9f\xa0l\xe8\x11\xef\x88\x83\x933<4\xab\x15{\xc9+\xfa1'
```

In the log above, the `KeyError` was generated inside `coro_import_block()`, but one has no idea exactly where. We need to somehow retain/log that info so that we can debug those errors, otherwise it is really hard

**Comment by pipermerriam** [comment]
Might be worth seeing if the `result` there has a proper traceback tied to it and whether we can manually print the error using the [`traceback`](https://docs.python.org/3.5/library/traceback.html) module.  If so, we could add this handling code to our `async_method` (and maybe `sync_method`) decorators.

**Comment by gsalgado** [comment]
Inside `_callmethod()` `result` is an `Exception` instance with an empty `__traceback__`, so ISTM the only way to preserve the traceback would be to wrap our actual methods (e.g. `HeaderDB.get_canonical_block_hash()`) with something that catches any exceptions, extracts the traceback, saves it on the exception instance itself and then re-raises it. That way I believe we'd be able to access that in `result`

**Comment by pipermerriam** [comment]
It looks quite dirty but it looks like we could swap in our own `subprocess.Manager` class to do this.  Best path I see is to use a new subclass of `subprocess.managers.Server` with an overridden `serve_client` method which wraps the `conn` object in some way such that we can intercept `conn.send` when the message is an exception response.

**Comment by gsalgado** [comment]
That sounds quite nasty indeed, so I thought I'd try a different approach and came up with #1004. How do you feel about it?

**Comment by pipermerriam** [comment]
👍
