### ISSUE TITLE
Add more coverages for Trinity CLI tests

### ISSUE THREAD

**Issue by glaksmono** [ethereum/py-evm#973]
### What is wrong?
This is a follow-up to the discussion in https://github.com/ethereum/py-evm/pull/968#issuecomment-400944731

The coverages in the `trinity` CLI tests [here](https://github.com/ethereum/py-evm/blob/master/tests/trinity/core/cli/test_trinity_repl.py) is insufficient.

### How can it be fixed
Add more coverages for `trinity` CLI to at least include the following cases:

- [x] Make sure that in the case when IPC file is not found, then it prints error log
- [ ] Make sure that `trinity attach` works

**Comment by veox** [comment]
Likely can be closed in favour of issue #1472.

**Comment by cburgdorf** [comment]
@veox yep, thanks!
