### ISSUE TITLE
Reconsider MAX_REORG_DEPTH

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#978]
I chose 24 as the value for that constant but that's an arbitrary value as I couldn't find out any info about how long chain reorgs tend to be. We should reconsider that value, specially if we start seeing aborted peer syncs because we cannot find a common ancestor

**Comment by carver** [comment]
After moving to the skeleton sync, we will be able to naturally handle forks of ~6 days (at 15s block times). That should be sufficient for now, and it's not too hard to extend it.
