### ISSUE TITLE
Allowing multiple peer subscribers can be problematic

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#986]
### What is wrong?

A `p2p.Peer` can have multiple subscribers, and each of them will get a copy of every msg sent by the remote (which allows us to have separate services handling different subsets of messages), but that can be problematic if both subscribers request/process the same type of data as the data requested by one subscriber will be delivered to the other as well, and might interfere other's operation.

As an example, we currently have `LightChainSyncer` and `LightPeerChain` as peer subscribers when we run a light node, and they can both request/process `BlockHeader`s, and if the latter requests some headers while the former is in the middle of a sync with a peer, it may try to validate/process those headers and if that fails (which can happen when the headers are further ahead of our local chain head), it will cause the sync with that peer to be aborted. Although this is not that big a deal given that another sync will be triggered as soon as one of our peers notify us of a new block, it is something we need to be aware of. And we must consider other cases where similar issues might happen

The above can be seen in practice when running `tests/p2p/test_lightchain_integration.py` as it requests the remote's head (via `LightPeerChain`) while `LightChainSyncer` is in the middle of a sync, which causes the sync to be aborted.

### How can it be fixed

In the case above, it could be fixed by having `LightChainSyncer` keep the `request_id`s used in the `GetBlockHeader` requests sent by itself and only processing the replies for those, but that won't work for services using the `ETH` protocols because there the requests don't include a `request_id`

I need to think more about this, just writing it down now so I don't forget about it

**Comment by gsalgado** [comment]
@pipermerriam is this still an issue, with the subscription and round-trip request/response changes you've made recently?

**Comment by pipermerriam** [comment]
I don't think so.  closing.
